### ISSUE TITLE
FixedDataTableColumnReorderHandle.react

### ISSUE THREAD

**Issue by jsCTim** [schrodinger/fixed-data-table-2#10]
After running:
`npm install fixed-data-table-2 --save`

When I run I get the following error:
```
ERROR in ./~/fixed-data-table-2/internal/FixedDataTableCell.react.js
Module not found: Error: Cannot resolve 'file' or 'directory' ././FixedDataTableColumnReorderHandle.react in /workspace/myapp/node_modules/fixed-data-table-2/internal
 @ ./~/fixed-data-table-2/internal/FixedDataTableCell.react.js 20:40-94
```

I do not see the FixedDataTableColumnReorderHandle.react.js anywhere.

**Comment by KamranAsif** [comment]
This was fixed in https://github.com/schrodinger/fixed-data-table-2/pull/6
Just pushed a new release, 0.6.3 which should fix this.
