### ISSUE TITLE
Modifying filter after clicking to later results can end up with invalid X/Y numbers

### ISSUE THREAD

**Issue by sarahstanger** [schrodinger/fixed-data-table-2#102]
![image](https://cloud.githubusercontent.com/assets/7503329/21770624/046ba728-d652-11e6-8502-0ab9051d16f4.png)

## Expected Behavior

Modifying the filter should reset the X/Y results numbers

## Current Behavior

Modifying the filter after you have clicked to view a result > 1 can results in an invalid X/Y results number

## Steps to Reproduce (for bugs)
1) Using http://schrodinger.github.io/fixed-data-table-2/example-scroll-to.html, filter by a single letter
2) Click to see results > 1
3) Add to the filter so that the number of results is less than the result number you previously clicked to 
4) Continued clicking will continue to update the viewing number even though it is greater than the total number of results number

## Your Environment

* Version used: http://schrodinger.github.io/fixed-data-table-2/example-scroll-to.html
* Browser Name and version: Chrome Version 55.0.2883.95 (64-bit)
* Operating System and version (desktop or mobile): OSX 10.11.6
* Link to your project:

**Comment by KamranAsif** [comment]
Thanks for the detailed report. Threw up a quick PR

**Comment by KamranAsif** [comment]
Resolved in #103
