### ISSUE TITLE
Drag Drop columns: Breaks if you drop out of window

### ISSUE THREAD

**Issue by sisyphean2** [schrodinger/fixed-data-table-2#104]
## Expected Behavior
If you drag a column and release the floating column header indicator outside of the browser window, the column should snap back to the initial position. Or do something else sensible.

## Current Behavior
If you drag a column and release the header outside of the browser window, the column does not drop anywhere. The column header continues to be bound to mouse movement. Trying to drop the column may end up with a 500 error in which Live Design tries to pass a null value into the columns order array. Refreshing the page resolves the issue.

## Possible Solution
Detect if the header is outside the window on mouseup and return it to it's original position if true.

## Steps to Reproduce (for bugs)
Steps given in details above.

## Context
I was playing with drag drop testing edge cases! Nothing useful!

## Your Environment
Chrome Ubuntu.

**Comment by KamranAsif** [comment]
Looks like we need to create onColumnReorderCancel :/
