### ISSUE TITLE
Fixed things on versions >= 0.7.4 cause onScroll lagging

### ISSUE THREAD

**Issue by phuong3030** [schrodinger/fixed-data-table-2#106]
I tried example ReorderColumn.js with version > 0.7.3, but the scroll was lagging. 

## Environment

* Version used: > 0.7.3
* Browser Name and version: Chrome 55
* Operating System and version (desktop or mobile): Mac OS 10.11.6

**Comment by KamranAsif** [comment]
Closing since theres no follow up
