### ISSUE TITLE
Question: rowIndex how can I get it from a column or ColumnGroup

### ISSUE THREAD

**Issue by yanv1991** [schrodinger/fixed-data-table-2#111]
As the title says, is there a way to get the rowIndex from Column/ColumnGroup and not from the cell attribute ??

Also I wonder if the length of columns can vary inside a column group depending of the row, so i.e. first row has 2 column inside the column group and  the second one could have only one column inside the column group and so on...

**Comment by KamranAsif** [comment]
I'm not sure I understand your first question. When would you want the rowIndex outside of the cell?

As for the second, we currently don't support this but we plan to add it eventually

**Comment by yanv1991** [comment]
yes outside of the cell!!!

**Comment by wcjordan** [comment]
Hey @yanv1991 could you give a bit more detail; the scenario you're describing isn't clear from the description.  

One common way to access the row id outside of an element is to add a data attribute to the DOM in your cell renderer.  This can be useful if you want to interop with jQuery and select the element by row id or extract the row id in a native click handler.

I hopefully this points you in the right direction.

**Comment by yanv1991** [comment]
`<Column
                header={<Cell className="header-table">Transformation</Cell>}
                cell= { ({rowIndex, width, height}) => (
                  <Cell
                    width={width}
                    height={height}
                    className="my-class">
                    <p>.....</p>
                  </Cell>
                ) }
                width={250}
              />`

In the above code rowIndex lives inside the cell context, is there a way I can get it outside of the cell, for example from a ColumnGroup component

**Comment by wcjordan** [comment]
Since a ColumnGroup contains all rows, would you want a set of all row indexes in the grid?

**Comment by yanv1991** [comment]
Nevermind, the scenario doesn't make sense if my second question couldn't be implemented so far.

**Comment by wcjordan** [comment]
Ok cool, I'm going to close the issue.  Hopefully we'll have support for cells spanning multiple cols / rows sometime later this year.

**Comment by fes300** [comment]
Hi @wcjordan do you have any updates on the `cells spanning multiple cols` feature?

**Comment by wcjordan** [comment]
Nope, no one's explored that as far as I know.

**Comment by fes300** [comment]
thank you for the fast reply @wcjordan :)
