### ISSUE TITLE
Fixed Data Table inside react-simpletabs

### ISSUE THREAD

**Issue by rokkarinn** [schrodinger/fixed-data-table-2#114]
both react-tabs and react-simpletabs use this.props.children and when adding fixed-data-table inside a panel it results in this error:
Warning: Failed prop type: Invalid prop `children` supplied to `Panel`.

Is there a way of getting around this error?

I have react 1.10 and FixedDataTable 0.7.10 and react-simpletabs 0.7.0

**Comment by KamranAsif** [comment]
Can you provide us a jsfiddle to reproduce this error?

**Comment by rokkarinn** [comment]
Thank you for the reply.
I figured it out it wasn't a bug in Fixed Data Table it self it was a bug on my end. I forgot to add key to the parent component that had simpletabs and fixed data tables inside them. 

Thanks again for great component.
