### ISSUE TITLE
Warning in console when '100%' width is used on Table

### ISSUE THREAD

**Issue by c0debreaker** [schrodinger/fixed-data-table-2#124]
It works but I'm getting a warning in console. Warning: Failed prop type: Invalid prop "width" of type "string" supplied to "FixedDataTable", expected "number".

```
      <Table
             rowsCount={this.state.myTableData.length}
             rowHeight={50}
             headerHeight={50}
             width={'100%'}  <<<----------- on this line
             height={500}>
```

What's the proper way?

**Comment by KamranAsif** [comment]
@c0debreaker all heights and widths need to be defined in pixels as a number.
Fixed data table isn't responsive by default. 

You can follow this example for responsiveness: http://schrodinger.github.io/fixed-data-table-2/example-responsive.html
