### ISSUE TITLE
Dynamically resizing rows based on contents

### ISSUE THREAD

**Issue by hechlerp** [schrodinger/fixed-data-table-2#125]
I was wondering if there's a way to have your row height adjust to fit all of the data in a cell. It seems like it either is determined on initialization (with the rowHeight field on the table) or you would have to manually measure the size of the contents itself. However, I'm sure there's an easier way to allow automatic expansion that I've simply missed. Any help would be greatly appreciated!

**Comment by KamranAsif** [comment]
Someone was able to get this done in the past using CellMeasurer from react-virtualized
https://github.com/schrodinger/fixed-data-table-2/issues/21 

We most likely won't support this, although we would love a PR to add this as a demo
