### ISSUE TITLE
If I have inputs in one column, the value from one input will duplicate in input with the rowIndex=rowToShows+actual index

### ISSUE THREAD

**Issue by ana31** [schrodinger/fixed-data-table-2#128]
## Expected Behavior

Only the value for the input in witch I type will change.
## Current Behavior

The value that I am typing , appears in the input where I am typing and in the inputs that are for the rows with the index (m*n+currentIndex), where n is the number of rows that are visible before scroll the content and  0<m<listOfData.length.
<img width="210" alt="screen shot 2017-03-21 at 00 20 10" src="https://cloud.githubusercontent.com/assets/11799420/24124453/77fb0bdc-0dcc-11e7-86be-1e5b23ceca66.png">
<img width="211" alt="screen shot 2017-03-21 at 00 20 19" src="https://cloud.githubusercontent.com/assets/11799420/24124454/77fd2368-0dcc-11e7-824f-c5c2cc6a6d73.png">

## Possible Solution

Should be because of the keys rerender

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by KamranAsif** [comment]
You need add a key to your input to prevent it from being recycled. This isn't exactly a bug, because we like to reuse elements within a column since usually the diff is small (text changes).

Adding a key will fix this but might cause some perf slowdown, which is why we don't implement this in the lib

**Comment by angsanb** [comment]
I'm having the same issue. I tried having a unique id for the input box. Still the content of the cell is being copied like explained above. Any one have a solution for this?

**Comment by angsanb** [comment]
class TextAreaCell extends React.PureComponent {
    constructor(props) {
        super(props);
        this.state = {
            data: this.props.data,
            value: this.props.data[this.props.rowIndex][this.props.columnKey],
            validateFormularyInfo: this.props.validateformularyinfo,
            updated: false
        }

    }
    //if value is not updated locally (prevState.updated) then check if the new props value is different
    // if so then update the state.
    static getDerivedStateFromProps(nextProps, prevState) {
        let fcmFormId = nextProps.data[nextProps.rowIndex]["fcmFormID"];
        if (nextProps.data[nextProps.rowIndex][nextProps.columnKey] !== prevState.data[nextProps.rowIndex][nextProps.columnKey] && !prevState.updated) {
            return { data: nextProps.data, value: nextProps.data[nextProps.rowIndex][nextProps.columnKey] };
        }
        else if (nextProps.validateformularyinfo.indexOf(nextProps.columnKey + fcmFormId) >= 0 && prevState.validateFormularyInfo.indexOf(nextProps.columnKey + fcmFormId) < 0
            || nextProps.validateformularyinfo.indexOf(nextProps.columnKey + fcmFormId) < 0 && prevState.validateFormularyInfo.indexOf(nextProps.columnKey + fcmFormId) >= 0) {

            return { validateFormularyInfo: nextProps.validateformularyinfo };

        }
        else return null;

    }

    componentDidUpdate(prevProps, prevState) {
        let fcmFormId = prevProps.data[prevProps.rowIndex]["fcmFormID"];
        if (prevState.data[prevProps.rowIndex][prevProps.columnKey] !== this.props.data[prevProps.rowIndex][prevProps.columnKey] && !this.state.updated) {
            this.setState({ data: this.props.data, value: this.props.data[this.props.rowIndex][this.props.columnKey] });
        }

        if (prevProps.validateformularyinfo.indexOf(prevProps.columnKey + fcmFormId) >= 0 && this.props.validateformularyinfo.indexOf(prevProps.columnKey + fcmFormId) < 0
            || prevProps.validateformularyinfo.indexOf(prevProps.columnKey + fcmFormId) < 0 && this.props.validateformularyinfo.indexOf(prevProps.columnKey + fcmFormId) >= 0) {

            this.setState({ validateFormularyInfo: this.props.validateformularyinfo });

        }

        if (this.state.updated) {
            this.setState({
                updated: false
            });
        }

    }
    changeValue = (value) => {
        //debugger;
        this.setState({ value: value, updated: true });
    }
    render() {

        const { Cell } = FixedDataTable;

        const { data, updatescrollpos, onformularychange, onKeyPress, onfieldfocusout, ...propsWOData } = this.props;
        var value = this.props.data[this.props.rowIndex][this.props.columnKey];
        var tierValue = this.props.data[this.props.rowIndex]["tier"];
        var stTypeValue = this.props.data[this.props.rowIndex]["stType"];
        var fcmFormId = this.state.data[propsWOData.rowIndex]["fcmFormID"];
        var isReadOnly = propsWOData.readonly;
        if (propsWOData.columnKey == "stepMsg") {
            isReadOnly = (stTypeValue == 'NA' || tierValue == '9') ? 'readOnly' : isReadOnly;
        }
        var className = this.state.validateFormularyInfo.indexOf(propsWOData.columnKey + fcmFormId) >= 0 ? "inputItemInValid form-control" : "form-control";

        return (
            <Cell {...propsWOData} className="fixedTableCell" >
                <textarea
                    key={propsWOData.rowIndex + '-' + propsWOData.columnKey}
                    id={propsWOData.rowIndex + '-' + propsWOData.columnKey}
                    className={className}
                    style={{ width: '150px', resize: 'none' }} name={propsWOData.columnKey} type="text"
                    onBlur={(e) => onformularychange(this.props.rowIndex, e.target.name, e.target.value)}
                    onChange={(e) => this.changeValue(e.target.value)}
                    value={this.state.value}
                    readOnly={isReadOnly}
                    onKeyDown={(e) => updatescrollpos(e, propsWOData.columnindex)}
                    onFocus={(e) => updatescrollpos('onfocus', propsWOData.columnindex - 1)}
                />

            </Cell>

        );
    }
}

**Comment by pradeepnschrodinger** [comment]
@angsanb, nothing seems wrong at a glance... 

I suspect you might not have specified `columnKey` through `Column` component. So `propsWOData.columnKey` will be `undefined`, and hence all the calculated keys will be `NaN`

**Comment by angsanb** [comment]
> @angsanb, nothing seems wrong at a glance...
> 
> I suspect you might not have specified `columnKey` through `Column` component. So `propsWOData.columnKey` will be `undefined`, and hence all the calculated keys will be `NaN`

Thanks for the reply, The columnKey seems to be pulling correctly. When i inspect the element using Browser Developement tools. The Id of the Input box are different. 

**This is the first textarea input box**
<textarea name="notCovMsg" class="form-control" id="**0-notCovMsg**" style="width: 150px;" type="text">test</textarea>

**This is the 11th textarea input box**
<textarea name="notCovMsg" class="form-control" id="**11-notCovMsg**" style="width: 150px;" type="text">test</textarea>

**Comment by angsanb** [comment]
and an interesting thing to note is, When i don't maintain a local state for the textareaCell and update the parent state on the **OnChange** Event. It appears to work correctly. But i'm having performance issue as each keystroke takes time to appear as the parent state is a heavy element with lots of data and validation. Hence i want to maintain a local state and update that first and at the end when user focus out of the input i want to update the parent state.

**Comment by pradeepnschrodinger** [comment]
FDT recycles rows, and your component will be reused. Thus unless you change the state values through a function of row and column index, they will be retained.

So I think `getDerivedStateFromProps` is not returning the new state when the column/row index is changed. Try checking your conditionals.
