### ISSUE TITLE
scroll-on-drag while re-ordering columns

### ISSUE THREAD

**Issue by hsin421** [schrodinger/fixed-data-table-2#13]
Thanks for sharing your folk. 

We're also building the re-ordering of columns then we saw yours. 

Just curious, have you implemented the "scroll-on-drag" when you are re-ordering more columns that will fit the current page? We having issues on how to simulate horizontal scroll externally. If you have any ideas, please do share!

Thanks again

**Comment by KamranAsif** [comment]
Hmm this seems like a problem we will run into @wcjordan 

We know the scrollLeft value for the grid, and we know the left offset + width of the column drag. We can detect if we hit the left or right edge and change the scrollLeft value appropriately.

**Comment by hsin421** [comment]
Thanks for your fast reply!

We found that it's hard to control scrolling with `scrollLeft` or `scrollToColumn`

let's compare notes once we have clearer handle on this

**Comment by KamranAsif** [comment]
Hey,

I've merged this in but we have a couple more tasks until we release 0.6.7
Feel free to check it out
