### ISSUE TITLE
Request API to control scrollbar position

### ISSUE THREAD

**Issue by zhaoxq** [schrodinger/fixed-data-table-2#130]
My problem is:
In the case that there are many columns and horizontal scrollbar shows,  when user clicks on column title of right side column to sort, we programmatically move horizontal scrollbar to the most right via scrollToColumn API(keep column index in state), user manually drag scrollbar to the left, and then after a while, table get refreshed, scrollbar goes to the most right side since it follows the latest state of column Index.  
My thought to resolve this issue:
 We would like to get the new position via onScrollEnd API after user dragging, keep this in state, and use requested new API to move scrollbar to right position when rendering.

Let me know if there is better solution, thanks.

**Comment by wcjordan** [comment]
There's definitely some inconsistency in props and whether they should only be handled once or whether they should be held whenever they're on.  scrollLeft had this same problem and we solve it by only obeying when we receive a props value which is different than the existing scrollLeft prop value.
That approach has the benefit of not needing to expose a new external API, but leads to some hacky handling in componentWillReceiveProps.

@KamranAsif what are your thoughts on props handling for cases like this?

**Comment by zhaoxq** [comment]
Yes, I have this kind of props inconsistency problem in my REACT component development.  At the beginning I develop a component, this component controls some internal state, then there is needs to let parent component to pass in this state, so I add props to this component, props inconsistency comes along.

**Comment by KamranAsif** [comment]
There are two solutions here. One is a quick fix, where you can use the onHorizontalScroll to reset your state and not pass in the scrollToColumn value.

The other is a fix to the internals of FDT where we check to see if the prop has changed before scrolling. The problem with this solution is when the user _wants_ this to be the state.

**Comment by zhaoxq** [comment]
Thanks, this resolve my issue.
