### ISSUE TITLE
Scrolling doesn't work after webpack build

### ISSUE THREAD

**Issue by danielmittelman** [schrodinger/fixed-data-table-2#131]
## Expected Behavior
Scrolling of the table should properly work

## Current Behavior
When building the react-bundle with webpack with _devtool: 'eval'_, scrolling works as expected. 

When building without this property, scrolling doesn't work at all, and whenever a scroll event occurs, the following error is written to the console:

```
Uncaught TypeError: Illegal invocation
    at e.value (react_bundle.js:47:1216)
    at Object.r (react_bundle.js:45:10810)
    at i (react_bundle:45:6782)
    at Object.s [as executeDispatchesInOrder] (react_bundle.js:45:6997)
    at d (react_bundle.js:39:14889)
    at f (react_bundle.js:39:15015)
    at Array.forEach (native)
    at n (react_bundle.js:58:31503)
    at Object.processEventQueue (react_bundle.js:39:16003)
    at r (react_bundle.js:103:15107)
    at Object.handleTopLevel [as _handleTopLevel] (react_bundle.js:103:15209)
```

(I know the stack isn't informative, but this only happens in production)

Debugger screenshot:  [http://imgur.com/XQPXJTn](url)

## Steps to Reproduce (for bugs)
1) Build react_bundle using webpack
2) Load a pack with the fixed-data-table-2 component that contains more rows that can be displayed on screen
3) Try scrolling the rows down using the mouse wheel or using the scrollbar
4) The component refuses to scroll (though it's not stuck - buttons and links inside the component respond)
5) Errors are rapidly written to the console, only during scroll events

## Context
This bug forces me to build our react_bundle with 'eval' in production, which bloats the bundle and exposes our code to potential security problems

## Your Environment
Build is done on Ubuntu 14.04 with all the latest updates, using webpack 1.13 and React 15.2.1.
Problem occurs in all the browsers I've tested, and both on desktop and mobile: Chrome for Mac, Safari for Mac, Chrome for Android

**Comment by wcjordan** [comment]
This looks very similar to the issue dasnixon had here:
https://github.com/schrodinger/fixed-data-table-2/issues/22

He found it to be related to his uglifier so that may be a first place to look.
I'll try compiling our mainline with webpack 1.13 and see if it makes a difference

**Comment by danielmittelman** [comment]
Yep, updating Uglifier did solve the problem, great catch!

**Comment by wcjordan** [comment]
Glad it helped!
