### ISSUE TITLE
Feature Request: Ability to increase overscan / row buffering minimum and maximum

### ISSUE THREAD

**Issue by NathanBWaters** [schrodinger/fixed-data-table-2#132]
In my rows I have cells that can extend down about 30 rows.  Of course they disappear if I scroll down about 7 rows.  It would be great if I could specify how many rows should still be rendered that aren't within the boundaries of the table. 

## Expected Behavior
It would be great if I could pass as a prop the minimum row buffering as a prop into the fixed-data-table-2 Table component.  

## Current Behavior
It looks like it's hardcoded in FixedDataTableRowBuffer.js. 
var MIN_BUFFER_ROWS = 3;
var MAX_BUFFER_ROWS = 6;

## Possible Solution
The ability to pass as a prop the minimum row buffering as a prop into the fixed-data-table-2 Table component which then passes it down to FixedDataTableRowBuffer.js

**Comment by wcjordan** [comment]
I'm open to making this configurable through a prop.  Would you like to submit a PR which fits your use case?

**Comment by KamranAsif** [comment]
@NathanBWaters FB changed this internally to their codeset (but didn't upmerge)
Can you rip out the relative piece from this [PR](https://github.com/facebook/fixed-data-table/pull/402/files#diff-910f16a8185c911a9573fe267d0edfb3) and submit it to ours

**Comment by NathanBWaters** [comment]
@KamranAsif @wcjordan sweet, not sure when I'll be able to work on this but I'll keep you updated this week on a PR.

**Comment by NathanBWaters** [comment]
@KamranAsif @wcjordan working on it today!
Novice question, but is there a better way to test out new changes?  

When trying to work on the fork by testing it out inside my current project, I had to do the following to get it to work:

1) Git clone a fork of the project into my project's `node_modules/`
2) Run `npm install` in `node_modules/fixed-data-table-2` (which is my fork)
3) Make modifications in the `src/` folder
4) Run `npm run build-npm`

So now every time I make a change I have to run `npm run build-npm` again.

**Comment by NathanBWaters** [comment]
@KamranAsif @wcjordan 
Feedback on https://github.com/schrodinger/fixed-data-table-2/pull/135?

**Comment by KamranAsif** [comment]
@NathanBWaters You can run npm run site-dev-server to get the example site running with demos.

**Comment by NathanBWaters** [comment]
@KamranAsif nice!  I'll play around with that.

**Comment by KamranAsif** [comment]
Resolved
