### ISSUE TITLE
Question about image cell re-renders

### ISSUE THREAD

**Issue by mirko77** [schrodinger/fixed-data-table-2#133]
Hi guys, awesome stuff!

One question, though. I implemented FixedDataTable2 with Redux on an application (which is live [here](https://five.epicollect.net/project/bestpint/data))
If you scroll up and down quickly you will notice the images are replaced a bit later due to the lazy loading, but the old image is still there...(cached by the previous render pass)

Any tips on how to avoid it? I had a look at your examples which uses react state, try to set a `shouldComponentUpdate` to return false when the url is the same, I tried to add a `componentWillUnmount()` which is never called...

Ideally, I would remove the image not in view with an empty cell/src, any ideas?

Does FixedDataTable expose a way to know if a cell is in view or hidden?

Thanks

**Comment by wcjordan** [comment]
This generally happens due to row recycling.  The easiest way to fix is to add a key to your img tags so a new one is generated instead of reusing the old one when the row is recycled.

**Comment by KamranAsif** [comment]
Hey,

Great question, we've seen this issue as well. The main problem is that react won't unset the src while the next image is loading.

Our solution was to add a key to the react image component to force react to throw away the reconciliation.

The downside of this approach is you'll lose some performance. We found marginal gains using a wrapper component that re-uses the image dom element but swaps the src to null when loading. This might be over kill for your solution.

@wcjordan We should probably start a wiki for these common issues

**Comment by wcjordan** [comment]
Ya, I agree, a wiki or FAQ page would be nice

**Comment by mirko77** [comment]
Thanks for the fast response, I will give it try!
