### ISSUE TITLE
pagination documentation

### ISSUE THREAD

**Issue by vinnyoodles** [schrodinger/fixed-data-table-2#14]
I was confused on the pagination example because there were a lack of links for pagination (ex. first, last, next, previous, page #). Could you add some documentation for adding pagination to a table?

**Comment by KamranAsif** [comment]
Hmm I think you are referring to paged data. The [example](http://schrodinger.github.io/fixed-data-table-2/example-pagination.html) Refers to an infintite scrolled table that has data paged in

I guess we should make a separate example that swaps out the data when user goes to a different 'page'. 

Lets do an example like this: http://dev.sencha.com/deploy/ext-4.0.0/examples/grid/paging.html

**Comment by KamranAsif** [comment]
@wcjordan Any idea what happened to this ticket?

**Comment by wcjordan** [comment]
It's in our current sprint.  I think Felicia is going to use it as a case to get more familiar and help with the repo.  Should be tackled after the column group work is done.

**Comment by KamranAsif** [comment]
I'm closing this since we can track it in jria
