### ISSUE TITLE
Proposal: Switch to Semantic Versioning

### ISSUE THREAD

**Issue by KamranAsif** [schrodinger/fixed-data-table-2#140]
We've been adding some new features to FDT2 in releases:
- pureRendering 0.7.14
- rowKeyGetter 0.7.12
- onVerticalScroll 0.7.9

It's not obvious for developers that we have this new feature because we increment patch version instead of minor version.

I propose we switch to v1.0.0 and switch to semantic versioning
- a bug fixes gets a patch verison increase, e.g. v1.0.1
- a new feature gets a minor version increase, e.g. v1.1.0
- a breaking change gets a major release, e.g. v2.0.0

Our roadmap has our Redux Migration which should be considered a major release in my opinion.
I'm interested to hear other folk's thoughts.

**Comment by wcjordan** [comment]
Having discussed offline w/ Kam, I agree with pushing hard for Redux migration and make that v1.0.  The downside is we'll unlikely have a chance to improve our API for a while, but we should be at a better place and have much easier maintainability.

**Comment by KamranAsif** [comment]
@wcjordan How do you feel about switching to 1.0 for column-reuse? I'm afraid that we haven't covered all edge cases and we might potentially break some customers.

**Comment by wcjordan** [comment]
That seems the prudent course to me.  I don't think 8.0 beta is 6 months out though.  I'd like to push it in 1-2 months from now.  Let's offline to discuss timeline & how that affects a 1.0 for column reuse.

**Comment by wcjordan** [comment]
This should be the case now
