### ISSUE TITLE
Selecting multiple rows by clicking rows

### ISSUE THREAD

**Issue by nextofsearch** [schrodinger/fixed-data-table-2#141]
Hi,

Is there anyway to select rows by clicking rows? I want to make something like the table in the link [here](http://www.ec2instances.info/). If you look at it you can click a row, which will be highlighted then you can compare selected rows by clicking a button labeled 'Compare Selected'

I am new to fixed-data-table-2 so wondering if it provides similar features.

Thanks,

**Comment by KamranAsif** [comment]
FDT avoids behind a kitchen sink so we don't provide this.
It's very easily to build though. Just add a click handler on your cell, and with that you get the rowIndex.

When rendering, just check if the current rowIndex is part of some selected set, and if so, render it with some class indicating selection

**Comment by wcjordan** [comment]
This is a good candidate for a new example if you'd like to play around with it in that environment and submit a PR? :)

**Comment by nextofsearch** [comment]
@KamranAsif Thanks for the comment. I will try.
@wcjordan Not sure I can make it but I will share it here if done. ;)

**Comment by nextofsearch** [comment]
@KamranAsif One more thing, If a table has thousands of rows, would toggling between all rows and selected rows by clicking the button take too much time if we have to re-render it? I would hide/unhide them using jQuery, what's the best way for React?

**Comment by KamranAsif** [comment]
FDT only renders rows on screen

**Comment by KamranAsif** [comment]
Any reason to keep this open?
