### ISSUE TITLE
Add option to disable scrolling

### ISSUE THREAD

**Issue by vocu** [schrodinger/fixed-data-table-2#143]
I believe currently there's no way to disable the scrollable state, in which the table just renders independent of a specific height/maxHeight.

**Comment by KamranAsif** [comment]
http://schrodinger.github.io/fixed-data-table-2/api-table.html#-overflowx-

overflowX={hidden} will hide the scrollbar and disable scrolling.

**Comment by vocu** [comment]
@KamranAsif Does height/maxHeight still need to be specified in order for the table to be shown? The table disappears without those attributes it seems. Might there be a way to show all table rows, with no scrollbar, and no specific height?

**Comment by KamranAsif** [comment]
@vocu height is required to render the table. We don't support any sort of fancy flex height

**Comment by vocu** [comment]
@KamranAsif So theoretically, if I wanted to render the entire table always, I can just set maxHeight to some arbitrarily large number such that the table will always fit its contents?

**Comment by KamranAsif** [comment]
IIRC maxHeight works such that if content > maxHeight, use maxHeight. If content < maxHeight, use context height as height.

If you use normal height, that'll always be the height. If you have less content than the height, you just see blank space on the bottom

**Comment by vocu** [comment]
@KamranAsif Thanks for your response, I guess the only way to make sure that all rows are shown without a scrollbar being rendered in the table is if maxHeight is set to some arbitrarily large number. Do you know if there's a limit to how high maxHeight can be set?
