### ISSUE TITLE
Support React 15.5

### ISSUE THREAD

**Issue by cfblaeb** [schrodinger/fixed-data-table-2#145]
I'm getting 2 warnings (see below)
The second one seems important.

Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
Warning: Scrollbar: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

I'm using react@15.5.3 and fixed-data-table-2@0.7.14

**Comment by KamranAsif** [comment]
Thanks for bringing this up.
@wcjordan  What's the best way to support this? In 15.5+ we need to require PropType separately. 
But we can't do that for libs lower than 15.5...

**Comment by wcjordan** [comment]
It looks like importing prop type separately should be fine for 0.14+
For createClass I suggest we cleanup / cutover unless it looks like too much work.

React Redux PR for reference: https://github.com/reactjs/react-redux/pull/663/files

**Comment by KamranAsif** [comment]
Interesting. I guess that means on < 15.5 we just have prop types included twice; one as part of react and once as part of this repo.

I wonder if tree shaking removes prop types in prod mode..

**Comment by kevflynn** [comment]
Any status on this PR?

**Comment by wcjordan** [comment]
Right now we're working on getting [support for create-react-class](https://github.com/reactjs/react-docgen/pull/179) into react-docgen.  After that, we have a few other things to cleanup & need to verify we're not breaking anything, but it shouldn't be long.  

I think we can get a release out with it early next week if nothing goes wrong.

**Comment by KamranAsif** [comment]
Biggest blocker right now are these amazing jungles and caves in Puerto
Rico. =D
I have a long flight Saturday so expect an update then.

On Apr 26, 2017 9:44 PM, "Chris Jordan" <notifications@github.com> wrote:

Right now we're working on getting support for create-react-class
<https://github.com/reactjs/react-docgen/pull/179> into react-docgen. After
that, we have a few other things to cleanup & need to verify we're not
breaking anything, but it shouldn't be long.

I think we can get a release out with it early next week if nothing goes
wrong.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/schrodinger/fixed-data-table-2/issues/145#issuecomment-297588086>,
or mute the thread

**Comment by KamranAsif** [comment]
@cfblaeb can you check out the PR and see if you have any issues?

**Comment by cfblaeb** [comment]
Which git command will checkout that PR?

**Comment by jphamilton** [comment]
It's not going to be as easy as switching to use prop-types and create-react-class. The use context will trigger warnings, too.

**Comment by wcjordan** [comment]
We're getting close to pushing this in and haven't seen any warnings related to using context.  I also don't see anything in the blog post here: https://facebook.github.io/react/blog/

Could you elaborate on what context issues you expected?

**Comment by jphamilton** [comment]
@wcjordan It was probably me, but I kept getting the warnings about using prop type validation functions...when I wasn't. This was on components that I had written. When I rewrote them to remove context, the warnings went away. If you are not getting them, it's all good I'm sure.

**Comment by wcjordan** [comment]
Interesting, since FDT doesn't use React context internally, I think we're safe to see what happens, but I'll keep an eye out on our examples which encourage using context.

**Comment by KamranAsif** [comment]
Resolved in 0.17.6

**Comment by IanVS** [comment]
To save future travelers a little confusion, I think it was actually [v0.7.16](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v0.7.16).
