### ISSUE TITLE
Does this version support display 'No Data...' in a whole line? 

### ISSUE THREAD

**Issue by szhuangx** [schrodinger/fixed-data-table-2#148]
In my business model, The data table could be empty in most of time, so, can we support 'No Data found...' in a whole line when my record is empty.

## Possible Solution
If there another way to to change the one cell style to fill out whole line.

## Your Environment
React+webpack+fixed-data-table-2

**Comment by wcjordan** [comment]
Is the goal to display on line among many which says no data but the cell spans many columns or is it to show a no data message when there are no rows?

If the goal is to show a no data message when no rows, it should be very easy to implement.  You would create a HOC for FDT which renders just FDT if rows exist and if no rows exist you would render FDT (if you want to see the headers) followed by a div containing your desired message.

**Comment by szhuangx** [comment]
Thank you, I't a good suggestion.
