### ISSUE TITLE
Ability to add ClassName to Row Wrapper

### ISSUE THREAD

**Issue by jakeseaton** [schrodinger/fixed-data-table-2#151]
I am trying to use [react-select](https://github.com/JedWatson/react-select) to allow users to edit the content of cells. The select dropdowns get cut off, because the rowWrapper and all of its descendants have overflow: hidden on them.

<img width="297" alt="screen shot 2017-04-20 at 11 17 58 am" src="https://cloud.githubusercontent.com/assets/7296193/25238807/58ec5112-25bc-11e7-8f12-0f08b0e505e9.png">

The api doesn't seem to expose any ability to conditionally add a class to the row wrapper, so I am having to use jquery when cells are clicked, and then override the overflow-y.

```javascript
<Cell
    onClick={e => $(e.target).closest(".fixedDataTableRowLayout_rowWrapper").addClass("clickedRow")}
/>

```

It would be great if I could do something like

```javascript
<Table
    rowClassName={rowIndex => rowIndex === clickedRowIndex && "clickedRow" }
/>
```

**Comment by wcjordan** [comment]
Your best bet may be to follow Kam's advice here #48 

We also have open issues #60 and #33 which could benefit from some details on your use case for future library improvements.

**Comment by jphamilton** [comment]
@jakeseaton Can you elaborate on what you did with jquery? I can't even get my hacks to work, so any insights would be helpful.

**Comment by wcjordan** [comment]
This is now supported w/ the rowClassNameGetter prop on the Table component
