### ISSUE TITLE
Touch scroll unusable in v0.7.16

### ISSUE THREAD

**Issue by maksis** [schrodinger/fixed-data-table-2#155]
## Expected Behavior

The table scrolls smoothly while touching and moving the finger, as with 0.7.15

## Current Behavior

It jumps to a new position only after lifting the finger

## Steps to Reproduce (for bugs)

I can reproduce it with your touch example after building the site with the latest version

## Your Environment

Latest versions of Chrome, Firefox and Edge on Win 10, it's the same also on Android

**Comment by wcjordan** [comment]
Thanks for filing this.  I can reproduce on our example and will take a look sometime later today.  Hopefully it's a quick fix.  Sorry for the issues.

**Comment by wcjordan** [comment]
Put a fix up with #157
