### ISSUE TITLE
Add events onMouseEnter/Leave for Cells

### ISSUE THREAD

**Issue by pszalanski** [schrodinger/fixed-data-table-2#16]
It would be a really convenient feature if I could have onMouse* Events for cells. Say, I want to display an icon as soon as the user hovers over a specific cell, to give a hint, that an action can be performed on the cell.

Right now, I can get these events only for the complete row. The cell or column the user hovers over at that time cannot be reconstructed, as far as I can tell.

**Comment by KamranAsif** [comment]
You can easily do this yourself by adding event handlers to individual cells.
Example: https://jsfiddle.net/pvt3dc1r/

The only downside is that adds 2 listeners per cell which can hurt performance depending on how many you have on screen.
