### ISSUE TITLE
Update Documentation to 0.7

### ISSUE THREAD

**Issue by leafoflegend** [schrodinger/fixed-data-table-2#160]
## Possible Solution
Your releases show that your current version is 0.7.17. The documentation seems out of date. It still lists the 0.5 API, as well as talks about the 0.6 roadmap. It also generally feels like an exact copy of Facebooks documentation, which was done a year and a half ago. So update the documentation to the most recent version of the library.

## Context
You've continued to improve on a world class table - it should have documentation to match! It would also make developing with this table infinitely easier.

**Comment by wcjordan** [comment]
Thanks.  We've discussed deleting the 0.5 API docs & 0.6 migration doc (I think that's what you mean instead of roadmap).  So this is welcome for anyone who wants to submit a PR.

The roadmap is also out of date with version numbers.  I'll update that when possible.

**Comment by KamranAsif** [comment]
I think we can use this for the 1.0 potentially breaking version

**Comment by wcjordan** [comment]
Updated the roadmap w/ #171.  I'll delete the old docs on the v0.8 (2.0) branch.

**Comment by pradeepnschrodinger** [comment]
Closing the issue since the updated docs were released with [v1.0.0](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v1.0.0).
