### ISSUE TITLE
Better Collapsible Row Example

### ISSUE THREAD

**Issue by leafoflegend** [schrodinger/fixed-data-table-2#161]
## Expected Behavior
Instead of simply having a collapsible row make the height increase, it should show additional content, or ideally, additional rows that are children of the parent row that was just collapsed.

## Current Behavior
Only increases the height of a row when collapsed.

## Steps to Reproduce (for bugs)
http://schrodinger.github.io/fixed-data-table-2/example-collapse-rows.html
Click on the Collapse Arrow on any row.

## Context
It makes the collapse feature somewhat useless.

**Comment by wcjordan** [comment]
Good idea.  This would be a good case for someone looking to get more involved with the library.

**Comment by spinningarrow** [comment]
> additional rows that are children of the parent row that was just collapsed

This is what I'm looking for. How do you envision this would work? By splicing the new rows into the data set in the component state?

**Comment by wcjordan** [comment]
You could try that.  Another approach would be to expand the row height and then use render a div which is on top of / "escapes the cell" to show what you want.  Kind of like a [portal](https://github.com/tajo/react-portal) or tooltip, but styled to look like it's part of the grid.

**Comment by spinningarrow** [comment]
> expand the row height and then use render a div which is on top

I think that would involve a whole lot of styling fixes in order to look smooth. Even vertical align will need changing (currently it's in the middle, but simply changing to `top` won't do the trick because that would make the text move up relative to where it is normally placed)…

Is there a way to conditionally render rows in the table?

**Comment by wcjordan** [comment]
Ya definitely would take styling work.

Conditionally rendering rows is easy.  I'd take a look at some of the filter examples and look at implementing the opposite.  That's probably the best way to go if you want the sub rows to look similar to the normal rows.

**Comment by wcjordan** [comment]
Closing via #186

**Comment by leafoflegend** [comment]
Sorry, this got lost in a mountain of notifications for me. I looked at the new behavior and would argue this is still not the ideal version of this feature. The additional content this allows is not really a new row per say - just a large div. The version of this I think many developers are looking for is a row with cells. Probably offset by one cell (but entirely up to interpretation and discussion). The current solution is still non-ideal and feels jury-rigged.

**Comment by wcjordan** [comment]
That functionality sounds like the inverse of what the client-side filter example does.  Have you tried that?  And if so could you describe how what you want is different than adding new rows to the table?

**Comment by leafoflegend** [comment]
I don't really understand how a client side filter has anything to do with what I mentioned. How I mean, is that these new `SubRows` don't have columns, they don't have `SubRowIndex`, etc. One might be able to think of once you collapse a row, you are looking at a nested table (with all the same functionality internally as the parent table). Super ideally, this would be recursive and could go any level deep. Appending a large block to a row is not adding an additional row, it is appending a large block.

**Comment by wcjordan** [comment]
Do you have a screenshot of what you're thinking?
I'm confused a by "looking for a row with cells" and it's problematic that "new SubRows don't have columns".

If these new rows have the same columns as the grid, I would recommend they just be new rows, maybe with some additional state for formatting the first cell differently.

If these new rows do not have the same columns as the grid, then the large block is an open canvas for you do do whatever you'd like with.  This could be adding a new fixed data table with different columns if desired.
