### ISSUE TITLE
Infinite scrolling / lazy loading on touch interfaces?

### ISSUE THREAD

**Issue by alexandergunnarson** [schrodinger/fixed-data-table-2#165]
Just a quick question: is infinite scrolling / lazy loading supported on touch interfaces (specifically an iPad Pro running the latest Chrome)? I see scrolling is supported — and it's buttery smooth, which is amazing! — but what about infinite/lazy scrolling?

Thanks for your help!

**Comment by wcjordan** [comment]
Infinite scrolling should work fine on mobile as should lazy loading.  One important thing to note is FDT doesn't provide lazy loading, but expects you to build that on top of the grid.  See the [Pagination Example](https://github.com/schrodinger/fixed-data-table-2/blob/master/examples/PaginationExample.js) for how this can be implemented.

**Comment by alexandergunnarson** [comment]
Sounds good! Thank you!
