### ISSUE TITLE
Default CSS doesn't style the table correctly

### ISSUE THREAD

**Issue by KazeSenoue** [schrodinger/fixed-data-table-2#176]
I'm trying to implement this component into my project, however the table doesn't get styled correctly, even though the default CSS is getting loaded normally.

## Expected Behavior
Table is styled, looking like the examples.

## Current Behavior
Table is styled, however it doesn't look like the examples, or like a table at all. (See https://streamable.com/3cib5)

## Steps to Reproduce (for bugs)
Code: https://gist.github.com/KazeSenoue/0a4422b4060dd606a21fb28df40192fa

## Your Environment
* Version used: Latest
* Browser Name and version: Chrome, latest
* Operating System and version (desktop or mobile): Windows 10, Desktop, Latest
* Link to your project: Closed source, sorry.

Ps.: My project uses the [React Static Boilerplate](https://github.com/kriasoft/react-static-boilerplate) as base (that means it also uses webpack, though I'm not sure if that's what's causing this issue).

**Comment by KamranAsif** [comment]
Did you include the default stylesheet dist/fixed-data-table.css?

**Comment by KazeSenoue** [comment]
Yes. I tried doing that through `include`, `require`, and even on `webpack.config.json`. None of them worked.

**Comment by KazeSenoue** [comment]
I forgot to mention that if I import the css like so (`include s from `fixed-data-table-2/dist/fixed-data-table.css`) and set the `className` attribute on the `Table` tag, it does load the style for that class normally.

**Comment by wcjordan** [comment]
That's bizarre.  Could you demonstrate the issue in a jsFiddle or do you have a public repo which reproduces the issue?  It sounds like it's related to your build system so will be difficult for us to resolve without reproduction.

**Comment by KazeSenoue** [comment]
I don't think I'm allowed to show much, but I believe if this is an issue with my build process it would be in Webpack's config file, right? Here's what I'm working with: https://gist.github.com/KazeSenoue/e0259c3cb57359fc541a650563c43077

**Comment by KamranAsif** [comment]
Resolved
