### ISSUE TITLE
Column#prop.headerClassName does not seem to work.

### ISSUE THREAD

**Issue by jspears** [schrodinger/fixed-data-table-2#193]
## Expected Behavior

Expect a classname to be added to the list of classes, as per documentation.

## Current Behavior

<Column headerClassName='whatever' .../> does not put the whatever class in.

**Comment by miskreant** [comment]
I do think the docs are a bit confusing here.. But my take on the statement

`'headerClassName' - This can be set directly on the `header` element.`

Is that 'headerClassName' isn't actually a prop, but just a name to provide context, in which case you should do something like:

`
        <Column
          columnKey="firstName"
          header={<Cell className="YOUR-CUSTOM-CLASS">First Name</Cell>}
          cell={<TextCell data={dataList} />}
          fixed={true}
          width={columnWidths.firstName}
          isResizable={true}
        />
`
Which will then add the class onto div.fixedDataTableCellLayout_wrap1 for the appropriate header cell. (@wcjordan correct me if I'm wrong) but hopefully that helps you there and I'll see about cleaning up the docs there.

**Comment by wcjordan** [comment]
Jeremy's read is correct.  I think headerClassName is only mentioned in the v0.5 Column docs and the v0.6 migration docs.  It was removed in v0.6 in favor of just setting it directly on the header element.

Let me know if you see it elsewhere and we can remove.
