### ISSUE TITLE
I don't have an issue ...

### ISSUE THREAD

**Issue by cephirothdy2j** [schrodinger/fixed-data-table-2#195]
I just wanted to say thanks for picking up and maintaining this awesome library since the original authors let it die, and to point out that, because of schrodinger, this project is simultaneously dead and alive.

**Comment by wcjordan** [comment]
Thanks!  It's always good to get feedback on the work.  And hopefully we won't disappoint with the new functionality and performance improvements we're working to cleanup and merge in for a v1!

![image](https://user-images.githubusercontent.com/1034455/28440227-5317c06a-6d73-11e7-9171-163b6cc2383a.png)
