### ISSUE TITLE
row animation (slide up)

### ISSUE THREAD

**Issue by lsentkiewicz** [schrodinger/fixed-data-table-2#196]
I need to implement slide up animation and I am not sure if this is possible.

Example:
![image](https://user-images.githubusercontent.com/4478684/28781355-0bc17d60-760a-11e7-8561-29e16f19e681.png)

- Select 2nd checkbox
- there is a button that removes the row from the table
- 2nd row is removed, and 3rd+ rows should go up

Currently, all rows have absolute positions. Is there any easy way to do that?

**Comment by wcjordan** [comment]
Hey there, you can remove the row from the table by updating your source data.  I recommend looking at the [client filter example](http://schrodinger.github.io/fixed-data-table-2/example-filter.html) for inspiration.

I'm less sure about the animation, but I think with some CSS and the right React keys using [rowKeyGetter](http://schrodinger.github.io/fixed-data-table-2/api-table.html), you may be able to do it.
