### ISSUE TITLE
How can we freeze columns to the right of table?

### ISSUE THREAD

**Issue by xhe** [schrodinger/fixed-data-table-2#197]
I know if we want to freeze columns, we just need to set fixed=true on the column configuration. In most cases, this is pretty good, but we have some requirements to put the fixed columns to the right of the table. This is just in the opposite of current solution, which pushes all the fixed columns to the left side of the table.

Is this doable? If not in product, can anyone tell me where I can change the code to make this possible?

Thanks

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by wcjordan** [comment]
Duplicates #121 so I'm going to close.  Please continue the conversation there.

**Comment by xhe** [comment]
Any plan to provide right fixed column solution soon?
