### ISSUE TITLE
Thanks for maintaining.  First release?

### ISSUE THREAD

**Issue by wavded** [schrodinger/fixed-data-table-2#2]
Just curious how you are planning to do releases.  Are you going to pick up a new package name, take over the existing?  And when do you anticipate a first release to be ready?  Thanks much!

**Comment by KamranAsif** [comment]
We will rename it to fixed-data-table-2 for now. I've pushed a release for v0.6.1 on npm as well.

We will be publishing minor versions every few months, and major versions once or twice a year.

We want to take over the existing one, but there is no time table yet.

**Comment by flipperkid** [comment]
We also plan to actively merge in pull requests and release patch versions with those changes.
Also if anyone has suggestions for a better name than fixed-data-table-2, we're open to them.

We're currently QA'ing a new release of our product having migrated it to FDT and will continue to get testing support there for IE11, Chrome, and Firefox.  It would be useful to get an idea of how we can fill in the gaps and make sure we don't have issues in other browsers.

**Comment by burakcan** [comment]
@wcjordan Hello, thank you for forking. We're also using fixed-data-table extensively at Adphorus and i was planning to start a fork, then saw your repo :) 
It would be nice to see what changed across releases to not to break stuff in our apps. Do you plan to publish changelogs with releases?
Also; i would be happy to help  you with this. I think we can add some bugfix tasks to our company's sprints sometimes. I also can help with bugs, features or pr reviews, personally.
Thank you again.

**Comment by KamranAsif** [comment]
Hey,

I updated our release logs. They are auto generated so we need to manually go and edit them.
As for helping out with tasks, that would be greatly appreciated!

**Comment by burakcan** [comment]
Great! Thank you 💯 
I'll be watching for the issues then

**Comment by wcjordan** [comment]
@burakcan thanks for the support, we're very happy to have any help you can give us!  

With regards to releases, our current plan is to try and release minor fixes with a patch version bump every week or so while we're bringing in pull requests from the Facebook repo.  We also have plans to add tests to the repo over the next couple months so we can prevent regressions.

Where possible, we'll try to put any risky changes in but disable them by default under a flag.  We'll also start work on more aggressive changes targeted for the next minor version bump.  Server side rendering and touch scrolling seem to be the focus of requests so far.

Please let us know if you have any concerns with that approach, any test examples you'd like us to test against, and any feature areas of interest.  Thanks!
