### ISSUE TITLE
is there a way to edit in place ?

### ISSUE THREAD

**Issue by sandys** [schrodinger/fixed-data-table-2#202]
hi,
Really sorry if this is the wrong place to file this.
I'm looking at this bug https://github.com/facebook/fixed-data-table/issues/249 and i tried to look at the code... but didnt find anything

 Is there any possible way to use an editor with FDT2 ?

**Comment by wcjordan** [comment]
Ideally a question like this should be asked in [discord](https://discord.gg/bPSWD73) or stackoverflow.

It's possible to edit in place by defining a [cell property](http://schrodinger.github.io/fixed-data-table-2/api-column.html) on a column as a React component which renders an input or other editable DOM component.  That would need to be hooked up to update the store which your rows render from when changed.

There's no code related to this as it's external to the library's functionality, but possible to add with the right cell renderer.
