### ISSUE TITLE
Is there a way to remove the vertical scrollbar space?

### ISSUE THREAD

**Issue by ardok** [schrodinger/fixed-data-table-2#203]
I have made sure that the table has height enough for the entire rows.
`this.props.rowData.length * this.props.rowHeight + this.props.headerHeight + 17`

`17` there is for the horizontal scrollbar space.

## Expected Behavior
When there is no vertical scrolling needed, vertical scrollbar space should disappear?

## Current Behavior
The space for vertical scrollbar is still there even when there is no need for vertical scrolling.

## Possible Solution
To my understanding, this scrollbar is actually "fake", not built-in.
Maybe have a way to hide / show vertical / horizontal scrollbar?

## Steps to Reproduce (for bugs)
https://jsfiddle.net/qtnhu4m8/1/

Just scroll all the way to the end of the horizontal scrolling. You'll see that there's an empty space for vertical scrollbar.

## Context
I'm trying to have a "fixed" right columns (https://gist.github.com/ardok/4aa9500f5dae3b462427b7cd54404176).

But due to this, the fixed right columns are going to have horizontal scrolling :(
![image](https://user-images.githubusercontent.com/1380581/29339229-1cbaa84c-81ce-11e7-888c-d027f035f147.png)

![image](https://user-images.githubusercontent.com/1380581/29339225-16c609e0-81ce-11e7-8bd2-647f8468ae68.png)

## Your Environment
* Version used: 0.8.0
* Browser Name and version: Chrome Version 60.0.3112.101 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Desktop MacOS Sierra 10.12.6 (maxed out specs)
* Link to your project: https://jsfiddle.net/qtnhu4m8/1/ (not with fixed right columns, but enough to show the vertical scrollbar space)

**Comment by miskreant** [comment]
Thanks for the find @ardok, I've got a fix pending here https://github.com/schrodinger/fixed-data-table-2/pull/204

**Comment by wcjordan** [comment]
Sorry for the delays on #204, this should be fixed on the v1.0 beta if you want to try it there.

If you want to try that and give use feedback you can set package.json to point to 1.0.0-beta.3 of fixed-data-table-2 or run yarn add fixed-data-table-2@beta

**Comment by wcjordan** [comment]
This is now fixed w/ v0.8.2

**Comment by miskreant** [comment]
@ardok, I introduced an issue in 0.8.2 which caused an incorrect calculation of the body height when the row count changes, you'll want to use 0.8.3 when it gets released instead.
