### ISSUE TITLE
Scrolling up and down makes cells render with the wrong values

### ISSUE THREAD

**Issue by Kxze** [schrodinger/fixed-data-table-2#205]
## Expected Behavior
Checkboxes are either checked / unchecked according to the logic passed to the `<Cell>` object.

## Current Behavior
When scrolling up and down, the checkboxes get re-rendered (I assume), and sometimes do so with the wrong value on `defaultChecked`.

## Steps to Reproduce (for bugs)
(Can't reproduce on jsfiddle without a big chunk of data)

## Context
I have a relational table where every input is a checkbox [like so](http://i.imgur.com/tdpqH2z.png). Some checkbox need to come checked according to the data it's receiving. This works fine, except for when I scroll down and back up, then the checkboxes get re-rendered and sometimes they don't re-render with `defaultValue` as true when they should and vice versa.

I have a small clip showing this happening: https://my.mixtape.moe/apauis.mp4
and the relevant code on a gist: https://gist.github.com/Kxze/8df3defd75918adcd55ca0b6512b19f9

I assume this is happening because I'm using `find`, which is making the checkboxes hang when being re-rendered, thus getting the wrong value.

## Your Environment

* Version used: Latest on npm
* Browser Name and version: 60.0.3112.90 64 bits
* Operating System and version (desktop or mobile): Windows 10 64 bits
* Using: webpack and react static boilerplate

**Comment by Kxze** [comment]
I edited the code to make a simple `Array#includes` check instead of the more resource-heavy `Array#find` and the bug still occurs. Setting `allowCellsRecycling` to `false` also didn't help.

**Comment by wcjordan** [comment]
Could you try adding a key onto the cell components which have checkboxes?  Since React recycles components & FDT recycles rows for performance, you can end up with the cell from one row being updated and used as the cell of a new row.  #128 & #18 have similar cases.

I'm going to close this assuming that's the issue, but if it doesn't fix the problem please re-open.
