### ISSUE TITLE
Is there a way to add one cell to take the whole row?

### ISSUE THREAD

**Issue by xhe** [schrodinger/fixed-data-table-2#208]
Hi, I do not know if this is doable, at least, I could not find out solution at all.

In general we have a data grid already, but now, we have requirement to show error message after each row, and this error message needs to take the whole row.

If we are using regular html table, we can use colspan to do that, but is there anyway to do that inside fixed data table also?

Thanks and hope to hear your advice on this.

Frank

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by wcjordan** [comment]
Take a look at the [Expanded Rows example source](https://github.com/schrodinger/fixed-data-table-2/blob/master/examples/ExpandedExample.js).  We recently added subRowHeight, subRowHeightGetter, & rowExpanded props to allow embedding a component to span the table beneath rows.

I'm going to close as this should address your use case, but feel free to comment if you need more assistance.

**Comment by xhe** [comment]
Thanks, that sample is good enough already.

**Comment by xhe** [comment]
Chris and Jeremy,
May I ask if there are any plan to accept this into main branch?

https://github.com/schrodinger/fixed-data-table-2/issues/121

That feature is highly expected and we also need to have the new expanded
row feature.

Thanks

Frank

**Comment by wcjordan** [comment]
Answered there, but for here as well.  We'd accept a PR for it, but unlikely to prioritize working on it.  I've added help wanted and backlog labels to it to help represent this.
