### ISSUE TITLE
RTL data-table

### ISSUE THREAD

**Issue by eafshary** [schrodinger/fixed-data-table-2#209]
How can I show data-table in rtl layout.
now column show from left to right
how can I change direction of columns and scrollbar?

**Comment by wcjordan** [comment]
I haven't used the table in RTL mode but there is some code which changes things if Locale.isRTL returns true.  You may want to explore playing with that.

https://github.com/schrodinger/fixed-data-table-2/search?utf8=%E2%9C%93&q=rtl&type=

**Comment by wcjordan** [comment]
If you do find a good way to do it or what the current state of it is, let me know.

**Comment by eafshary** [comment]
I want to change locale to RTL, must be compile your package?

**Comment by eafshary** [comment]
thanks, now table show from right to left but scrollbar shows on left and not working properly!
can change direction of scrollbar?

**Comment by wcjordan** [comment]
That's as much as I know here.  You'll likely need to dig into the code to fix up the issues.

**Comment by kamaldlk** [comment]
How to use RTL in Fixed Data Table 2 pease Help me on this

**Comment by kamaldlk** [comment]
@eafshary  How to implement RTL In Table can you give me some example

**Comment by pradeepnschrodinger** [comment]
Closing this as it got fixed through #497.

From v1.0.2 and onwards, the table prop `isRTL` can be used.
