### ISSUE TITLE
how to handle "Failed prop type" error

### ISSUE THREAD

**Issue by xhe** [schrodinger/fixed-data-table-2#211]
## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

Recently, I updated fixed-data-table 2 from 0.7.6 to 0.8.0, but immediately, I saw this error:

react-with-addons.js:22536 Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use `PropTypes.checkPropTypes()` to call them. Read more at http://fb.me/use-check-prop-types
    in FixedDataTableCellDefault (created by ExpandableTextCell)

"fixed-data-table-2": "^0.8.0",
"react": "^15.3.0",
"react-dom": "^15.3.0",

I already followed the error msg online and upgraded the react version, but the error still there.

May I ask what I can do to remove this warning?

Thanks

**Comment by wcjordan** [comment]
I'm not able to reproduce this on the examples using 15.3 (although I am w/ 15.2).  Double check you rebuilt and are using 15.3.  If that doesn't help could you include the full stacktrace of the warning?  In particular the offending lines for FDTCellDefault would be nice although looking at that file now it uses prop-types every where.

**Comment by xhe** [comment]
Thanks Chris,

Although the warning doesn't harm, it is still very annoying. Do you have
any plan to update the code to remove the warning?


This is package.json

"fixed-data-table-2": "^0.8.0",
    "react": "15.3.0",
    "react-addons-test-utils": "15.3.0",
    "react-dom": "15.3.0",

Below is the full warning stacktrace:

react-with-addons.js:22536 Warning: Failed prop type: Calling PropTypes
validators directly is not supported by the `prop-types` package. Use
`PropTypes.checkPropTypes()` to call them. Read more at
http://fb.me/use-check-prop-types
    in FixedDataTableColumn (created by tableDOM)
    in tableDOM
warning @ react-with-addons.js:22536
checkReactTypeSpec @ react-with-addons.js:19053
validatePropTypes @ react-with-addons.js:11100
createElement @ react-with-addons.js:11134
(anonymous) @ JnprDataTableNgcsc.jsx:453
tableDOM_render @ JnprDataTableNgcsc.jsx:452
_renderValidatedComponentWithoutOwnerOrContext @ react-with-addons.js:6808
_renderValidatedComponent @ react-with-addons.js:6834
performInitialMount @ react-with-addons.js:6376
mountComponent @ react-with-addons.js:6264
mountComponent @ react-with-addons.js:14467
performInitialMount @ react-with-addons.js:6390
mountComponent @ react-with-addons.js:6264
mountComponent @ react-with-addons.js:14467
mountComponentIntoNode @ react-with-addons.js:12180
perform @ react-with-addons.js:18733
batchedMountComponentIntoNode @ react-with-addons.js:12201
perform @ react-with-addons.js:18733
batchedUpdates @ react-with-addons.js:10503
batchedUpdates @ react-with-addons.js:16382
_renderNewRootComponent @ react-with-addons.js:12360
_renderSubtreeIntoContainer @ react-with-addons.js:12446
render @ react-with-addons.js:12467
(anonymous) @ index.html:780

**Comment by wcjordan** [comment]
As best I can tell, this isn't coming from FDT.  Are you able to reproduce it on the examples page or can you create an example project on GitHub that reproduces it?

**Comment by xhe** [comment]
Thanks Chris.
You are right, it is my fault. I am rendering react component in our
project using react-dom.js and react-with-addon.js, those two js file is
still old one. Once I upgraded these to 15.3, all the warning is gone.
Thanks for your help.

**Comment by wcjordan** [comment]
No problem, glad you were able to track it down.
