### ISSUE TITLE
Example: "Expanded rows" does update the CollapseCell icon on click

### ISSUE THREAD

**Issue by jonnysparkplugs** [schrodinger/fixed-data-table-2#215]
## Expected Behavior

Clicking on the ► should change the arrow to ▼

## Current Behavior

The ► only changes to ▼ if the cell is recycled. E.G. scrolled on and off screen

## Possible Solution

Fix available here: https://github.com/schrodinger/fixed-data-table-2/pull/214

## Your Environment

* Version used: Lastest
* Browser Name and version: Chrome 60
* Operating System and version (desktop or mobile): Windows 10
* Link to your project:

**Comment by wcjordan** [comment]
This is fixed now as far as I can tell
