### ISSUE TITLE
Typescript typing?

### ISSUE THREAD

**Issue by jonnysparkplugs** [schrodinger/fixed-data-table-2#216]
## Expected Behavior

I'm using the grid in typescript (working great thanks 👍). However due to my own TSConfig i get warnings as there is no typeing. Sadly no one has built the typings (Booo 👎)
 
## Current Behavior

No typing as its a ES6 lib.

## Possible Solution

Add typing to lib directly or via the types repo.

## Steps to Reproduce (for bugs)

import anything from 'fixed-data-table-2
![image](https://user-images.githubusercontent.com/840353/29662453-5037ddb4-88bf-11e7-9997-45739506ae1d.png)

## Context

Using fixed-data-table-2 in a type safe manor 

## Your Environment

* Version used: Latest
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Windows 10 linux subsystem
* Link to your project: N/A

**Happy to do the typing, just wanted to make sure someone hasn't started it? I can either add the types directly to this project via a fork/PR or just add them as a different npm via definitelytyped.org**

any preference?

**Comment by enriquin** [comment]
Hello!
Any advance on this? Any help needed?

Thanks

**Comment by stevegreatrex** [comment]
It's absolutely not ideal but I've found that I can work around this by using the type definitions for the original `fixed-data-table` project:

1. `npm install --save-dev @types/fixed-data-table`
2. In `fixed-data-table-2.d.ts` somewhere in my project
```typescript
declare module "fixed-data-table-2" {
   export {
      Table,
      TableProps,
      //...anything else you need...
   } from "fixed-data-table";
}
```
3. In any file that needs to reference those types
```typescript
/// <reference path="./fixed-data-table-2.d.ts" />
import { Table, TableProps } from "fixed-data-table-2";
//...
```

I'm almost certain that this approach will cause me some problems later but it might serve as a stop-gap.

**Comment by KamranAsif** [comment]
@stevegreatrex I think you could create a PR that adds the typings from fixed-data-table to this repo. It shouldn't interfere with any other work being done since it'll just add a new file.

**Comment by KamranAsif** [comment]
@wcjordan might need to see about legal issues though

**Comment by stevegreatrex** [comment]
I think we'd actually need to submit the PR to https://github.com/DefinitelyTyped/DefinitelyTyped.  I should be able to do this later today.

I'm not particularly familiar with this component (I've inherited a project that uses it); how comfortable are you with publishing types that may not necessarily be up-to-date?

**Comment by KamranAsif** [comment]
AFAIK you can either add types to @types or directly to a repo. I suppose your PR works :)

**Comment by Flui** [comment]
But why are you choosing typescript over flow? Since I feel like flow is more popular in React environment.

**Comment by pradeepnschrodinger** [comment]
Closing this since type definitions exist via https://www.npmjs.com/package/@types/fixed-data-table-2.
