### ISSUE TITLE
Provide linting via ESlint

### ISSUE THREAD

**Issue by Dangoo** [schrodinger/fixed-data-table-2#218]
This repo expects a certain coding style defined [here](https://github.com/schrodinger/fixed-data-table-2/blob/master/CONTRIBUTING.md), but there is no linting.

## Expected Behavior
Linting should be enabled.

## Current Behavior
💥

## Possible Solution
Add eslint config.

## Context
Checking the code style programmatically leads to a cleaner code base and less review overhead for code style.

## Your Environment

* Version used: `v2.0-merge_master `

**Comment by Flui** [comment]
an much easier solution would be to use prettier and a precommit hook (https://prettier.io/docs/en/precommit.html). So only styled code would be commited.

**Comment by wcjordan** [comment]
Closing this in favor of #520
