### ISSUE TITLE
scroll on IE11

### ISSUE THREAD

**Issue by FredericHeem** [schrodinger/fixed-data-table-2#22]
The new 0.6.6 versions solves the issue of resizing columns on IE11, however, there is still an old bug regarding srcolling in IE11: https://github.com/facebook/fixed-data-table/issues/15
Thanks a lot for maintaining this project.

**Comment by KamranAsif** [comment]
@FredericHeem Can you please elaborate on the exact repo steps? We have been using IE11 for a while and haven't run into any problems so far.

**Comment by FredericHeem** [comment]
Please have a look at the example: http://schrodinger.github.io/fixed-data-table-2/example-resize.html
It's not scrollable on IE but works fine on Chrome.

**Comment by KamranAsif** [comment]
Scroll should be working fine. I think the site doesn't work because of TouchExampleWrapper
Try out this: https://jsfiddle.net/gww7j03L/

@wcjordan We should remove the TouchWrapper since we now support native touch. Any objections?

**Comment by wcjordan** [comment]
Ah that's really misleading, that the examples all include TouchExampleWrapper and it doesn't work with IE11.  Let's definitely delete TouchExampleWrapper.

@FredericHeem thanks for pointing that out.  We'll update the examples to be correct.

**Comment by FredericHeem** [comment]
I can confirm that the jsfiddle works fine on IE, however, I still have to find out why it doesn't scroll in my case, which doesn't use TouchWrapper at all.

**Comment by KamranAsif** [comment]
@FredericHeem You can fork my jsfiddle and try replicate it on there. If you can do that, feel free to file a new issue and we can address it.

**Comment by FredericHeem** [comment]
I'm using `Dimensions` from `react-dimensions`, is there an easy to add this dependency to jsfiddle ?

**Comment by FredericHeem** [comment]
The issue is related to webpack, as a workaround, changing the `devtool` option from `eval` to `source-map` makes the scrolling work on IE.

**Comment by wcjordan** [comment]
Ah it's good you have a workaround.  That will kill your webpack performance though, right?
I'll take a look sometime today or tomorrow and see if I can reproduce and identify the underlying cause.

**Comment by wcjordan** [comment]
Hmm scroll works for me in IE11 in our application when running webpack dev server with devtool eval.
I'll try things out in one of my side projects when I get a chance, but may need an example for reproduction to make any more progress.

**Comment by dspoonia7** [comment]
I am also facing scrolling issue in production env. In development environment, It works fine.

I don't think this issue is related to webpack. Because I have faced this issue with browserify also. Then i moved to webpack but the issue remains the same.

In Chrome, Error: `Uncaught TypeError: Illegal invocation`
In firefox, Error: `TypeError: 'requestAnimationFrame' called on an object that does not implement interface Window.`

File: fixed-data-table-2/internal/ReactWheelHandler.js
Line#99 `this._animationFrameID = (0, _requestAnimationFramePolyfill2.default)(this._didWheel);`

**Comment by wcjordan** [comment]
@dspoonia7 could you put together a plunker/jsfiddle/codepen which reproduces the issue you're seeing?

**Comment by herman-rogers** [comment]
Ok so I've also got this issue and I can confirm the difference is between production and development environments for webpack building. For production I have removed the 'devtool: "eval"' option and in the dev environment I have it set as default. If I add the eval option to production the build returns fine, if I remove it I get the 'Illegal Invocation' error. Don't really want to have the eval map available in the inspector but for now I'll have to live with it.

**Comment by dasnixon** [comment]
I'm also having this issue, seems to be on the `p.default(this._didWheel)` under `onWheel`

```javascript
return a(e, [{
    key: "onWheel",
    value: function(e) {
        var t = l.default(e)
          , n = this._deltaX + t.pixelX
          , r = this._deltaY + t.pixelY
          , o = this._handleScrollX(n, r)
          , a = this._handleScrollY(r, n);
        if (o || a) {
            this._deltaX += o ? t.pixelX : 0,
            this._deltaY += a ? t.pixelY : 0,
            e.preventDefault();
            var i;
            (0 !== this._deltaX || 0 !== this._deltaY) && (this._stopPropagation() && e.stopPropagation(),
            i = !0),
            i === !0 && null === this._animationFrameID && (this._animationFrameID = p.default(this._didWheel))
        }
    }
}
```

**Comment by dasnixon** [comment]
@wcjordan @KamranAsif any thoughts?
<img width="1011" alt="screen shot 2017-03-23 at 12 30 58 pm" src="https://cloud.githubusercontent.com/assets/672057/24266613/a1bed1b6-0fc4-11e7-8505-93bfb41a4553.png">

**Comment by dasnixon** [comment]
Nevermind, it was my fault, sorry to bug you all. My assets are compiled by Rails/sprockets, I needed to update sprockets and uglifier.

**Comment by KamranAsif** [comment]
Glad you were able to get it resolved!

**Comment by andrepcg** [comment]
@dasnixon I'm having this exact same issue and I'm using create-react-app to build the final JS file

**Comment by wcjordan** [comment]
This is similar to #131 
You may want to look at updating any uglifier dependencies you have.
