### ISSUE TITLE
Rows not always rendered in order.

### ISSUE THREAD

**Issue by andylhansen** [schrodinger/fixed-data-table-2#221]
Is it expected behavior for table rows to not always be rendered in order? They visually appear in order, but in the DOM, they are not in order.
I took a screenshot to illustrate the problem:
![image](https://user-images.githubusercontent.com/9617934/29888100-e43e2bdc-8d7c-11e7-8f31-e6ca9ca1979b.png)

In the image, the rows with indices 22, 21, and 23 are the first children of FixedDataTableBufferedRows. I would expect that the rows would be rendered in order of index.

This is giving me problems because I am trying to style a border-top on each row, but if they are out of order, then the background from one row covers up the border of another.

Is there any way to fix this?

**Comment by wcjordan** [comment]
This is done as a performance enhancement so we can recycle rows and reduce the number of react mounts and unmounts.  We don't support any alternative nor do I think we will.
