### ISSUE TITLE
The scrollbar in mobile is scrolling the parent container as well

### ISSUE THREAD

**Issue by emirdeliz** [schrodinger/fixed-data-table-2#225]
## Expected Behavior
The scroll of the parents should not move when change scroll of table

## Current Behavior
When i have scrollbar in parent container the scroll moving in both.

![print](https://user-images.githubusercontent.com/6270495/30277057-0e8403ee-96dd-11e7-8c82-c7f59664a43a.png)

## Steps to Reproduce (for bugs)

[https://jsfiddle.net/uzg4dosc/](https://jsfiddle.net/uzg4dosc/)

## Your Environment

* Version used: 0.8.0
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): mobile

**Comment by wcjordan** [comment]
This is the unfortunate result of [Chrome making touch events passive by default](https://developers.google.com/web/updates/2017/01/scrolling-intervention).  I won't be able to fix within FDT2 until React fixes [#8968](https://github.com/facebook/react/issues/8968).

In the meantime, you can fix it in your app by adding this css:
```
.fixedDataTableLayout_rowsContainer {
    touch-action: none;
}
```

Some discussion related to this can be found at the bottom of this thread:
https://github.com/schrodinger/fixed-data-table-2/issues/154

**Comment by emirdeliz** [comment]
@wcjordan this works! Thanks

**Comment by emirdeliz** [comment]
this works! Thanks
