### ISSUE TITLE
React warning after upgrade to 0.8 (getDefaultProps)

### ISSUE THREAD

**Issue by onemenny** [schrodinger/fixed-data-table-2#227]
After upgrading FDT2 to v0.8 in order to get rid of the "Warning: FixedDataTable: isMounted is deprecated."

Now I get 
"Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead."

verified with react 15.4, 15.5 or 15.6

**Comment by wcjordan** [comment]
Hmm I haven't seen this before and can't reproduce on the examples.  Could you put together a JsFiddle or sample repo which reproduces there warning?

**Comment by onemenny** [comment]
Sorry, I cannot at this point put together a fiddle or a repo. 
I did debug the code and the failure occures on FixedDataTableCellGroup on line 146

`_React2.default.createElement(_FixedDataTableCell2.default, {`

which goes to ReactElementValidator and then goes to validatePropTypes which in turn trows the error
The react version is 15.6.1

**Comment by wcjordan** [comment]
My best bet is this is caused by [react #9999|https://github.com/facebook/react/issues/9999].  I recommend investigating if you're mixing a dev & prod build FDT & your repo.

I'm going to close for now, but feel free to re-open if you come up with more details on the source of the problem.
