### ISSUE TITLE
React 16

### ISSUE THREAD

**Issue by skosch** [schrodinger/fixed-data-table-2#228]
I just tested FDT2 with React 16, simply by making that change in package.json (while leaving things like `prop-types` at v15) and the examples seem to work perfectly fine.

Would you be willing to make that change official? Right now this wonderful library ends up pulling its own React 15 into my updated React 16 project, and that leads to all kinds of avoidable conflicts. What do you think?

**Comment by wcjordan** [comment]
That's peculiar, React is a peer dependency of FDT2 so I would not expect it to pull it in.  It could be related to the create-react-class / prop-types dependency or maybe something related to devDependencies.  If you have any suggestions, I'm happy to explore or accept a PR, until then we may have to wait until more examples of libs handling this exist.

**Comment by skosch** [comment]
Well, looks like you're right, I wasn't paying attention! The copy pulled in by FDT2 was indeed v16 as well. I've cleaned up my node_modules manually now and everything seems to work. Sorry about the noise!

**Comment by wcjordan** [comment]
Great, glad you were able to track it down!
