### ISSUE TITLE
Update license to MIT in order to align with React.

### ISSUE THREAD

**Issue by thejohnbackes** [schrodinger/fixed-data-table-2#229]
I created a ticket on Fixed Data Table to update the license to MIT in order to align with React. I assume FDT2 inherits its license from FDT.

We use FDT2, which will be our only BSD + PATENTS dependency if we can't get this resolved....

Please see: https://github.com/facebook/fixed-data-table/issues/506

**Comment by wcjordan** [comment]
Here there, we did inherit / keep  the license from FDT.  I can raise the question of relicensing to our legal team, but may take a while to work it out.

Is there any driving motivation for the suggestion?

**Comment by KamranAsif** [comment]
When I got the original license from Schordinger's legal team; they simply took the existing license and copy/paste it with Schrodinger's name instead of Facebook.

Since we used the original code from facebook/fixed-data-table, I imagine we need them to switch to MIT license first

**Comment by thejohnbackes** [comment]
we are under a lot of pressure at LinkedIn to drop any BSD + Patents
licenses, particularly if we want to open source a project. We have
multiple projects we are going to have to switch to React Virtualized (with
much pain) if we stay with BSD + Patents on Fixed Data Table.

**Comment by wcjordan** [comment]
I've spoken with our legal team, and since Facebook still holds the copyright here, we won't be able to relicense until they've relicensed the original library.  I've pinged some Facebook engineers on the issue you opened there.

**Comment by thejohnbackes** [comment]
Thanks Chris!

**Comment by wcjordan** [comment]
Facebook isn't planning to relicense the original FDT so we're stuck as is for now.
