### ISSUE TITLE
minWidth ignored on flex columns

### ISSUE THREAD

**Issue by dcoales** [schrodinger/fixed-data-table-2#23]
Hi,

I've tried using the original table and found that flex columns can shrink to nothing and seem to ignore the minWidth setting.  Is this also true in your version (or am I just doing something wrong).

Thanks,
David

**Comment by wcjordan** [comment]
Hey @dcoales can you try switching minWidth to width and see if that fixes things.
This [example](http://schrodinger.github.io/fixed-data-table-2/example-flexgrow.html) seems to do things that way.  Definitely not intuitive that it works that way...

**Comment by dcoales** [comment]
This was the answer. Many thanks.

Cheers
David

**Comment by wcjordan** [comment]
Glad to hear!  I'll update the documentation to make the differences / usage of minWidth and width more clear.

**Comment by ryanhca** [comment]
I haven't been able to get the "FlexGrow" property to work. I have literally copied and pasted the code from the example and am using my own data to populate the table, but my table doesn't resize at all. Has anyone else had a tough time with this?

**Comment by wcjordan** [comment]
I haven't heard of anything, but can look if you can put up a jsfiddle that repros the issue.  

One common point of confusion is expecting the grid to grow to fill it's container which is not supported.  That can be added with an HOC like react-dimensions though.  Some discussion is here: https://github.com/facebook/fixed-data-table/issues/62#issuecomment-238151809

**Comment by ryanhca** [comment]
I found a good work around for this problem! Well.. good is subjective.

But it is something like this... take it or leave it.

`componentWillMount() {
        this._updateDimensions();
    }
    componentDidMount() {
        window.addEventListener("resize", this._updateDimensions);
    }
    componentWillUnmount() {
        window.removeEventListener("resize", this._updateDimensions);
    }
    _updateDimensions(){
        this.setState({tableWidth: ($(window).width()+100), tableHeight: ($(window).height()-150)});
    }`

Set the height and width props of your table to this.state.tableHeight and this.state.tableWidth. Adjust the dimensions as necessary for your layout. It takes a second to resize so it's DEFINITELY NOT optimal. But it gets the job done for our Beta app we're building. 

Cheers!

**Comment by KamranAsif** [comment]
Closing this since theres no actionable follow up
