### ISSUE TITLE
Callback for mouseup event on rows

### ISSUE THREAD

**Issue by SirGandal** [schrodinger/fixed-data-table-2#230]
## Expected Behavior
Implement _onRowMouseUp_: a callback function for when the mouse button is released on a row. This is similar to the existing _onRowMouseDown_.

## Current Behavior
No callback can be defined for mouseup events on rows.

## Possible Solution
Add _onMouseUp_ in the returned div of _FixedDataTableRowImpl_ and bind props similarly to _onMouseDown_. If this is in scope a PR is ready to be issued from [here](https://github.com/SirGandal/fixed-data-table-2_RTR/tree/onRowMouseUp).

## Context
We are trying to detect long clicks on rows. We start a timer _onRowMouseDown_ and we would like to check the elapsed time _onRowMouseUp_ to see if that click qualifies as "long click". 

## Your Environment
* Version used: 0.8.1

**Comment by wcjordan** [comment]
This seems reasonable to me, go ahead an put in the PR and I'll give a quick test.  

Also handling row clicks is an area we don't have good examples.  If you're up for copying ObjectDataExample.js and adding one, it'd be appreciated.

**Comment by SirGandal** [comment]
Sounds good, thanks! I have created PR #234 with the changes and an example as well.

**Comment by SirGandal** [comment]
Can this be closed now?

**Comment by wcjordan** [comment]
Yep, thanks
