### ISSUE TITLE
Scroll bars are jumpy and jittery in Edge/Windows.

### ISSUE THREAD

**Issue by DaveCole** [schrodinger/fixed-data-table-2#233]
## Expected Behavior
Scrolling vertically or horizontally should be smooth and the scroll bars should reflect the correct position as you scroll.

## Current Behavior
Scrolling in Edge on Windows results in very jumpy scroll bar positions as you scroll.  This can hurt rendering performance somewhat too depending on the implementation.

## Steps to Reproduce (for bugs)
Load any of the examples in Edge on Windows.

## Your Environment

* Version used: 0.8.1
* Browser Name and version: Edge (latest)
* Operating System and version (desktop or mobile): Windows 10

**Comment by wcjordan** [comment]
Hey Dave, I haven't tried things out in Edge, but haven't seen these issues in IE11.  

My first thought is this may be performance related, particularly if your cell renderers aren't pure components.  Could you profile and see if React is taking more than 16 ms with each render pass on a scroll?  #146 and #190 also have some discussion of performance debugging.

**Comment by SirGandal** [comment]
I have noticed this issue as well in IE11.
Once I use the mouse and drag the scrollbar (either vertical or horizontal) the scrollbar disappears.

![IE11](https://i.imgur.com/cCGbvFy.gif)

Here's a jsfiddle you should be able to load in IE11 to reproduce: https://jsfiddle.net/sirgandal/uwxthquy/2/.

The behavior is also weird in the latest firefox where the scrollbar moves only when you stop dragging and not as you are dragging.

![Firefox](https://i.imgur.com/kyocrvg.gif)

As a reference this is how it looks in the latest Chrome:
![Chrome](https://i.imgur.com/xGCUVZN.gif)

**Comment by DaveCole** [comment]
Here's a screengrab of scrolling in Edge - the examples seem to scroll a little smoother than my real-world application so I'll look into performance as you requested and get back:

![edgescroll](https://user-images.githubusercontent.com/959631/31140153-73c86ebe-a828-11e7-9884-403b8dad5b55.gif)

**Comment by DaveCole** [comment]
Thanks for the info on optimization - the table is very performant once I do a production build, but I still see the jittery scroll nub behavior in Edge.  It scrolls fine but I'm beginning to understand why you hid them in IE while moving them :)

**Comment by lsentkiewicz** [comment]
Any update here?
Scrollbar doesn't work well in Edge http://take.ms/DcyZ1
I am using the old version, and I don't see such issues.

**Comment by wcjordan** [comment]
No updates, but happy to accept a PR.  I don't know any heavy Edge users, so I doubt it's gotten much attention.

**Comment by wcjordan** [comment]
We now have a new customizable scrollbar API w/ v1.1 which allows customizable scrollbars and should support native scroll.  We're still working on examples to help document it, but hopefully that API addresses these issues.
