### ISSUE TITLE
 React depends on requestAnimationFrame. Make sure that you load a polyfill in older browsers.

### ISSUE THREAD

**Issue by CharlesStover** [schrodinger/fixed-data-table-2#235]
There is no problem in my modern Chrome, but whenever I run unit tests, any component that uses fixed-data-table-2 will throw this warning:
Warning: React depends on requestAnimationFrame. Make sure that you load a polyfill in older browsers. http://fb.me/react-polyfills

I know I can just polyfill in Jest's setup files, BUT: Components that don't use fixed data table 2 do not give this warning.

## Expected Behavior
This warning should not appear.

## Current Behavior
This warning appears on unit tests of components that contain fixed data table 2 as a child.

## Possible Solution
Include the polyfill? Or see how other components are created that do not need the polyfill. None of the components that we have made manually or imported from other libraries are giving this error, nor have we had to manually include the polyfill in any components.

## Steps to Reproduce (for bugs)
```
npm path/to/test.js --env=jsdom

process.env.BABEL_ENV = 'test';
process.env.NODE_ENV = 'test';
process.env.PUBLIC_URL = '';
const jest = require('jest');
jest.run(process.argv.slice(2));
```

## Context
Trying to run unit tests without bloated warning messages.

## Your Environment
Jest
internal project

**Comment by wcjordan** [comment]
Since FDT2 doesn't support IE < 11, I'm going to close this as will not fix and leave it for users to polyfill before they load the library.  This will help avoid library bloat for users depending on IE11 & evergreen browsers as well as avoid an impression we support legacy browsers (which are untested).

**Comment by CharlesStover** [comment]
My suggestion isn't so much to support legacy browsers, but to support unit testing, e.g. Jest.

No other React component in my entire application requires this polyfill; not that I completely understand why yours is the only exception.

**Comment by wcjordan** [comment]
Could you add a raf polyfill to your jest/setupFiles?

**Comment by CharlesStover** [comment]
Yes, that is what I've done. The idea is more along the line of addressing what exactly is different about _your_ component that isn't different about every other component in existence. If no other library or React component requires this polyfill in Jest tests, why does yours? There may be a dependency on a deprecation that could use looking into.

I don't believe React includes this polyfill by default in its components, and because of this, I don't think the fix would require you to include this polyfill, since none of my other components are using said polyfill, and none of them are giving the error that requestAnimationFrame does not exist.

Because of this, I think developers who use Jest should not be greeted with errors just because they `npm install fixed-data-table-2`. It's not expected behavior and doesn't seem to be necessary to import third party components in other cases.

**Comment by wcjordan** [comment]
Ya that does seem reasonable.  If you want to add a page to the documentation of setting up jest tests for FDT2 that seems like it would be a good fit.
