### ISSUE TITLE
Callback for touchstart, touchend and touchmove events on rows

### ISSUE THREAD

**Issue by SirGandal** [schrodinger/fixed-data-table-2#236]
Same as #230 but for touch devices.

## Expected Behavior
Implement _onRowTouchStart_, _onRowTouchEnd_ and _onRowTouchMove_: callback functions for when the touch-start, touch-end and touch-move events are detected on rows. This is similar to the existing _onRowMouse..._ callback functions.

## Current Behavior
No callbacks can be defined for touch start/end/move events on rows.

## Possible Solution
See possible solution of #230.

## Context
We are trying to detect long press on rows on touch devices. We would like to start a timer _onRowTouchStart_ and check the elapsed time _onRowTouchEnd_ or _onRowTouchMove_ to see if a press qualifies as "long press".

## Your Environment
* Version used: 0.8.1

**Comment by wcjordan** [comment]
This seems reasonable to me, and would accept a PR.

One thing I've wanted to change for a bit is to not bind touch listeners unless touchScrollEnabled is true.  If you could look into that while addressing this, it'd be appreciated.  Thanks!

**Comment by wcjordan** [comment]
Fixed w/ #238

**Comment by wcjordan** [comment]
This is now published w/ v0.8.2
