### ISSUE TITLE
Table is "stealing" scrolling from Modal (in React 16 only)

### ISSUE THREAD

**Issue by jacoporicare** [schrodinger/fixed-data-table-2#242]
## Expected Behavior
If I use [react-modal](https://github.com/reactjs/react-modal) library I want to scroll behaves normally. 

## Current Behavior
If you render a modal with `react-modal` and React 16 (v15 works fine) in a table cell, the table "steals" scrolling event and scrolls the table first (behind the modal) and after you reach the end it starts scrolling the content in modal. If I render a modal inside a normal scrollable div (outside of fixed-data-table-2) it works just fine - that's why I think the bug is in this library.

## Steps to Reproduce (for bugs)
Due to NDA I cannot post a video but just render a table (with some scrolling) and open (render) a modal (with a scrollable content) inside a table cell.

An example of modal with scrollable area:
![image](https://user-images.githubusercontent.com/18525854/31496772-010e4b00-af5d-11e7-96ce-4ae3d036ff9b.png)

## Your Environment

* Version used: 0.8.1 (0.7.x and 1.0.0-beta.4 behave the same)
* Browser Name and version: Chrome 61
* Operating System and version (desktop or mobile): macOS 10.12.6

**Comment by wcjordan** [comment]
This is peculiar, and sounds like FDT may be getting the scroll event before the modal.  Could you debug and see if the modal or field within the modal gets the scroll event before the grid?

One thing you can try is having your modals scrollable component [stopPropagation](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation) of the scroll as this could be a case where the modal does nothing on scroll (relying on the default), FDT then receives the scroll and handles it and prevents default, then no scroll takes place in the modal.

**Comment by jacoporicare** [comment]
Thank you for quick reply 👍, I'll try that and let you know. I'm just wondering if scroll event would be enough as I've seen you're using `onWheel`, `onTouchStart` etc. Anyway I'll try to debug it. Cheers!

**Comment by jacoporicare** [comment]
Hello, so I've tried it and if I add `onWheel` event handler and call `stopPropagation` it solves the problem. It's fine as a workaround but I'm still wondering why it's happening only with React 16. I presume it has something to do with new portals. Somehow the modal is influenced by the `onWheel` event of the table even though the modal itself is rendered in `body` on the top level. Anyway thank you, I'll try to apply to all modals and it should do the trick.

**Comment by jacoporicare** [comment]
If someone would have the same problem, here's a little wrapper for `react-modal` that solves the issue:

```js
import React, { Component } from 'react';
import Modal from 'react-modal';
import { on, off } from 'dom-helpers/events';

class MyModal extends Component {
  componentWillUnmount() {
    off(this.modal.node, 'wheel', this.stopWheel);
  }

  stopWheel = event => {
    event.stopPropagation();
  };

  handleAfterOpen = (...args) => {
    if (this.props.onAfterOpen) {
      this.props.onAfterOpen(...args);
    }

    on(this.modal.node, 'wheel', this.stopWheel);
  };

  handleRequestClose = (...args) => {
    if (this.props.onRequestClose) {
      this.props.onRequestClose(...args);
    }

    off(this.modal.node, 'wheel', this.stopWheel);
  };

  render() {
    const { children, ...props } = this.props;

    return (
      <Modal
        ref={modal => (this.modal = modal)}
        {...props}
        onAfterOpen={this.handleAfterOpen}
        onRequestClose={this.handleRequestClose}
      >
        {children}
      </Modal>
    );
  }
}

export default MyModal;
```

**Comment by wcjordan** [comment]
I think you're right, that the React 16 portals have made it so the modal events now bubble through the table cell which launches it.

In general, I think this is a bad side-effect of the fact that FDT2 manages scrolling itself instead of using the browser's built in mechanism.

Thanks for the example code for the fix!
