### ISSUE TITLE
Scrollbar feel/behavior is off & frustrating on Linux

### ISSUE THREAD

**Issue by alexhultman** [schrodinger/fixed-data-table-2#243]
The thing you drag with your mouse inside the scrollbar, let's call it "scroll handle" for now. The feel and behavior of this handle is way off compared to the native feel of most OS:es

* When you drag the handle and your mouse cursor happens to go outside of the browser window (well, outside of the body canvas) the drag stops. This is *very* frustrating when scrolling through a table that is close to the edge of the browser window. This is not the feel and behavior of *anything* else I have seen. It should keep on scrolling even though the mouse cursor happens to go outside of the browser window - this is the feel and behavior of every single scroll handle I have ever used. Mind you, this only seems to be the case on Linux. I know that this is not the case on OS X.

* When you drag the handle up and it goes as far as it can (the handle is now at "offset 0"). If you then *keep* dragging up while still holding the mouse button down (you are still "scrolling" even though the handle is capped at its uppermost position). If you then drag down the handle goes down even though your mouse cursor hasn't yet returned to the position where the handle was capped. In other words, the scroll handle is no longer synced with the mouse cursor's Y position. Instead the scroll handle is moving as far away from the mouse cursor, as you moved the mouse upwards when the handle was capped.

## Your Environment
* Version used: the one you host on your example / demo page
* Browser Name and version: Version 60.0.3112.101 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Linux with Gnome a desktop
* Link to your project: this bug is reproducible in your own version, deployed on your own example page

**Comment by wcjordan** [comment]
Thanks for the issue report.  I'd accept a PR for these.

I believe the 1st issue is related to [this chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=750455).  So you may want to just watch that case.
You could poke around in [DOMMouseMoveTracker.js](https://github.com/schrodinger/fixed-data-table-2/blob/master/src/vendor_upstream/dom/DOMMouseMoveTracker.js) & [Scrollbar.js](https://github.com/schrodinger/fixed-data-table-2/blob/master/src/Scrollbar.js) though.
It may also be worth switching DOMMouseMoveTracker to use it from [fbjs](https://github.com/facebook/fbjs/blob/master/packages/fbjs/src/dom/DOMMouseMoveTracker.js)

The 2nd issue would involve changes in how scroll is tracked in [Scrollbar.js](https://github.com/schrodinger/fixed-data-table-2/blob/master/src/Scrollbar.js).  Right now we just track it as a delta, but you may want to add something which tracks a scroll deficit, but doesn't propagate it out to the onScroll method.

**Comment by alexhultman** [comment]
It (the first issue) cannot *only* be a Chrome bug because I see the exact same issue with fixed-data-table-2 in Firefox (and Firefox does *not* have that Chrome bug).

The bug report at Chrome is about not getting mouse move updates outside the browser window but the issue with fixed-data-table-2 is that once you go outside with the mouse, your drag *aborts completely* and cannot be resumed by dragging the cursor back in the browser canvas. Even though the browser does not emit any mouseup event, the drag is dead.

So yes, Chrome has some similar issues but this thing is primarily caused by JS scripting in the lib.

**Comment by wcjordan** [comment]
That's good to know.  I'd poke at those files I mentioned as they contain the related scrollbar & mouse drag tracking logic.

**Comment by alexhultman** [comment]
The fbjs DOMMouseMoveTracker does not listen to mouseleave and mouseout while the one in this lib does. Those events also calls onMouseEnd which sounds like the problem here.

**Comment by wcjordan** [comment]
Now that we support customizable scrollbars & native scroll there should be ways to work around this by implementing  scroll independently.
