### ISSUE TITLE
Can't interact with columns on left when table has columns fixed to the right.

### ISSUE THREAD

**Issue by garytang8** [schrodinger/fixed-data-table-2#252]
## Expected Behavior

Non-fixed columns on the left should always behave as expected, meaning their content can be selected and the table can be sorted by those columns. 

## Current Behavior

If a table has columns fixed to the right (via the `fixedRight` property on the Column), then an invisible column group for the fixed columns will block the user from clicking on the columns on the left. For example, if the table is set up for sorting, the user won't be able to sort by that column.

## Possible Solution

I have a fix, which is to use the `offsetLeft` property on the `FixedDataTableCellGroup` rather than the `left` property.

## Steps to Reproduce (for bugs)

This will affect tables that have columns fixed to the right.

## Your Environment

* Version used: 0.8.4
* Browser Name and version: Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): macOS Sierra (v10.12.6)

**Comment by airwin** [comment]
+1. It seems `fixedRight` conflict with the `allowCellsRecycling`.

**Comment by garytang8** [comment]
Thanks for pointing that out @airwin. My fix in that PR should address the conflict with `allowCellsRecycling=true`

**Comment by wcjordan** [comment]
Merged and released w/ 0.8.5
