### ISSUE TITLE
Dynamic column rendering

### ISSUE THREAD

**Issue by abologna-r7** [schrodinger/fixed-data-table-2#255]
First of all, thanks for the support to all contributors of this library. Now I believe this is not possible (yet), but doesn't hurt if I ask anyway, and maybe there's already someone who needs this or has already done it so here it goes:

## Context
I'm using the table component and creating columns based on, and this is the key here, "known"  data rows, so basically I'm able to do the following:

```js
<Table
   rowsCount={data.length}
   {...props}
>
   <Column
      header={...}
      cell={...}
      width={100}
   />
...
</Table>
```

Now the above works wonderful, but, for a second table that I need, I have a tiny issue. The data that I'm handling is unknown, meaning that I do not know the number of key:value pairs that the table will receive, so here is what I'm expecting to do (not possible at the moment):

```js
<Table
   rowsCount={data.length}
   {...props}
>
   {data[rowIndex].map(row => (
      <Column
         header={...}
         cell={...}
         width={100}
      />
   ))}
</Table>
```

## Your Environment
* Version used: v0.8.6
* Browser Name and version: Chrome Latest
* Operating System: Mac OSX

**Comment by wcjordan** [comment]
From what you describe there are 2 ways you can go.  One is doable, and the other isn't.

If you have data where there are different columns for each row, and want to display all columns across all row, then you can add a componentWillReceiveProps method in you component and have it walk all rows aggregating the columns.  Then when you render put all columns in the Table.

If instead you want different columns for each row, then it no longer sounds like a table.  If that's the case, it'd be interesting to hear more, but may not be much I could point you too.

Let me know if this helps!

**Comment by abologna-r7** [comment]
Thanks for the fast response @wcjordan 👍 
That's actually a pretty good solution (1st option). Yes there maybe data rows with a different number of key:value pairs, but that would be something that I can handle on my end at a later time.

I cuold probably spread the object inside the main object itself:

```js
data.map((item, index) => {
        records.push({
          sent: item.created_at,
          ip: item.ip,
          ...item.sub_records,
        })
      })
```

**Comment by abologna-r7** [comment]
Closing this. Thanks a lot!

**Comment by wcjordan** [comment]
Great, glad that will work.  Good luck, and if you have some spare time and a good implementation, we always welcome new examples!

**Comment by abologna-r7** [comment]
Of course, I'll submit this as an example as soon I finish implementing it :)
