### ISSUE TITLE
why we can't give rows manually in single cell in single column how do give the rows manually in single cell and single column.

### ISSUE THREAD

**Issue by suresh6666** [schrodinger/fixed-data-table-2#256]
## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by wcjordan** [comment]
I'm going to close this since you didn't fill out the issue template and it's not comprehensible.  Please add more details and do what you can to make the issue understandable if you'd like me to consider re-opening.  Thanks
