### ISSUE TITLE
Unwanted space after last column with fixedRight and both horizontal/vertical scrollbars

### ISSUE THREAD

**Issue by ricovitch** [schrodinger/fixed-data-table-2#260]
## Expected Behavior
With a fixed right column and both vertical and horizontal scrollbars, when scrolling to the maximum horizontal position, there should be no space between the end of the last column and the fixed one.

## Current Behavior
With a fixed right column and both vertical and horizontal scrollbars, when scrolling the maximum horizontal position, there is an unwanted space between the end of the last column and the fixed one.

## Possible Solution
We did not find an elegant workaround

## Steps to Reproduce
* https://codesandbox.io/s/z61z0m1yr3
* scroll horizontally to the maximum scroll position

## Context
The case with horizontal and vertical scroll bars is frequent on our side as we have tables with a lot of columns and rows. The unwanted space after the last column is disturbing.

## Your Environment
* Version used: 0.8.6
* Browser Name and version: reproduced on chrome and edge

**Comment by wcjordan** [comment]
@miskreant could you take a look and see if this is related to things you've seen before?  If it's not clear, ping me and I'll look closer.

**Comment by miskreant** [comment]
Yep, looks like my bad @wcjordan, will get a fix in soon.

**Comment by wcjordan** [comment]
Released w/ v0.8.8
