### ISSUE TITLE
rowGetter not working and cell render

### ISSUE THREAD

**Issue by kamaldlk** [schrodinger/fixed-data-table-2#263]
rowGetter not working and cell render.

im trying to do rowGetter and _getColumns not working please help me anyone im new in react

here my sample please check it

https://codesandbox.io/s/kmz5k1zz6v

**Comment by wcjordan** [comment]
The link doesn't seem to use FDT from my look.  Either way the issue tracker is probably not the best place for this, I recommend posting to the discord channel and / or StackOverflow.
