### ISSUE TITLE
row reorder possible ? 

### ISSUE THREAD

**Issue by kamaldlk** [schrodinger/fixed-data-table-2#264]
row reorder possible ?

**Comment by wcjordan** [comment]
Reordering rows is possible, but we don't provide any sort of drag UI.  If you need drag and drop, I recommend adding it into your cell renderers and mutating your data state accordingly.

See the SortExample for an example of reordering rows.
http://schrodinger.github.io/fixed-data-table-2/example-sort.html
https://github.com/schrodinger/fixed-data-table-2/blob/master/examples/SortExample.js

**Comment by kamaldlk** [comment]
thanks @wcjordan
