### ISSUE TITLE
TabIndex added to fixedDataTable_main causes focusing issues

### ISSUE THREAD

**Issue by jackie-benowitz** [schrodinger/fixed-data-table-2#266]
I just upgraded from FixedDataTable -> FixedDataTable2 and post-upgraded found a pesky `tabindex` on the fixedDataTable_main div. 

It looks like it was added within this merge: https://github.com/schrodinger/fixed-data-table-2/pull/207

The tabIndex addition was not added behind the configurable prop (as it should be).

Otherwise you'll get this wonderful focusing on the div on click (and I really didn't want to handle it within my own css):
<img width="362" alt="screen shot 2017-12-04 at 4 16 44 pm" src="https://user-images.githubusercontent.com/6272698/33576664-94b5e568-d90e-11e7-9081-7d7746f75189.png">

If I have time I can make a pull request to fix this! However if anyone else spends 2 hours attempting to figure this out as well, here's 1/2 the work.

**Comment by wcjordan** [comment]
Ah good catch I'm happy to accept a PR on this.  Should just need a quick check here:
https://github.com/schrodinger/fixed-data-table-2/pull/207/files#diff-293ddd101833c33e0069803f5068f2f7L736

Heads up @shysteph as well.

**Comment by wcjordan** [comment]
Fixed by #347 and released w/ 0.8.15
