### ISSUE TITLE
Scroll within table not working on IE.

### ISSUE THREAD

**Issue by nabeel95** [schrodinger/fixed-data-table-2#267]
## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by wcjordan** [comment]
I tried our examples on IE11 and everything works fine for me.  You'll need to fill out our issue template with more details and reproduction steps if you need more assistance.  This may not be related to FDT2 so you may be better off asking on our discord channel or StackOverflow.
