### ISSUE TITLE
Dragging and dropping rows within fixed-data-table-2 possible

### ISSUE THREAD

**Issue by kamaldlk** [schrodinger/fixed-data-table-2#272]
Dragging and dropping rows within fixed-data-table-2 possible . If possible please share here via code pen / codesandbox.

**Comment by wcjordan** [comment]
I don't have any examples off hand, but it should be possible if you have a cell render a drag handle and drop targets.

You could look at how column reorder is implemented [here](https://github.com/schrodinger/fixed-data-table-2/blob/master/src/FixedDataTableColumnReorderHandle.js), although it may be easier to implement using HTML5 drag / drop APIs for your case.
