### ISSUE TITLE
how to get rowHeight dynamically with data size 

### ISSUE THREAD

**Issue by suresh6666** [schrodinger/fixed-data-table-2#273]
i am getting so much of data in single cell but cell is not expanding dynamically with data most of the data hidden.i want expand the cell dynamically with data please give me a suggestion.

**Comment by wcjordan** [comment]
FDT doesn't provide any functionality for measuring cell content to decide the row height.  You may want to look at [ReactVirtualized's CellMeasurer](https://github.com/bvaughn/react-virtualized/blob/master/docs/CellMeasurer.md)
