### ISSUE TITLE
Weird Double Click + Scroll To Row behavior

### ISSUE THREAD

**Issue by binarykitchen** [schrodinger/fixed-data-table-2#275]
## Expected Behavior
1. I double click on a row, i.E. with the middle mice button or two subsequent fast single clicks
2. That row remains selected and the table won't scroll to another position
3. The `onRowDoubleClick` fn gets executed

## Current Behavior
Upon double-click, `scrollToRow` causes the table to scroll back to the previously selected row.

## Possible Solution
Ideas:
- add more parameters to the `scrollToRow` function, i.E. to distinguish whether it's a double-click or not
- ...

Using v0.7.17 here

**Comment by wcjordan** [comment]
I'm not able to reproduce this on the Jump to Row example.  Do you have an reproduction for this?

**Comment by binarykitchen** [comment]
sorry, i fixed this myself with better event handling. listening to single clicks only. this works.

the coffee code is something like this

```
  onRowSingleClick: (target, index) ->
    ...

  onRowDoubleClick: (target, index) ->
    ...

  onRowClick: (target, index) ->
    if not @props.disabled
      @setState(
        rowClickCount: @state.rowClickCount + 1,
        () =>
          if @state.rowClickCount is 1
            @setState(singleClickTimer: setTimeout(() =>
              @onRowSingleClick(target, index)
              @setState(rowClickCount: 0)
            , @props.doubleClickDelay))

          else if @state.rowClickCount is 2
            clearTimeout(@state.singleClickTimer)
            @setState(rowClickCount: 0)
            @onRowDoubleClick(target, index)
      )
```

**Comment by wcjordan** [comment]
Sg, thanks!
