### ISSUE TITLE
 Next/Previous and jump to page sample.

### ISSUE THREAD

**Issue by wyattbiker** [schrodinger/fixed-data-table-2#283]
Hi,

Is there a sample on how to do classic paging instead of infinite scrolling? I prefer users see how many pages are available and click on controls such as `<<   <   1 2 3 4 ....1000  >   >>` to navigate the pages. Also would like drop down to select rows per page.

Thanks!

**Comment by wcjordan** [comment]
This isn't supported with FDT.  You could build a paging component yourself on top of FDT, but you could also investigate [react table|https://react-table.js.org/#/story/readme] which takes this approach rather than supporting virtualization / infinite scroll.
