### ISSUE TITLE
Scrollbar becomes invisible when scrolling on IE11

### ISSUE THREAD

**Issue by Tierica9002** [schrodinger/fixed-data-table-2#285]
When scrolling in IE11 the scrollbar dissapears.

## Expected Behavior
The scrollbar should be visible when scrolling on IE11.

## Current Behavior
The scrollbar disappears when scrolling on IE11.
## Possible Solution
Remove backface-visibility: hidden

## Your Environment
* Browser Name and version: IE 11.1944.14393.0
* Operating System and version (desktop or mobile): Windows 10, desktop
* Link to your project:

**Comment by wcjordan** [comment]
Interesting, I wan't able to reproduce this on Win 7, IE 11.  There is an issue where the scrollbar IE 11 doesn't update position until it's dropped, but this sounds different.

Happy to accept a PR if you want to explore removing backface-visibility.

**Comment by tomaslevin** [comment]
+1
By removing the backface-visibility, the scrollbar becomes jumpy in IE11.

**Comment by CallidusAsinus** [comment]
I'm experiencing this as well in IE11 on windows 10

**Comment by jeffmath** [comment]
I get the same result as @skarjalainen after removing the `backface-visibility: hidden` CSS rule property.  It occurs when dragging the thumb, but not when clicking on the scrollbar outside of the thumb.

**Comment by jeffmath** [comment]
@skarjalainen @wcjordan  To get rid of the jitteriness of the scrollbar thumb, I changed the translateDOMPositionXY function in translateDOMPositionXY.js to this:
```
var translateDOMPositionXY = function () {
  /* the next three lines were moved or changed */
  var ua = global.window ? global.window.navigator.userAgent : 'UNKNOWN';
  var isIE11 = /Trident\//.test(ua);
  if (!isIE11 && _BrowserSupportCore2.default.hasCSSTransforms()) {
    var isSafari = /Safari\//.test(ua) && !/Chrome\//.test(ua);
    // It appears that Safari messes up the composition order
    // of GPU-accelerated layers
    // (see bug https://bugs.webkit.org/show_bug.cgi?id=61824).
    // Use 2D translation instead.
    if (!isSafari && (_BrowserSupportCore2.default.hasCSS3DTransforms() || true)) {
      return function ( /*object*/style, /*number*/x, /*number*/y) {
        style[TRANSFORM] = 'translate3d(' + x + 'px,' + y + 'px,0)';
      };
    } else {
      return function ( /*object*/style, /*number*/x, /*number*/y) {
        style[TRANSFORM] = 'translate(' + x + 'px,' + y + 'px)';
      };
    }
  } else {
    return function ( /*object*/style, /*number*/x, /*number*/y) {
      style.left = x + 'px';
      style.top = y + 'px';
    };
  }
}();
```
which avoids the transform if the browser is IE 11.  The downside, of course, is that the thumb's position does not update until the mouse button is released.  I prefer that to the jitteriness, though.

**Comment by jeffmath** [comment]
@skarjalainen @wcjordan I was able to remove the jitter of the scrollbar thumb by removing these lines from the FDT dist/*.css files:
```
  -webkit-transition-duration: 250ms;
          transition-duration: 250ms;
```
As a bonus, the thumb syncs faster with the user's mouse drag, on all browsers.

**Comment by wcjordan** [comment]
Nice, I'll give the PR a look!
