### ISSUE TITLE
Double scrollbars display bug with fixedRight columns

### ISSUE THREAD

**Issue by ricovitch** [schrodinger/fixed-data-table-2#291]
Follow up about this previous resolved issue : #260 

## Expected Behavior
With a fixed right column and both vertical and horizontal scrollbars, when scrolling with the horizontal scrollbar, table headers content should not be visible at the top of the vertical scrollbar (top right of the table)

## Current Behavior
We can observe table headers content scroll "under" the fixed column at the top right of the table

## Possible Solution
We did not find a workaround, as everything is absolute positionned, and there is no css class on the fixedColumn to tweak.

## Steps to Reproduce (for bugs)
* https://codesandbox.io/s/xo1r9o868z
* scroll horizontally and observe the top right of the table

## Context
The case with horizontal and vertical scroll bars is frequent on our side as we have tables with a lot of columns and rows.

## Your Environment
Version used: 0.8.9
Browser Name and version: reproduced on chrome and edge

**Comment by wcjordan** [comment]
This may just be a z-index fix.  @miskreant any suggestions where @ricovitch could look to fix this?

**Comment by miskreant** [comment]
@ricovitch In the sandbox, it looks like the ScrollbarSpacer doesn't have the absolute position & z-index rules from [here](https://github.com/schrodinger/fixed-data-table-2/pull/265/files#r155709489). On closer inspection, I saw that the comment in the styles has the wrong version number. I'm not familiar with codesandbox.io, but are we certain that the correct styles are being applied for FDT v0.8.9?
![fileaedwcf](https://user-images.githubusercontent.com/294747/35866965-30e0a82e-0b1e-11e8-967d-cd76b7ac21f4.png)

As an alternative @wcjordan , we could probably fix this on our end by simply inlining said styles.. but it seems like the stylesheets bundled w/FDT should be in use..

**Comment by ricovitch** [comment]
@miskreant you are right i did not pay attention, but the v0.8.0 css styles were pasted right in the index.html code, instead of importing the css from the update fixed-data-table-2 v0.8.9
I modified the codesandbox sample to load the right css path, and the bug still happens.
https://codesandbox.io/s/xo1r9o868z

![ep-3414_fdt2_0 8 9](https://user-images.githubusercontent.com/186973/35919217-b7fbdb48-0c14-11e8-9bcb-8032984f9d90.jpg)

**Comment by wcjordan** [comment]
Any updates here?  Is this still an issue?

**Comment by ricovitch** [comment]
Sorry i didn't have time to look at that recently, i will try to come back to you ASAP
