### ISSUE TITLE
Pagination example doesn't have any pagination

### ISSUE THREAD

**Issue by yantakus** [schrodinger/fixed-data-table-2#295]
Hi there. Thanks for the awesome library! Just wanted to report that pagination example http://schrodinger.github.io/fixed-data-table-2/example-pagination.html actually doesn't have any pagination.

**Comment by wcjordan** [comment]
Hmm ya that isn't the best named.  I'd be happy to accept a PR renaming to infinite scroll or infinite data loading.

**Comment by yantakus** [comment]
@wcjordan Sorry, but I don't see there any infinite scroll as well. It renders all the 1999 items right from the start.

**Comment by wcjordan** [comment]
It only loads 200 and renders 20 (but it's fast since the data is generated locally).  I recommend looking at the DOM and then dragging the scrollbar down and looking for the text in the grid to say pending to understand better.

**Comment by wcjordan** [comment]
Closed via #354
