### ISSUE TITLE
Is it possible to create row group (pivot table)

### ISSUE THREAD

**Issue by zuyetawarmatik** [schrodinger/fixed-data-table-2#299]
Hi, is there any example that shows the ability to group rows (expanding trees), i.e pivot table?

**Comment by wcjordan** [comment]
We don't support this as a first class feature, but we support 2 ways you can implement this on top of our API.

1) Follow the [Expanded Rows example](http://schrodinger.github.io/fixed-data-table-2/example-expanded-rows.html) and render sub tables in the expanded content
2) Render the rows you want and use the first columns' renderers to give a UX feel of column grouping.

I'm going to close as this isn't an issue nor something we plan to implement further, but feel free to follow up if anything's unclear.
