### ISSUE TITLE
Resizing the window when the table is scrolled to the bottom element locks the table view

### ISSUE THREAD

**Issue by matneyx** [schrodinger/fixed-data-table-2#302]
(Maybe related to this FDT1 bug: https://github.com/facebookarchive/fixed-data-table/issues/25#issuecomment-307140600 )

https://youtu.be/_VM65xaWS6o  (video is upside down... I'll get a better one uploaded tomorrow)

When a table doesn't have enough rows to require a scrollbar, and you resize the window small enough to require a scroll bar, scroll down, and then resize the window to the original size, top-most rows are unrendered and inaccessible.

## Expected Behavior
The table should render all rows when window is resized large enough to not require a scrollbar

## Current Behavior
The table removes the scroll bar, but doesn't rerender -- top-rows are inaccessable

## Steps to Reproduce (for bugs)
1. Take a table where there aren't enough rows to warrant a scrollbar
2. Resize the window small enough that you get a scroll bar
3. Scroll to the bottom of the table
4. Resize the window, again, to be large enough to remove the scrollbar from the table

## Your Environment

* Version used: 0.8.11
* Browser Name and version: Chrome Version 64.0.3282.186 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Windows 7 Enterprise
* Link to your project:

**Comment by matneyx** [comment]
Now that you mention Responsive, I'm really embarrassed... I was using a ResponsiveDataTable wrapper around FDT2 columns and cells. (I'm working on a 2-year-old bug...) :(  

Thank you.

**Comment by wcjordan** [comment]
No problem, thanks for  reaching out, and glad you got it resolved!
