### ISSUE TITLE
Cannot resize columns when using ColumnGroup

### ISSUE THREAD

**Issue by namibian15** [schrodinger/fixed-data-table-2#306]
##Summary
When creating a table with grouped columns, one cannot resize the "sub-columns" of the ColumnGroup

## Expected Behavior
Should be able to resize columns under ColumnGroup just like regular table without CoulmnGroup.
## Current Behavior
I defined a callback to handle column resizing. I declared the onColumnResizeEndCallback in the table options to invoke this callback. When mouse down on the resizer, the thin blue line appears which can be moved by moving the mouse. On mouse up, the callback is invoked, yet the column is not resized and the thin blue line never gets "released" or cleared.

## Possible Solution
None that comes to mind

## Steps to Reproduce (for bugs)
1. Define a table with any number of ColumnGroup definitions.
2. Add the onColumnResizeEndCallback to table options
3. Implement callback to be invoked with onColumnResizeEndCallback

## Your Environment
* Version used: ^0.8.11
* Browser Name and version: Firefox 59.0 (64-bit); Chrome 65.0.3325.181

**Comment by wcjordan** [comment]
Could you provide a jsFiddle or CodePen to reproduce the issue?  It sounds like you may have issues with updating the state properly in your handler.  I'm going to close as this isn't currently actionable, but will re-open when there's a valid repro.
