### ISSUE TITLE
When using a rowHeightGetter, the grid is losing rows (not rendering them)

### ISSUE THREAD

**Issue by fairps** [schrodinger/fixed-data-table-2#310]
We have say 100 rows of data, and we are using the rowHeightGetter to calculate the desired height of each row.  Let's say rowHeight = {10}, so it looks like an internal size of 1000 is being calculated to put up the scroll bar and to display the rows.  However, since some of our rows have a larger height than 10, we only see say 70 of the rows rendered, and we can scroll all the way down and it looks like there are only 70 rows.  We have embedded this is a region that can be resized (splitters) and resizing the region causes the full number of rows to appear, but it is messed up until the resize.

We have played around with the initial rowHeight setting and if we calculate an average height for our rows and put that into rowHeight it seems to allow all of the data, but the scroll bar stops before hitting the bottom of the trough the scroll bar travels in (maybe 80% of the way down)

## Expected Behavior
All rows should render with the heights returned by rowHeightGetter, all rows should display, and the scroll bar should be correct

## Current Behavior
Some of the bottom rows do not render, and scrolling all the way down looks successful but rows are missing.  The table size seems to be initially limited by rowHeight until a resize

## Possible Solution
Calculate an average row height and use it for determining the area needed for rendering?

## Steps to Reproduce (for bugs)
Pretty easy to reproduce if you set rowHeight={1} and rowHeightGetter={( ) => 20} then throw about 100 rows into the grid

## Context
Misrepresentation of data  without the work-around of setting rowHeight to the average row size.  With the work-around the scroll bar just doesn't work correctly.

## Your Environment
* Version used:  0.8.11
* Browser Name and version: Chrome Version 64.0.3282.186 (Official Build) (64-bit)
* Operating System and version (desktop or mobile):  Windows 7
* Link to your project:  not public

**Comment by wcjordan** [comment]
Dynamic row heights don't work well due to design decisions from FDT.  We've re-architected the whole library to fix these with the 1.0 release which is currently in beta pending updated documentation and stress testing in a real application.  I recommend trying that out (fixed-data-table-2@1.0.0-beta.4) and seeing if it addresses the issue you're seeing

**Comment by wcjordan** [comment]
Fantastic to hear!  Let me know if you see any issues with the beta

**Comment by fairps** [comment]
Will do.  We actually rolled it out the day you mentioned trying it and it has been running solidly ever since.  Performance seems to be as good or better than the previous version as well.  Our grids are pretty heavy... 30+ columns and a few thousand rows so they are a good test of heavy use

**Comment by wcjordan** [comment]
Awesome, that's great to hear!  I haven't had a chance to test it yet in our main app, which is why it's still beta.  Good to hear it's holding up!

**Comment by pradeepnschrodinger** [comment]
Closing the issue, as this was fixed in our beta branch (now released as [v1.0.0](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v1.0.0)).
