### ISSUE TITLE
Sort arrow is backwards

### ISSUE THREAD

**Issue by Tsmith18256** [schrodinger/fixed-data-table-2#311]
## Expected Behavior

* When sorting a column in ascending order, the arrow should point up.
* When sorting a column in descending order, the arrow should point down.

## Current Behavior

The arrow points in the directions opposite to those mentioned above.

## Possible Solution

Reverse the order of the arrow.

## Steps to Reproduce (for bugs)
Open [the client-side sort example](http://schrodinger.github.io/fixed-data-table-2/example-sort.html) and sort a column.

## Context

Sortable tables use the arrows as described in Expected Behavior. See Spotify as an example:

![image](https://user-images.githubusercontent.com/7586082/38339869-5c71861e-3825-11e8-874b-2dc07b8f186c.png)

Vs the current implementation:

![image](https://user-images.githubusercontent.com/7586082/38339878-66670f86-3825-11e8-9be3-bacc1abf367c.png)

**Comment by wcjordan** [comment]
I'm happy to accept a PR for this.  The issue is related to the header renderer in the example here:
https://github.com/schrodinger/fixed-data-table-2/blob/master/examples/SortExample.js#L33

**Comment by Tsmith18256** [comment]
Thanks for pointing out the location of that, I have opened #312.

**Comment by KamranAsif** [comment]
It seems subjective which way the arrow should go. Down makes sense to me, because your going in descending order.

**Comment by Tsmith18256** [comment]
@KamranAsif Down being descending is what would usually be happening. The order in the screenshot above is ascending but the arrow is pointing down.

**Comment by KamranAsif** [comment]
I see what your saying, I always thought of as logically going downwards.

**Comment by wcjordan** [comment]
Closed with #312
