### ISSUE TITLE
Cell component customer input value is repeated every 25 rows

### ISSUE THREAD

**Issue by xhe** [schrodinger/fixed-data-table-2#314]
We want to use customer component in the Cell, which is only a very simple input box. like below:

In the Table config, 

`cell={ <CustomerCell />}`

in the CustomerCell component:

`return <Cell>
            <div>
               <input type='text' defaultValue={this.props.rowIndex} />
            </div>
            </Cell>;`

Now when I am passing more than 25 rows, I found that whenever user entered content in the first row input box, the value automatically appeared in the 25th row input box when I scroll down the table. And when scrolled up, the value is no longer in the first row, but moved to second row.

Also the weird thing is I see the input default value is normal in first screen, but when I scroll down, I saw the defaultValue resetted to 0 after the 25th row. So why the rowIndex become 0 automatically?

I tried to set allowCellsRecycling, but useless at all.

## Expected Behavior
The customer component should never be auto-duplicated. It looked at some caching issue or recycled/reused improperly.

## Your Environment

* Version used: 0.8.5
* Browser Name and version: chrome
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by KamranAsif** [comment]
See https://github.com/schrodinger/fixed-data-table-2/issues/18#issuecomment-227744217
