### ISSUE TITLE
fix example link

### ISSUE THREAD

**Issue by hoshmn** [schrodinger/fixed-data-table-2#317]
The [fiddle](https://jsfiddle.net/uq8osbp1/) provided in Steps To Reproduce is broken. We may want to provide an alternate, such as [this codepen](https://codepen.io/alphalpha/pen/oqKJgG)

**Comment by hoshmn** [comment]
jsfiddle-integration-babel has been broken due to jsfiddle mixed content policy for a number of months... we may want to link to a functional codepen like this one at least for the time being

**Comment by wcjordan** [comment]
This sounds good to me, do you want to open a PR to switch things over?

**Comment by hoshmn** [comment]
Sounds good
