### ISSUE TITLE
cursor jump to top of the table once data is updated

### ISSUE THREAD

**Issue by xhe** [schrodinger/fixed-data-table-2#320]
Recently we upgraded fixed data table 2 from previous 0.7.4 to 0.8.5, and we noticed one issue. Before, when user scroll the table to the end, we use infinity scroll to fetch next page data and then append to the current datalist and then bind back to FDT. The cursor should scroll up to the previous end point, that will be somewhere in the middle of the table.

But now, we noticed once we bind the newly generated the datalist to the FDT, the cursor immediately jump to the top of the table.This is very bad user experience as user lost their previous view point.

Is this a bug or we need to do something special to maintain the cursor position?

Thanks

**Comment by wcjordan** [comment]
That's unusual and not what I see with the [pagination / infinite scroll example](http://schrodinger.github.io/fixed-data-table-2/example-pagination.html).  If you have an example JsFiddle / CodePen which reproduces the issue I'm happy to take a look.

My guess is one of two things is happening:
1) Before updating the table with the new data, all data / rows are being cleared collapsing the table to have no content (and forcing scroll to 0).
2) When the rowsCount change, we're create a new ScrollHelper and when we set it to the previously scrolled row & offset, it's not working.
See https://github.com/schrodinger/fixed-data-table-2/blob/master/src/FixedDataTable.js#L1122 for where we do this.

**Comment by pradeepnschrodinger** [comment]
Fixed in beta, and no longer reproducable with the [v1.0.0](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v1.0.0) release.
