### ISSUE TITLE
input in cell onBlur event not firing

### ISSUE THREAD

**Issue by leemm** [schrodinger/fixed-data-table-2#325]
## Expected Behavior
When table has a lot of rows, with several columns, containing a ``<input type=text/>`` in each cell, the onBlur event doesn't fire on the focused element if you scroll vertically to the other opposite of the table.

## Current Behavior
Whenever a value is entered and then onBlur is fired it saves the value to a batch ready for saving.  If you scroll slowly and focus on another cell/input it runs as expected.  However, if you scroll far down the table and perform the same action, onBlur is never fired (the console.warn never appears in the example below).  Presumably because the component has been destroyed or recycled?

## Possible Solution
Is there any to prevent recycling of rows/cells?
After browsing through the other issues on here I discovered that by ensuring each input's key is unique should prevent this from happening.  I've checked and they're all unique so it doesn't appear to work.

## Steps to Reproduce (for bugs)
This is our cell code (with some app specific custom logic removed).

```javascript

        let {
            onSave,
            onCellFocus,
            onUpdateLocal,
            inputKey = `input_${this.props.row.id}_${this.props.column.id}`,
            inputvalue
        } = this.props;

         return (
            <Cell>
                <input
                    ref={ inputKey }
                    className="assessment__input assessment__input--text"
                    value={ inputvalue }
                    key={ inputKey }
                    id={ inputKey }
                    type="text"
                    onFocus={ e => onCellFocus( column, row, e ); }
                    onBlur={ () => { console.warn('BLUR'); onSave.bind(this, 'score'); } }
                    onChange={ onUpdateLocal.bind(this) }
                />
            </Cell>
        );
```

## Context
By providing a large table of editable cells to the end user.  Any value can be modified and we track the change via onBlur.

## Your Environment
* Version used: 0.8.12
* Browser Name and version: Chrome 65.0.3325.181
* Operating System and version (desktop or mobile): Mac OS X, Windows 10

**Comment by wcjordan** [comment]
This sounds similar to #18 and #152 & #149.  Since onBlur isn't expected to be fired when a component unmounts, you may want to have the cell call save directly when the cell unmounts.

I'm going to close as this isn't actionable from the FDT side, but feel free to continue the discussion if you have questions about how FDTs virtual rendering works.

**Comment by leemm** [comment]
OK, that makes sense, thanks for the reply.

The problem we've got is that the above code is inside a Component but componentWillUnmount is never called.  Are you saying that we should extend Cell and check for componentWillUnmount on that?

**Comment by wcjordan** [comment]
Not 100% sure I follow, but to clarify, the table & column components will not unmount but the component you pass in as the cell prop will.  It sounds like you may be using the reference implementation of Cell which provides the styled divs.  You should implement your own cell logic in a component composed of that much like these examples: https://github.com/schrodinger/fixed-data-table-2/blob/master/examples/helpers/cells.js

**Comment by leemm** [comment]
OK, thanks.  But that seems to be the issue.  This is the entire CellComponent (used in same way as the examples).  Adding componentWillUnmount seems to do nothing i.e. nothing appears in the console.
I can't quite see what I'm doing wrong here.  Could it be the way we've implemented it?

```
import React, { Component } from 'react';
import { Cell } from 'fixed-data-table-2';
import Classnames from 'classnames';
import { keys } from './cell-helpers';

import ErrorFlag from './ErrorFlag.jsx';

class TextInputCell extends Component {

    render() {

        let {
            column,
            row,
            hasEdit,
            assessment,
            onSave,
            onBulkScoreUpdate,
            bulkCell,
            onCellFocus,
            onUpdateLocal,
            columnKey,
            inputKey = `input_${this.props.columnKey}_${this.props.rowIndex}`,
            showModal,
            validationError,
            move
        } = this.props;

        let wrapperclasses = Classnames({
            'assessment__cell': true,
            'assessment__cell--bulk': bulkCell,
            'error': validationError,
            'has-value': assessment && assessment.score && assessment.score.length
        });

        /**
         * Avoid controlled / uncontrolled input error
         */
        const inputvalue = _.has( assessment, 'score' ) ? assessment.score : '';

        return (
            <Cell className={ wrapperclasses }>
                <input
                    ref={ inputKey }
                    className="assessment__input assessment__input--text"
                    data-column={ columnKey && columnKey.toString() }
                    value={ inputvalue }
                    key={ inputKey }
                    id={ inputKey }
                    type="text"
                    disabled={ !hasEdit }
                    onFocus={ e => onCellFocus( column, row, e ); }
                    onBlur={ onSave.bind(this, 'score') }
                    onChange={ onUpdateLocal.bind(this, 'score') }
                    onKeyDown={ e => {
                        const key = keys[e.keyCode];
                        if (key){
                            e.preventDefault();
                            move(key, inputKey);
                        }
                    } }
                />

                {/* // Show Status */}
                { validationError && <ErrorFlag onTouchTap={ () => { showModal(true); } } /> }

            </Cell>
        );

    }

    componentWillUnmount(){
        console.warm('nothing...');
    }
}

export default TextInputCell;

```

**Comment by wcjordan** [comment]
Ahh okay.  I think the issue is your TextInputCell is being recycled since rows are recycled, but the input element is being recreated since it has a unique key.  You should put the the unique key value on the same component as has the componentWillUnmount handler.

**Comment by leemm** [comment]
Thanks Chris, that works.  Never occurred to me to check the key on the TextInputCell (this section of the app is quite a complicated mish-mash of components) but that works as I hoped.
