### ISSUE TITLE
Odd rows in table with fixed columns on either side render above the fixed cells.

### ISSUE THREAD

**Issue by andpor** [schrodinger/fixed-data-table-2#327]
It is very weird but it seems that odd rows in table with fixed columns on either side render cells above the fixed cells. It is a very basic example based on your example only with first 7 columns in table fixed on LHS...

## Expected Behavior
Both even and odd rows render under the fixed area

## Current Behavior
Odd rows in table with fixed columns on either side render above the fixed cells. Headers and even row render below fixed columns correctly. row indexing from 0...so row 0 renders fine, 1 doesn't, 2 does, 3 doesn't and so on...

## Your Environment
* Version used: 0.8.13
* Browser Name and version: Chrome 46.0.2490.80 (64 bit)
* Operating System and version (desktop or mobile): Mac OS X
* React: 15.6.2

**Comment by wcjordan** [comment]
Could you provide a reproduction?  There's not much we can do to help with the current detail on this issue.

**Comment by wcjordan** [comment]
Any update here?

**Comment by andpor** [comment]
Bug in my code.
