### ISSUE TITLE
Scroll bars behave oddly in Safari

### ISSUE THREAD

**Issue by ghardin137** [schrodinger/fixed-data-table-2#328]
In Safari, (Latest and previous version), the scroll bars do not properly follow the arrow and get jittery when scrolling.

## Expected Behavior
Scroll bars should move smoothly and with the mouse pointer as they do in other browsers.

## Current Behavior
Scroll bars are jittery and move around sporadically and do not say with the mouse pointer.

## Steps to Reproduce (for bugs)
You can reproduce this error by opening any of the examples such as http://schrodinger.github.io/fixed-data-table-2/example-object-data.html with Safari (11.1 or 10.1.2) and then trying to scroll the table vertically.

## Context
Seems to occur in all tables that would include scroll bars.  Longer results cause it to happen worse.
In my environment the table has between 50 and 500 rows.  This occurs in both vertical and horizontal scroll bars.

## Your Environment
* Version used: Latest
* Browser Name and version: Safari (11.1 and 10.1.2)
* Operating System and version (desktop or mobile): Mac OS 10.13.4 and 10.12.6 Desktop

**Comment by wcjordan** [comment]
I'm happy to accept a PR for this, but unfortunately we don't support Safari.  You can find our supported browsers in the README.  I'm going to close since we're unlikely to fix this, but feel free to follow up if you want to tackle it and would like advice on what to look at.

**Comment by ghardin137** [comment]
I can definitely look into a fix if you can give me a few places to start looking

**Comment by wcjordan** [comment]
I'd start with [Scrollbar.js](https://github.com/schrodinger/fixed-data-table-2/blob/master/src/Scrollbar.js) and see if safari doesn't like any of the css or if the props / state there are changing in an inconsistent way (e.g. bouncing up and down).  Particularly any animation or translate 3d css might have weird cross browser differences.

The next thing to check would be the [ScrollHelper](https://github.com/schrodinger/fixed-data-table-2/blob/master/src/FixedDataTableScrollHelper.js).  I think it's less likely to be an issue there, but may be worth a look.
