### ISSUE TITLE
Row context menu support

### ISSUE THREAD

**Issue by ervoiox** [schrodinger/fixed-data-table-2#33]
Does this have support for row level context menus?

I see there's a outstanding PR on Facebook's fixed-data-table which was never merged in: https://github.com/facebook/fixed-data-table/pull/321

**Comment by KamranAsif** [comment]
We currently don't, but if you apply that same PR on our fork we would love to merge it in

**Comment by sli** [comment]
I desperately need this. Still accepting a PR or have things changed since this was originally posted?

**Comment by wcjordan** [comment]
We'd still accept a PR.  I recommend exposing some event handler and maybe adding an example which shows integration with an existing context menu library.  We don't need to support a custom context menu internal to the repo.

**Comment by sli** [comment]
I've already applied the old PR to a fork of this repo. Nothing special or custom added beyond that, just a straight port. I just need to get it all built and tested before I submit the PR, which seems to require Linux (building looks to be totally broken when using git-bash on Windows). I'll have to wait until after work to build and test on my home machine.

**Comment by wcjordan** [comment]
Linux & mac should work, but ya no idea about windows for development.

**Comment by sli** [comment]
I've finally gotten a chance to come back to this and applied the PR from the original repo. Everything seems to be functioning great. I'm using react-contextmenu to test, as that's what I'm using in the actual app. Any context menu module that supports programmatically triggering the context menu should work. Everything is isolated to a set of onContextMenu functions, so no existing code should be affected.

As a quick reference, onRowContextMenu looks like:

`(event, rowIndex) => { /* handler code */ }`

Writing the PR now.

**Comment by difelice** [comment]
Hi @sli, glad to hear you're porting this feature. Thanks. 👏

**Comment by wcjordan** [comment]
The PR for this went stale, but if you want to get it in, it looks like there's just a minor cleanup needed to not alter the old docs.

**Comment by wcjordan** [comment]
Fixed w/ #301.  Will release w/ v0.8.11

**Comment by wcjordan** [comment]
Released with v0.8.11
