### ISSUE TITLE
Shift+mousewheel doesn't cause horizontal scrolling

### ISSUE THREAD

**Issue by jeffmath** [schrodinger/fixed-data-table-2#335]
## Current Behavior
For your [example](https://schrodinger.github.io/fixed-data-table-2/example-object-data.html), pressing the shift key while using the mouse scroll-wheel should scroll the non-fixed columns horizontally.

## Current Behavior
Vertical scrolling of all rows occurs, instead.

## Context
My team has tasked me with replacing a react-virtualized grid in our app with a fixed-data-table-2 table.  The former supports horizontal scrolling using shift+mousewheel, but the latter does not.

## Your Environment
* Version used: 0.8.13
* Browser Name and version: Chrome v67.0.3396.99
* Operating System and version (desktop or mobile): Windows 10 Pro desktop

**Comment by wcjordan** [comment]
I'd be happy to review a PR for this.  It seems straightforward and valuable.

Out of curiosity, why are you migrating away from react-virtualized?

**Comment by jeffmath** [comment]
@wcjordan, react-virtualized has this [bug](https://github.com/bvaughn/react-virtualized/issues/291), which the author doesn't seem motivated to fix.

The odds of me submitting a PR are very slim.  I could see about my client contracting you for the work, if you would be interested.
