### ISSUE TITLE
onClick border not required

### ISSUE THREAD

**Issue by rajatrawataku1** [schrodinger/fixed-data-table-2#336]
I want to remove the border created when we click on the table. I tried it to remove through css, may be its been injected through javascript. Is there any way to do this ?

**Comment by rajatrawataku1** [comment]
Yeah , It solved the issue. 

*:focus {
    outline: none;
}

This command does the work but it is applied to the whole body. So if anybody wants to apply on the table only, use this syntax.

TableClassName :focus{
    outline: none;
}

Working in both chrome and Internet explorer.

Thanks, @wcjordan

**Comment by xalisys** [comment]
This fixes the problem for me: 
`
.classNameForTable:focus{
outline-color: unset !important;
outline: unset !important;
}
`

**Comment by pradeepnschrodinger** [comment]
Closing the issue since the border is not controlled from our side, and is probably applied from the browser. 

We could just use the CSS selectors explained above on the root table component.
