### ISSUE TITLE
Missing internals folder

### ISSUE THREAD

**Issue by SheepFromHeaven** [schrodinger/fixed-data-table-2#343]
Just installing and using the package won't wirk for me. It tells me the internals folder is missing.

## Expected Behavior
After installing the package with yarn, I can just import the components as described in the example. 

## Current Behavior
Importing the components throws an error at build time, that the internals folder is not existing.

## Possible Solution
Have the build internals script run as npm post install script.

## Steps to Reproduce (for bugs)
- install the package with yarn
- import {COMPONENT} from 'fixed-data-tables-2';
- build it with webpack

## Context
I just want to use it with webpack and ES6 imports.

## Your Environment
* Version used: 0.8.4
* Browser Name and version: No browser => build time 
* Operating System and version (desktop or mobile): OsX and windows
* Link to your project: not public 😞

**Comment by wcjordan** [comment]
Could you create a toy project that reproduces this with a webpack config?  This sounds like an issue with your webpack config to me, but I can't help without more details. 

2 other things you can check:
1) Your issue import from fixed-data-tables-2, that should be fixed-data-table-2, but I'm guessing that's just a typo on the issue.
2) You can check that node_modules/fixed-data-table-2/internal exists

I'm going to close until this is actionable, but please feel free to re-open when an example project exists.
