### ISSUE TITLE
How to use this with css modules?

### ISSUE THREAD

**Issue by g-kanoufi** [schrodinger/fixed-data-table-2#349]
Hello, i am trying to get Fixed Data Table 2 with css modules, but can't find a way to integrate it to my app.

Any help on how to achieve this would be greatly appreciated.

Right now if i import the css in my grid file or in the html with a <link> nothing is happening, can't see any of the css taking on.

Thank you for your help

**Comment by wcjordan** [comment]
Best I can point you to is #60 and #61.  This may be something internally related to the particular project you're using for CSS modules or your build system.

I'm going to close as this isn't a bug report, but feel free to continue asking questions here, and I'll help w/ anything I can.
