### ISSUE TITLE
onScrollEnd is invoked with previous this.state.scrollX

### ISSUE THREAD

**Issue by xinghul** [schrodinger/fixed-data-table-2#355]
## Expected Behavior
onScrollEnd is invoked with updated this.state.scrollX.

## Current Behavior
onScrollEnd is invoked with previous this.state.scrollX.

## Possible Solution
<img width="1050" alt="screen shot 2018-10-15 at 1 24 08 pm" src="https://user-images.githubusercontent.com/6555861/46976349-144f5400-d07e-11e8-80b4-46d65ca17cda.png">
line 1337, invoke `this._didScrollStop()` in setState() callback instead, something like:

```javascript
this.setState({
     scrollX: roundedX
}, this._didScrollStop);
```

So it's invoked after scrollX value is updated.

**Comment by wcjordan** [comment]
I'm happy to accept a PR for this, but we should leave it as is on the master branch to avoid breaking changes to the API.  Instead let's fix on the v1 beta branch.  Things will be trickier there though as the actions are pulled out to redux so didScrollStop will likely need to be as well.
