### ISSUE TITLE
Is that possible to get the row height from the DOM? Or leave the row height not set?

### ISSUE THREAD

**Issue by moonkop** [schrodinger/fixed-data-table-2#356]
My rows are some cards generate from json , the length or height of content of these cards are not known before they are rendered in the DOM. 
What I am doing is to find a way to calculate the height of each row and put it in to the rowHeightGetter,and the height I get form my way is not exactly the same as the height from the DOM.

**Comment by wcjordan** [comment]
We don't support getting the row height from the DOM, but you can look at using something like [react-virtualized CellMeasurer](https://github.com/bvaughn/react-virtualized/blob/master/docs/CellMeasurer.md) to calculate the height and store it somewhere that rowHeighGetter can use.

If you're doing this, I recommend using the v1 beta branch as the current production version has many bugs related to dynamic row heights.

I also recommend looking at these issues so you're aware of some of FDT2's limitations:
https://github.com/schrodinger/fixed-data-table-2/issues/166
https://github.com/schrodinger/fixed-data-table-2/pull/162#issuecomment-305547043
