### ISSUE TITLE
How can we add a header filter, PopUp

### ISSUE THREAD

**Issue by datavisorfrankhe** [schrodinger/fixed-data-table-2#357]
Hello,
I am having one question on using Fixed data table and don't know if you can help to clarify.
We need to put column filter in the header. There is an icon located in header cell, and if user click that filter icon, there should be one pop-up appears, inside the popup, there are filter form only for this column. I thought I can easily put a sub-component inside the header cell, and if user click the icon, just show that component.
But I found not that easy. The header cell space are not allowed to be expanded, also, the filter component will  be restricted only inside the small header cell space. I want it to have pop-over effect, so that we can provide complicated filter config, such as time range, multi-select etc.
can you help to clarify how to resolve this requirement?
Thanks

**Comment by wcjordan** [comment]
I would recommend looking into Portal's in React ([React 16+](https://reactjs.org/docs/portals.html), [React 15 & less](https://www.npmjs.com/package/react-portal)).  They were built to solve the problem you're describing.

I'm going to close as this isn't an FDT issue, but please feel free to respond if you have further questions.
