### ISSUE TITLE
There is blank column when set attribute 'showScrollbarY={false} '.

### ISSUE THREAD

**Issue by xinlizhang** [schrodinger/fixed-data-table-2#359]
Hi guys, I found a black column will show when I set the attribute 'showScrollbarY={false} ' for fixed-data-table-2.

## Current Behavior
![image](https://user-images.githubusercontent.com/27684721/47554191-61171280-d93b-11e8-9bea-37d345e84706.png)

## Possible Solution
I read the codes of fixed-data-table-2, and found container's height is the only condition for adjust width for scrollbar, I think another condition is if the scrollbar is hidden.
<img width="791" alt="image" src="https://user-images.githubusercontent.com/27684721/47555030-64ab9900-d93d-11e8-974e-8e3abe7d5535.png">

I apply a Pull Request(https://github.com/schrodinger/fixed-data-table-2/pull/358).

PS: By the way, thanks for your code, fixed-data-table-2 is the best table library I have never used.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by wcjordan** [comment]
@miskreant could you check out this issue request?  I believe it relates to work you've done, previously.

**Comment by wcjordan** [comment]
Fixed via #358 and released w/ v0.8.16
