### ISSUE TITLE
Expanded rows example: The content of last item is not visible on expanded state

### ISSUE THREAD

**Issue by giladtamam** [schrodinger/fixed-data-table-2#360]
On Expanded rows example The content of last item is not visible on expanded state

## Expected Behavior
Click on the last item will open the content 

## Current Behavior
The last item content is not visible when click to expand

## Steps to Reproduce (for bugs)
go to [example](https://schrodinger.github.io/fixed-data-table-2/example-expanded-rows.html)
scroll to last item and click to expand

## Your Environment

* Version used: Example
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): desktop
* Link to your project: https://schrodinger.github.io/fixed-data-table-2/example-expanded-rows.html

**Comment by wcjordan** [comment]
I suspect this is the same issue as #310 #37 and #25 and is fixed on v1.

**Comment by giladtamam** [comment]
thanks!
I saw that v1 is still under beta.
How stable is it?
Is it possible to merge that fix to stable version?

**Comment by wcjordan** [comment]
I don't know of any issues w/ the beta, but am not using it on any large projects at Schrodinger yet.  Many have used it and reported it works well for them though.  One person mentioned seeing some issues this week but hasn't responded w/ what they saw yet.

Unfortunately the change can't be backported as it's a total rewrite of the library's state management.  The original version written by Facebook included an API for dynamic row heights, but the architecture doesn't support it well and has frequent issues with an incorrect tracking of the total table height.  The rewrite fixes those, but via a total overhaul using Redux for state management.

**Comment by pradeepnschrodinger** [comment]
Closing the issue as this was fixed in beta. 
See latest [v1.0.0](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v1.0.0) release.
