### ISSUE TITLE
Massive data render getting slow performance

### ISSUE THREAD

**Issue by gopinath-sixt** [schrodinger/fixed-data-table-2#361]
## Expected Behavior
When rendering massive data to be fast without hanging.

## Current Behavior
When rendering massive data getting hanged and slow.

## Steps to Reproduce (for bugs)

1.calling api for getting massive data(>4000 list) and then updated redux state, render from connection component and browser getting hanged for six seconds and after few seconds, scrolling with massive data with vertical or horizontal perfectly working
2.Selecting checkbox from row, updating boolean value in redux state and through connection component getting re-render and now again getting hanged and then working perfectly.

Notes: In Column Component pureRendering={true} allowCellsRecycling={true} was used.

## Your Environment

* Version used: "^0.8.13"
* Browser Name and version:  chrome 70.0.3538.77 
* Operating System and version (desktop or mobile): window 10
* Link to your project:

**Comment by varunm0503** [comment]
Hey @wcjordan,
I am facing a similar performance issue where the whole table gets re-rendered due to change in any props. I can add shouldComponentUpdate at Cell level. However, this would be too much code as I will have to add a shouldComponentUpdate on every Cell Renderer. Can I add shouldComponentUpdate at Row level?
I read fixed-data-table-2 source code and shouldComponentUpdate for FixedDataTableBufferedRows currently returns true. Why are we avoiding optimisation at Row level?

**Comment by wcjordan** [comment]
Unfortunately that's not how FDT is designed for 2 major reasons.  First FDT doesn't manage the data or perform any diffing over it, so we would not have a way to know if a rows data has changed or not.  Second FDT reuses rows to avoid extra mounts and unmounts.  If you optimize your cell renderers, these leads to better performance, but it does require that.  Do to these design decisions, FDT doesn't know enough about when rows should and shouldn't update to handle that check internally.

Some libraries which might fit your use case better might be [react-table](https://react-table.js.org/#/story/readme) which doesn't provide virtualization or [react-virtualized's List](https://bvaughn.github.io/react-virtualized/#/components/List) which operates on a per row motif.

**Comment by varunm0503** [comment]
@wcjordan Thanks for your input. I understand what you are saying. I will optimise my Cell Renderers instead of optimising rows. 
Cheers!
