### ISSUE TITLE
adding checkbox on first column messed up checked status when user scroll down

### ISSUE THREAD

**Issue by datavisorfrankhe** [schrodinger/fixed-data-table-2#362]
I need to add checkbox on the first column, this is what I added, 

1. In Table comp, I added this column:

```
<Column
                    width={50}
                    header={<ColumnHeaderCheckBoxCell/>}
                    cell={<ColumnCheckBoxCell key={this.props.rowIndex} />}
                />
```

2. For the cell:
```
    _onChange(e) {
        this.setState({
            checked: e.target.checked
        });
}
render() {
        return (
            return (
            <Cell>
                <input type="checkbox"  key={this.props.rowIndex} checked={this.state.checked}  onChange={this._onChange}/>
            </Cell>
        );
        );
    }
```

Now I tested by providing 1000 rows, but when I check fist three rows and scroll down, I found after certain number of rows, they are auto checked.

And when I scroll to the top, the first three rows shifted down a bit, and if I scroll again, this happened 

I googled a lot and some one suggested to put key there, but I don't think it worked either.

Any suggestions?

**Comment by wcjordan** [comment]
This is happening because the React cell component is being recycled (FDT reuses rows to minimize perf issues from mounting and unmounting).  Adding a key to your cells will prevent them from being recycled, but you could also have an issue of component not rerendering due to a failed prop change check or something else in you cell components.

I'm going to close this as it's not in an actionable issue state right now, but feel free to follow up if you have any further questions.

**Comment by datavisorfrankhe** [comment]
@wcjordan , thanks for your explanation, I even set 
```
allowCellsRecycling={false}
```
on the column level, but still when I check first checkbox, the check box in  row after 24 or other number got selected automatically.

If I remove the 
```
checked={this.state.checked} 
```

no more other row is checked, but I have no way to restore it.

Do you have any ideal or sample code I can follow to make sure the checkbox is working with scrolling?

**Comment by wcjordan** [comment]
Unfortunately I don't have any examples w/ input fields in the grid.  The closest I have are the Adv Data Context example and maybe the Cell Tooltip example.
http://schrodinger.github.io/fixed-data-table-2/example-context.html
http://schrodinger.github.io/fixed-data-table-2/example-tooltip.html

From you description, you may want to look at how this.state is getting set for your cells.  It sounds like you may be setting it at some point, but not resetting it when a rows row id / index is being updated.

**Comment by datavisorfrankhe** [comment]
Thanks @wcjordan , I set the state when component did mount

```constructor() {
        super();
        this.state = {
            checked: false
        };
        this._onChange = this._onChange.bind(this);
    }

    componentDidMount() {
        this.store = S(this.props.appId);
      
        let rowData = S(this.props.appId).getState().dataList[this.props.rowIndex];
        let keyColumnKey = S(this.props.appId).getState().config.getPrimaryColumnKey();
        let rowKeyVal = rowData[keyColumnKey];
        let nowchecked =  S(this.props.appId).getState().selectedRowKeys.includes(rowKeyVal);
        this.setState({
            checked: nowchecked
        });
    }
```
do you think componentDidMount() is a good place to set state?

**Comment by wcjordan** [comment]
You will also need to handle prop updates, since cells can be re-used when a row is reused.

**Comment by datavisorfrankhe** [comment]
the strange thing is if I put console.log in componentDidMount of the cell, 
from console, I can only see 37 rows, based on the table height, after that, when I scroll down, even if it is 100's row, there is no more print 
is the cell reused? not newly created?

**Comment by datavisorfrankhe** [comment]
that is exactly what I guess, mind show me some example on how to handle prop update?
really appreciate it.
