### ISSUE TITLE
Portal is not working for cell, still cut off

### ISSUE THREAD

**Issue by datavisorfrankhe** [schrodinger/fixed-data-table-2#366]
Hello, I need to put filter in the headerCell, since header cell is fixed position, I plan to use react-portal to append contents into the header cell.
This is my code:

```
<Cell>
                <div className="headerWrapper">
                    <span className="sortIconWrapper" onClick={this.sort}>
                        {this.state.sortIcon}
                    </span>
                    <span className="title">{this.state.columnConfig.title}</span>
                    <span
                        className="filterIconWrapper"
                        onClick={this.filter}>
                        <i className="material-icons">filter_list</i>
                    </span>
                    <span id={"filterIconWrapper_" + this.props.columnKey}></span>
                    {this.state.openFilter && (
                        <Portal node={document && document.getElementById("filterIconWrapper_" + this.props.columnKey)}>
                            <HeaderFilterComp {...this.props} />
                        </Portal>
                    )}
                </div>
            </Cell>
```

But when I click the filterIcon, the appended portal content is still cut off by the HeadCell. I tried to adjust z-index, background color and I can not not bring filter to above the table.

Can you help to give me some suggests on how to bring content above the table?

Thanks

**Comment by wcjordan** [comment]
Nothing obvious jumps out to me as the issue.  If you can reproduce in a CodePen or JsFiddle, I'm happy to take a deeper look.

I'm going to close now since this isn't an actionable issue w/ the repo, but feel free to continue the conversation as you get better reproduction steps.

**Comment by datavisorfrankhe** [comment]
That's fine Chris,
I changed to use Tether instead of Portal, not the content is working.
Thanks

**Comment by datavisorfrankhe** [comment]
Hi Chris,

I am looking at onRowClick event on the table, I need to get rowIndex, but
I can not find that attribute, do you know how I can retrieve it from this
event?
Thanks

**Comment by datavisorfrankhe** [comment]
forget, sorry, I saw it is passed in the second parameter
Thanks
