### ISSUE TITLE
May I ask what might be the cause for this error?

### ISSUE THREAD

**Issue by datavisorfrankhe** [schrodinger/fixed-data-table-2#368]
I have met this isuse:

flattenChildren(...): Encountered two children with the same key, `column10`. Child keys must be unique; when two children share a key, only the first child will be used.
in div (created by FixedDataTableCellGroupImpl)
    in FixedDataTableCellGroupImpl (created by FixedDataTableCellGroup)
    in div (created by FixedDataTableCellGroup)
    in FixedDataTableCellGroup (created by FixedDataTableRowImpl)
    in div (created by FixedDataTableRowImpl)
    in div (created by FixedDataTableRowImpl)
    in FixedDataTableRowImpl (created by FixedDataTableRow)
    in div (created by FixedDataTableRow)
    in FixedDataTableRow (created by FixedDataTableBufferedRows)
    in div (created by FixedDataTableBufferedRows)
    in FixedDataTableBufferedRows (created by FixedDataTable)
    in div (created by FixedDataTable)
    in div (created by FixedDataTable)
    in FixedDataTable (created by TableComp)
    in div (created by TableComp)
    in div (created by TableComp)
    in TableComp (created by DataTableComp)
    in div (created by DataTableComp)

My usage senerio is I exported data table into a component and use that component in angular6, and when I navigate to different page and back to same url, this error happened.

I though it was because I did not ummount the component, but when I added this:

```
ngOnDestroy(): void {
        //remove subscriber
        this.unsubscriberTheme();
		try {
			ReactDOM.unmountComponentAtNode(this.nativeElement.children[0]);
		} catch (e) { }
    }
```
error still happened.

Any solutions?

Thanks

**Comment by wcjordan** [comment]
There's not enough detail here for me to assist very much, but it looks like you might have cells rendered with the same React key in a row.   I'd double check you don't have any columns with the same columnKey.  You could deep dive and debug the code here:
https://github.com/schrodinger/fixed-data-table-2/blob/master/src/FixedDataTableCellGroup.js#L95

I'm going to close as this isn't in an actionable state.  But feel free to follow up if you learn more or have a better reproduction.
