### ISSUE TITLE
Focus jumps when I have two tables on the same screen and scroll the above table

### ISSUE THREAD

**Issue by Powerade** [schrodinger/fixed-data-table-2#369]
The version "1.0.0-beta.5" has the following bug:
When I have 2 tables on the same page, focus the bottom one, scroll the top one and then try to write something on the bottom table (which still has the focus on), the focus jumps all over the place.

Like this:
![bug](https://user-images.githubusercontent.com/36645390/49936102-f27e1c00-feca-11e8-853a-9e9f10122b75.gif)

## Your Environment
* Version used: 1.0.0-beta.5
* Browser Name and version: Chrome latest
* Operating System and version (desktop or mobile): mac desktop
* Link to your project: https://github.com/Powerade/fixed-data-table-2-bugs/tree/focus-bug-double-table

**Comment by wcjordan** [comment]
Thanks for reporting this.  We designed the v1 branch to work with multiple tables on screen, but hadn't tested it well.  There was some default state shared between the tables which I've now reinitialized with each table as part of PR #371.

**Comment by Powerade** [comment]
Hey man, thanks for the quick response.
I'm trying to run that branch with:
`"fixed-data-table-2": "git+https://github.com/schrodinger/fixed-data-table-2.git#multi_table_fix",`

But I'm getting the following error:
./node_modules/fixed-data-table-2/main.js
Module not found: Can't resolve './internal/FixedDataTableRoot' in '/Users/<user>/fixed-data-table-2-bugs/node_modules/fixed-data-table-2'

Amd I doing something wrong here?

**Comment by wcjordan** [comment]
This is now fixed w/ #371 and published as v1.0.0-beta.7
