### ISSUE TITLE
Horizontal scrollbar appears when vertical scrollbar is visible

### ISSUE THREAD

**Issue by shemExelate** [schrodinger/fixed-data-table-2#386]
When using for example a 1000px x 1000px table with 10 100px columns and many rows (in order to cause vertical scroll to show) an unwanted horizontal scrollbar appears.

## Expected Behavior
The horizontal scrollbar shouldn't appear.

## Current Behavior
An unwanted horizontal scrollbar appears

## Possible Solution
I think It should be handled in https://github.com/schrodinger/fixed-data-table-2/blob/15312e3d7790ea45b197175d7e33dde4167c2aec/src/FixedDataTable.js#L1175

## Steps to Reproduce (for bugs)
https://codepen.io/anon/pen/XOJLLa

## Your Environment
* Version used: 1.0.0-beta.5
* Browser Name and version: chrome latest
* Operating System and version (desktop or mobile): OSX 10.14.2

**Comment by shemExelate** [comment]
Reproduced in 0.8.16 too

**Comment by wcjordan** [comment]
Hey, thanks for filing.  I'd like to understand you example a bit better.  Looking at it, it appears you want a table of width X and then you want 3 columns with widths A, B, C where A+B+C adds up to X.  This doesn't leave any room for the vertical scrollbar.  So when the vertical scrollbar is shown, column C is obstructed by it.  We add a horizontal scrollbar so you can scroll and show the obstructed part of column C.  This is desired to avoid cutting off table content and leaving it impossible to view.

I recommend you explore either:
1) Adding more space to your width to accommodate the vertical scrollbar without cutting off your columns
2) Explore using the flexGrow Column prop (see [Responsive Resize example](http://schrodinger.github.io/fixed-data-table-2/example-responsive.html)) to dynamically size your columns.  This will take the space needed for the scrollbar into account and adjust depending on its visibility.
