### ISSUE TITLE
Reorderable columns bug

### ISSUE THREAD

**Issue by CosminIonascu** [schrodinger/fixed-data-table-2#39]
## Expected Behavior
When I drag a column to the left,the column should move  and when I arrived to the table end the scroll should move until the end of the columns

## Current Behavior
The scroll bar move but after 5-6 seconds the column that i was dragging disappear and the scroll bar moves on its own.

## Steps to Reproduce (for bugs)
1.Create a table with 20 + columns 
2.Try to drag the first column until the end of the table
3.After 5 - 6 second of dragging an warning apear 
'warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the FixedDataTableColumnReorderHandle component. '
This is the function where the warning appear:
_updateState: function() {
                this._animating && requestAnimationFrame(this._updateState), this.setState({
                    dragDistance: this._distance
                }), this.props.onColumnReorderMove(this._distance);
            }
## Context
I am trying to reorder column in my table,i have more than 30 column on the table

## Your Environment
version :"fixed-data-table-2": "0.7.1",
* Browser Name and version: Chromium 
* Operating System :Ubuntu 12.04

**Comment by KamranAsif** [comment]
@CosminIonascu do you have allowCellsRecycling enabled in your application? 

I'm able to see this bug when thats set to true, but not when its false. Want to make sure this is the actual problem and not a red herring

**Comment by KamranAsif** [comment]
Resolved as part of https://github.com/schrodinger/fixed-data-table-2/pull/40
Try v0.7.2

**Comment by CosminIonascu** [comment]
@KamranAsif yes  I have allowCellsRecycling enabled.
Thank you for the fix.
