### ISSUE TITLE
Fixed bug for grouped columns that have no flexGrow parameter (beta version)

### ISSUE THREAD

**Issue by Invizor** [schrodinger/fixed-data-table-2#401]
Fixed bug for grouped columns that have no flexGrow parameter (beta version)

## Description
If all columns of the table do not have the flex Grow parameter specified, the result is that the column grouping header row may not display correctly.

## Motivation and Context
If you are open example
https://schrodinger.github.io/fixed-data-table-2/example-column-groups.html
and remove all flexGrow parameters, then columGroup row header is empty. Width is set to NaN, and css style is broken.

Screenshots:
https://imgur.com/v7QPKqg

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.

fix this issue at pull https://github.com/schrodinger/fixed-data-table-2/pull/400

**Comment by pradeepnschrodinger** [comment]
Fixed with [v1.0.0-beta.13](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v1.0.0-beta.13)
