### ISSUE TITLE
Scrolling errors in Chrome 73

### ISSUE THREAD

**Issue by KingAtoki** [schrodinger/fixed-data-table-2#407]
When using the table, scrolling inside of the grid produces an error in the console.

```[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312```

Looked around and saw thought that it was due to Chrome making touch events passive by default.

Tried to add `touchAction: none` style to the parent div and also the Table component itself, but the error is still coming up.

## Possible Solution
Seems the problem is the `event.PreventDefault()` on `line 104` in `https://github.com/schrodinger/fixed-data-table-2/blob/master/src/vendor_upstream/dom/ReactWheelHandler.js` is causing the error to come up. Commenting the line out should fix it.

## Environment
Seems to be only on Chrome 73 so far.
Go to http://schrodinger.github.io/fixed-data-table-2/example-touch-scroll.html
Open the console and try scrolling on Table

**Comment by wcjordan** [comment]
Thanks for reporting.  I think your cause analysis is spot on.  Unfortunately removing event.preventDefault would lead to scrolls within the grid also scrolling the parent container as the event bubbles.

One solution would be to move the event listener out of React using the classic addEventListener and removeEventListener APIs.  This is necessary since React puts event listeners on the window object and doesn't support the passive config.  See https://github.com/facebook/react/issues/6436 for more discussion.

Please let me know if you're interested in putting together a PR for this.  Also see #154 for potential other ideas / discussion from when this has come up before.

@pradeepnschrodinger could you keep an eye on this and assist with it?  I think it's pretty important and will likely affect many folks.

**Comment by pradeepnschrodinger** [comment]
@wcjordan, sure. 

> One solution would be to move the event listener out of React using the classic addEventListener and removeEventListener APIs. This is necessary since React puts event listeners on the window object and doesn't support the passive config. See facebook/react#6436 for more discussion.

Maybe we can have a flag that can be passed to FDT, and use this approach, which could fix this temporarily? 
We'll remove this once React fixes the [issue](https://github.com/facebook/react/issues/6436).

**Comment by wcjordan** [comment]
That's one approach we can explore.  I think we need more investigation into the different effects these changes have to know for sure.  I'd particularly like to know how pages where both the table and the page scroll are affected.

Could you carve out a Jira ticket for us to prioritize looking into this in our scrum?  
CC @somavara for heads up

**Comment by jvaill** [comment]
I extracted this change from [KevinYaoooooo's fork](https://github.com/KevinYaoooooo/fixed-data-table-2), see https://github.com/dooly-ai/fixed-data-table-2/commit/bcf563dedd63e77e382b61f0c48368a6121ffdb0.

It seems to work well for our use case - the table fixed to the edges of the viewport, but I haven't tested it in other configurations.

Let me know if you'd like me to open a PR.

**Comment by wcjordan** [comment]
Nice!  Ya, that looks like the right direction to me.  We'd be very interested in a PR.

**Comment by datavisorfrankhe** [comment]
I am eager to see the fix also, right now, this component is throwing hundred of errors whenever user is scrolling up and down. This can be easily seen from the demo page as well.
Thanks

**Comment by wcjordan** [comment]
Please feel free to open a PR if you have the opportunity.

**Comment by datavisorfrankhe** [comment]
PR is already there
https://github.com/dooly-ai/fixed-data-table-2/commit/bcf563dedd63e77e382b61f0c48368a6121ffdb0

waiting it to be accepted

**Comment by wcjordan** [comment]
That's a commit and looks like a reasonable fix.

**Comment by AviralVarshney123** [comment]
@datavisorfrankhe Have you already created the PR ? Your link re-directs to commit version.
Else i can help in creating one.

**Comment by wcjordan** [comment]
We could still use a PR.  Thanks @AviralVarshney123 !
