### ISSUE TITLE
Rename FixedDataTableColumnResizeHandle

### ISSUE THREAD

**Issue by pradeepnschrodinger** [schrodinger/fixed-data-table-2#408]
From the [docs](http://schrodinger.github.io/fixed-data-table-2/codebase.html):
[`FixedDataTableColumnResizeHandle`](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/src/FixedDataTable.js#L679) is the component that renders the **line** displayed while resizing a column.

This is quite confusing as the actual resize handle is defined in `FixedDataTableCell`, under the name [`columnResizerComponent`](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/src/FixedDataTableCell.js#L234) (not defined as a React class)

## Current Behavior
Confusion! Had this while trying to fix #381 

## Possible Solution
Rename!

## Context
No developer shall suffer after this is renamed well.

## Your Environment

* Version used: v1.0.0-beta.12
* Browser Name and version: Chrome (latest)
* Operating System and version (desktop or mobile): Windows 10

**Comment by pradeepnschrodinger** [comment]
@wcjordan, any suggestions?
Mine is just to rename `FixedDataTableColumnResizeHandle` to `FixedDataTableColumnResizerLine`, since the component also uses the classname ["fixedDataTableColumnResizerLine"](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/src/FixedDataTableColumnResizeHandle.js#L126)

**Comment by wcjordan** [comment]
That's sounds like a good name to me.  I'd even consider dropping the Fixed data table prefix for a shorter name.

**Comment by pradeepnschrodinger** [comment]
Fixed with [v1.0.0-beta.13](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v1.0.0-beta.13)
