### ISSUE TITLE
Update peerDependencies to support V15?

### ISSUE THREAD

**Issue by HongJheLi** [schrodinger/fixed-data-table-2#44]
Can you update react version like below?

```
"peerDependencies": {
	"react": "^15.2.1",
	"react-dom": "^15.2.1"
}
```

BTW, I just fork this, and try to install from my repository.
And there is an error in my browser.

```
internal/FixedDataTableRoot.js
	Error: XHR error (404 Not Found) loading
```
I know the file is generated from ```npm run build-npm```, but how can I do after npm install?

**Comment by KamranAsif** [comment]
Can you put up a PR with the proposed changes?
I think we would still need to add >=0.13.0 and >=0.14.0 for react and reactdom respectively 

You shouldn't need to run anything if you are installing it as a dependency.
If you are modifying the library, you need to run `npm run build-dist`

**Comment by HongJheLi** [comment]
1. Because I use react@^15.3.1 in my project, and I see error below.

    > Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner)

    That why I try to upgrade peerDependencies. But I can not run the example since that.
    Dose this project only support >= 0.13 or  >= 0.14?

    Or can you teach me how to solve it. Many thanks

2. I install it from github. That's properly why I miss those files.

**Comment by KamranAsif** [comment]
I don't see that error here: https://jsfiddle.net/f0x7wg90/
We have a minimum supported version, so yes we need those min versions
