### ISSUE TITLE
Accessibility support for a screen reader (i.e. JAWS or Narrator)

### ISSUE THREAD

**Issue by Tanner-MS** [schrodinger/fixed-data-table-2#440]
Accessibility tree should be correct so a screen reader can understand DOM structure. Currently there are no roles set anywhere.
This can be achieved by adding the correct roles and attributes to the elements following the ARIA standard. Here is a link: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Grid_Role

This is needed for users with disabilities to be able to use this control.

**Comment by wcjordan** [comment]
Hey @Tanner-MS, thanks for filing this.  We'd be happy to accept a PR adding this.

**Comment by pradeepnschrodinger** [comment]
Fixed with the [v1.0.0](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v1.0.0) release through #445.
