### ISSUE TITLE
shift+mousewheel no longer scrolling horizontally

### ISSUE THREAD

**Issue by IanVS** [schrodinger/fixed-data-table-2#444]
## Expected Behavior

Holding the `shift` key while scrolling with a mousewheel should cause the list to scroll horizontally.

## Current Behavior

During our upgrade from 0.8.13 to 0.8.23, we found that holding `shift` and using a mousewheel no longer causes the list to scroll horizontally.  

## Possible Solution

From some console.log checks, it seems that `normalizeWheel.js` is sending the correct `spinX` when holding shift, but that some other logic in `ReactWheelHandler.js` swaps it back.  I think that the break happened in https://github.com/schrodinger/fixed-data-table-2/pull/390

## Your Environment

* Version used: 0.8.23
* Browser Name and version: Chrome 74 and Safari
* Operating System and version (desktop or mobile): MacOS
* Link to your project:

**Comment by wcjordan** [comment]
@pradeepnschrodinger  could you investigate this?

**Comment by pradeepnschrodinger** [comment]
@wcjordan, this doesn't seem to be an issue in Windows using Chrome (v74), Firefox, Edge, or IE...

I'm guessing MacOS detects shift and internally swaps the spin. 
And because of the changes in #390, where we explicitly check for the shift key, the axis gets swapped again...

What should be done here? Maybe we should feature flag #390, or detect the browser/OS?

**Comment by wcjordan** [comment]
Detecting the OS sounds like a way to go.  I think you can use `navigator.platform ==="MacIntel"`

If you put up a PR, I can test on my mac a bit later on.

**Comment by pradeepnschrodinger** [comment]
@IanVS, fix released with [v0.8.25](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v0.8.25) and [v1.0.0-beta.19](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v1.0.0-beta.19) through #447.
