### ISSUE TITLE
Warning: Unknown prop `columnKey` on <div> tag.

### ISSUE THREAD

**Issue by FredericHeem** [schrodinger/fixed-data-table-2#45]
The columnKey prop is passed to the underlying children and react now moans about it.

```
Warning: Unknown prop `columnKey` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
```

## Expected Behavior
no warning
## Current Behavior
warning

## Your Environment
React 15.3.1

**Comment by KamranAsif** [comment]
This should have been fixed here https://github.com/schrodinger/fixed-data-table-2/pull/28/files
What version of FDT2 are you using?

**Comment by FredericHeem** [comment]
The last version is being used: `0.7.2`

**Comment by KamranAsif** [comment]
Can you get this reproducible in a jsfiddle? We need more information on the error

**Comment by FredericHeem** [comment]
Before spending some time to isolate the issue, the live examples at http://schrodinger.github.io/fixed-data-table-2/example-object-data.html are using the latest version ?

**Comment by burakcan** [comment]
Can you post full error stack output?

**Comment by FredericHeem** [comment]
```
Warning: Unknown prop `columnKey` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by InvoiceTable)
    in div (created by FixedDataTableCell)
    in FixedDataTableCell (created by FixedDataTableCellGroupImpl)
    in div (created by FixedDataTableCellGroupImpl)
    in FixedDataTableCellGroupImpl (created by FixedDataTableCellGroup)
    in div (created by FixedDataTableCellGroup)
    in FixedDataTableCellGroup (created by FixedDataTableRowImpl)
    in div (created by FixedDataTableRowImpl)
    in div (created by FixedDataTableRowImpl)
    in FixedDataTableRowImpl (created by FixedDataTableRow)
    in div (created by FixedDataTableRow)
    in FixedDataTableRow (created by FixedDataTable)
    in div (created by FixedDataTable)
    in div (created by FixedDataTable)
    in FixedDataTable (created by InvoiceTable)
    in div (created by InvoiceTable)
    in InvoiceTable (created by Unknown)
    in div (created by Unknown)
    in Unknown (created
```

**Comment by KamranAsif** [comment]
```    in div (created by InvoiceTable)```
This is caused by your code, not FDT.

**Comment by josescasanova** [comment]
hey @FredericHeem were you able to solve this issue? I'm running into the same issue and can't seem to find the root cause.

**Comment by FredericHeem** [comment]
I'm glad i'm not the only one, this annoying warning is still there but I haven't had the time to delve into it, it's a warning after all

**Comment by josescasanova** [comment]
@FredericHeem Yep! I removed every instance of `columnKey` in my app and its still happening :(

**Comment by FredericHeem** [comment]
Columnkey is needed to resize and reorder columns so it's needed in my use case.

**Comment by KamranAsif** [comment]
If you can create a jsfiddle reproducing this consistently, please feel free to reopen.

**Comment by wcjordan** [comment]
@FredericHeem I suspect in your InvoiceTable you pass props with the spread operator such as is described [here](https://facebook.github.io/react/docs/transferring-props.html#transferring-with-...-in-jsx).  You'll want to consume the columnKey prop so it is not passed down to the div with other props.

Is that the case?  If not would it be possible to share a bit of the render for InvoiceTable?

@josescasanova could you look at your cell renderer and see if you have anything similar.

You can read a bit more about the warning and solutions others have found in these react issues:
https://github.com/facebook/react/issues/7266
https://github.com/facebook/react/issues/7445
