### ISSUE TITLE
Question: animating height of expanded rows

### ISSUE THREAD

**Issue by dwoznicki** [schrodinger/fixed-data-table-2#457]
In my project, I have tables where expanding/collapsing a row causes a nice slide-down/slide-up effect. If possible, I'd like to port this behavior to my FDT2 tables as well.
Presently, I'm relying on [velocity-react](https://github.com/google-fabric/velocity-react#readme), which in turn uses [window.requestAnimationFrame()](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) to execute the animation. 

I understand this is probably well outside the the scope of FDT2, but if you have any pointers on how to accomplish this/if it's even possible, I'd really appreciate it.

Possibly related: #356

**Comment by pradeepnschrodinger** [comment]
Not sure if this will be straightforward to do...

Each row is [absolutely translated](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/src/FixedDataTableBufferedRows.js#L114), so sliding the expanded row will overlap or get overlapped by the other rows during the animation, unless every other row is also translated...

The actual translation through the DOM is applied at the [row wrapper level](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/src/FixedDataTableRow.js#L462).

And the offsets are calculated at the reducer level at [computeRenderedRows](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/src/reducers/computeRenderedRows.js#L203)

**Comment by dwoznicki** [comment]
Thanks for the information. I'll see how in demand this feature is, but given the cost I may ultimately shelve it.

**Comment by pradeepnschrodinger** [comment]
Sure. I'm closing this issue for now, but feel free to respond if you need any help or have made any progress.
