### ISSUE TITLE
prevent scrolling of the table when scrolling expanded row

### ISSUE THREAD

**Issue by jk171505** [schrodinger/fixed-data-table-2#468]
Is this possible to prevent scrolling of the table while scrolling scrollable div inside expanded row?

**Comment by pradeepnschrodinger** [comment]
Just add a `onWheel` handler to your scrollable div and use [Event.stopPropagation](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation) so that the event doesn't propagate to the table.

One catch to this is that, latest versions of our master branch (or beta) don't use React's scroll events, and instead uses a native DOM event listener at document level.

So if you do use later versions, try using a native wheel listener
```js
class ExpandedRow extends React.Component {
  constructor(props) {
    super(props);
    this.refCallback = this.refCallback.bind(this);
  }

  componentDidMount() {
    this.dom.addEventListener('wheel', this.suppressOnWheel);
  }

  componentWillUnmount() {
    this.dom.removeEventListener('wheel', this.suppressOnWheel);
  }

  refCallback(dom) {
    this.dom = dom;
  }

  suppressOnWheel(event) {
    event.stopPropagation();
  }

  render() {
    return (
      <div ref={this.refCallback}>
        expanded content
      </div>
    );
  }
}
```

**Comment by jk171505** [comment]
I'm trying to use pretty similar idea, but this doesn't work for some reason;
`    rowExpandedGetter = () => {
            <div>
                <div className="command-history-items"
                     onScroll={e => {
                         e.stopPropagation();
                     }}>
                     ...
                </div>
            </div>
        );
    };`

**Comment by pradeepnschrodinger** [comment]
That doesn't work because you used `Event.stopPropagation` through React's event system. 

FDT uses the native addEventListener on `wheel`, so you'll need your scrollable div to listen on the same event type and then stop propagate, as I mentioned above.

**Comment by jk171505** [comment]
That works perfect now, thanks!

**Comment by pradeepnschrodinger** [comment]
Great, glad it worked 😄 
I'm closing this issue, but feel free to continue the conversation if you run into issues.

**Comment by mirko77** [comment]
@pradeepnschrodinger 

I have the reverse problem, i.e when I scroll the outside FixedData Table, the expanded row (which contains another FixedDataTable component with the same number of columns) does not scroll, and viceversa.

I need to scroll both (horizontally) so the columns match...any suggestions?

**Comment by wcjordan** [comment]
You might have luck using onHorizontalScroll and scrollLeft to synchronize the tables' scroll positions.
