### ISSUE TITLE
Provide configurable padding for cells

### ISSUE THREAD

**Issue by alecf** [schrodinger/fixed-data-table-2#47]
Right now FixedDataTableCellDefault provides a hard-coded padding of `8px`. You can workaround this by setting a margin of `-8px` (or some equivalent) but it would be nicer if this were configurable.

## Possible Solution
Probably just pass down via props to `<Cell>` (though I assume this would affect cell height calculation)

## Context
We're trying to provide a very dense table of data and the extra space that `8px` gives you is annoying to workaround.

**Comment by wcjordan** [comment]
That sound reasonable to me.  Any chance you'd like to create a PR?  

The class is specified [here](https://github.com/schrodinger/fixed-data-table-2/blob/5e11477172d0c380838be6449741fd178fc43aba/src/FixedDataTableCellDefault.js#L95) as className={cx('public/fixedDataTableCell/cellContent')}.

**Comment by KamranAsif** [comment]
Padding is only added via the css. You can add
```
.public_fixedDataTableCell_cellContent {
  padding: 0px;
}
```

to your css.
Example: https://jsfiddle.net/f0x7wg90/

**Comment by alecf** [comment]
I was considering submitting a PR, I just think adding a global CSS rule to your app as a way around this seems.. like the wrong way to handle this.

**Comment by KamranAsif** [comment]
Yeah its not ideal, but this library absolutely requires the css file also be included. 
This is what happens when you don't: https://jsfiddle.net/gpuz7dL8/

**Comment by KamranAsif** [comment]
Sorry, closed this issue prematurely. If you want to put a PR that allows you to override the padding or the cellContent class, please go for it!

**Comment by KamranAsif** [comment]
@alecf Would you be able to put up that PR?

**Comment by alecf** [comment]
I'll see what I can do. 

My inclination is towards inline styles here though - i.e. moving the 8px out of the stylesheet and into `FixedDataTableCellDefault.js` - but that's fairly different than the current styling of the rest of the table. Any recommendations before I dive in? I just want to make sure I take the right approach before I put together a PR. How likely is it that this project will go down the Aphrodite route? (as mentioned in #51, cross-referencing this issue)

**Comment by wcjordan** [comment]
It looks like the Aphrodite approach in the cross referenced issue doesn't require any changes to FDT.  Could you try that approach in your application (I intend to create and commit an example of it over the next week)?

If you have any concerns with that approach, please list them in the cross referenced thread.  For now I'm going to close this issue and recommend the Aphrodite approach.
