### ISSUE TITLE
How to handle column according to response data ?

### ISSUE THREAD

**Issue by Wan-YunPeng** [schrodinger/fixed-data-table-2#477]
## Expected Behavior

Get column information from server-side, not hard code it
## Current Behavior

Hard code very column information while coding, which means if you have a thousand different table to show, you have to write a thousand table column information.
## Possible Solution

Pass column information like data.
## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by pradeepnschrodinger** [comment]
Yea this is possible. FDT parses column data through FDT's Column component, which is passed as children to the Table component.

So this means you just need to generate the Column component. Something like:
```
columns = [];

const cellRenderer = ({ columnKey, rowIndex }) => (<div> {rowIndex}, {columnKey} </div>);

for (let i = 0; i < 100; i++) {
  columns[i] = (
	<Column
	  key={i}
	  columnKey={i}
	  header={<div> {i} </div>}
	  cell={cellRenderer}
	  width={100}
	  allowCellsRecycling={true}
	/>
  )
}
``` 
and then pass `columns` to the table as the child component:
```
<Table
  {...tableProps}
>
 {columns}
</Table>
```

You can see similar approach in some of our examples, like the [AutoScrollExample](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/examples/AutoScrollExample.js#L117).

**Comment by pradeepnschrodinger** [comment]
We do have a long term plan to have an alternate API that allows the user to pass in raw data, instead of React components for the columns. See #464.

For now the API is not decided, and there's no timeline decided... but we'll probably be looking into it after v1 is released.

**Comment by Wan-YunPeng** [comment]
@pradeepnschrodinger thanks. Adding column as children works for me.

**Comment by pradeepnschrodinger** [comment]
Cool. I'll close the issue, but feel free to continue the discussion here if needed.
