### ISSUE TITLE
How to create infinite scroll (request new data after Y scrolling reached the bottom bar)

### ISSUE THREAD

**Issue by izzuddinraffar** [schrodinger/fixed-data-table-2#488]
**Hi, I'm stuck on creating an infinite scroll to request new data.  I've studied the issue and found the solution using onScrollEnd. But I don't know to get the last bottom scrolling height or row index to create the argument/ condition. So, how to create the argument/ condition on onScrollEnd?**

**The table**
`<Table
                    rowsCount={this.props.redux.vouchers.length}
                    rowHeight={60}
                    headerHeight={32}
                    width={tableWidth}
                    height={tableHeight}
                    footerHeight={45}
                    onScrollEnd={(_, num, endRowIndex) => { this.onScrollEndRequest(num, endRowIndex); return true; }}      
 />`

**The function**
` onScrollEndRequest(num, endRowIndex) {
        if(a==b){
        //request new data
       }
    }`

**Comment by pradeepnschrodinger** [comment]
Is your question on how we can detect if the user has scrolled all the way to the end? 
If so, just make use of the `endRowIndex` parameter provided by onScrollEnd.

> onScrollEnd(scrollX, scrollY, firstRowIndex, endRowIndex);

`onScrollEnd` is called at the end of any scroll with 4 parameters (see usage [here](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/src/FixedDataTable.js#L1154))

**Comment by izzuddinraffar** [comment]
> 
> 
> Is your question on how we can detect if the user has scrolled all the way to the end?
> If so, just make use of the `endRowIndex` parameter provided by onScrollEnd.
> 
> `onScrollEnd` is called at the end of any scroll with 4 parameters (see usage [here](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/src/FixedDataTable.js#L1154))
> 
> > onScrollEnd(scrollX, scrollY, firstRowIndex, endRowIndex);
Yup..
Thanks for the reference, I'm almost be done but my  "fixed-data-table-2": "^0.8.28" and just have 3 params:
`if (this.props.onScrollEnd) {
      this.props.onScrollEnd(this.state.scrollX, this.state.scrollY, this.state.firstRowIndex);
    }`

How to upgrade to v1.0 because of the official v 0.8.28 only?

**Comment by pradeepnschrodinger** [comment]
Ah right, only the beta branch has it, and we are almost done releasing it.

For now you can just use the latest beta, which is `v1.0.0-beta.30`. This should solve the issue.

**Comment by izzuddinraffar** [comment]
> 
> 
> Ah right, only the beta branch has it, and we are almost done releasing it.
> 
> For now you can just use the latest beta, which is `v1.0.0-beta.30`. This should solve the issue.

Thanks, that all is working fine...
