### ISSUE TITLE
Update issue template (codepen link)

### ISSUE THREAD

**Issue by pradeepnschrodinger** [schrodinger/fixed-data-table-2#489]
## Expected Behavior

New users using the issue template will see a "Steps to Reproduce..." section which has a CodePen. The CodePen must be simple and working for the user to provide a reproducable example.

## Current Behavior

The current codepen link doesn't work: https://codepen.io/alphalpha/pen/oqKJgG

## Possible Solution

Updated CodePen (better to have a new link).

## Steps to Reproduce (for bugs)

See the current [CodePen](https://codepen.io/alphalpha/pen/oqKJgG)

## What's to be done here
* Provide a new CodePen (maybe even simplify some stuff)
* Investigate why the current one failed.

**Comment by wcjordan** [comment]
This may provide a reasonable starting point:
https://codesandbox.io/s/react-playground-y6zof

**Comment by wcjordan** [comment]
This is done w/ #565
