### ISSUE TITLE
Space is only reserved for last column border when vertical scrollbar is shown

### ISSUE THREAD

**Issue by brandon-hass** [schrodinger/fixed-data-table-2#495]
## Expected Behavior
It seems like space for the right border of the last column should be reserved whether the vertical scrollbar is shown or not.

## Current Behavior
Currently, when the vertical scrollbar is visible, 1px is reserved for the last column's right border, however this is not the case when the vertical scrollbar is not visible.

This leads to a lack of consistency around widths and styling depending on whether or not the vertical scrollbar is shown.

## Possible Solution
https://github.com/schrodinger/fixed-data-table-2/blob/dd871d8b64b1e09cfd50723992085b4725f9cc2c/src/selectors/columnWidths.js#L44-L45

Could be changed to:
```diff
-  const scrollbarSpace = scrollEnabledY ? Scrollbar.SIZE + Scrollbar.OFFSET : 0;
-  const viewportWidth = width - scrollbarSpace;
+  const scrollbarSpace = scrollEnabledY ? Scrollbar.SIZE : 0;
+  const viewportWidth = width - scrollbarSpace - 1; // Reserve space for last column border
```
Similarly:
https://github.com/schrodinger/fixed-data-table-2/blob/dd871d8b64b1e09cfd50723992085b4725f9cc2c/src/selectors/roughHeights.js#L138-L143

Could be:
```diff
+  const adjustedWidth = width - 1; // Reserve space for last column border
+
   if (overflowX === 'hidden' || showScrollbarX === false) {
     return ScrollbarState.HIDDEN;
-  } else if (minColWidth > width) {
+  } else if (minColWidth > adjustedWidth) {
     return ScrollbarState.VISIBLE;
   }
 
-  const scrollbarSpace = Scrollbar.SIZE + Scrollbar.OFFSET;
-  if (minColWidth > width - scrollbarSpace) {
+  if (minColWidth > adjustedWidth - Scrollbar.SIZE) {
```

## Steps to Reproduce (for bugs)
https://codesandbox.io/embed/confident-hofstadter-qp2nn?fontsize=14

Styling has been added to clarify the issue.

- Notice that in the top table, the width is 400 and each column is width 200. The right border of the last column is not visible and does not cause the horizontal scrollbar to appear.
- Notice that in the bottom table, the width is 415 (200 + 200 + 15 for the scrollbar) and the horizontal scrollbar appears to account for the right border of the last column (by using Scrollbar.OFFSET)

**Comment by pradeepnschrodinger** [comment]
Thanks for the detailed sandbox. 

Are there two fixes here? First one being that the vertical scrollbar, whether present or not, should not change the overall width of the table? And the second one being the extra 1px which is not expected when the vertical scrollbar is present?

This seems reasonable, could you open up a pull request?

**Comment by brandon-hass** [comment]
@pradeepnschrodinger 

> Are there two fixes here? First one being that the vertical scrollbar, whether present or not, should not change the overall width of the table? And the second one being the extra 1px which is not expected when the vertical scrollbar is present?

Not exactly. The vertical scrollbar's presence doesn't affect the overall width of the table currently, so that doesn't seem to be an issue. Here's the problem as I see it:

Since `.fixedDataTableLayout_main` has `box-sizing: border-box` as well as a 1px border, the available width for the content will be 2px less than the width of the table (total width - left and right borders). However for styling purposes, cells in the last column purposely overlap with whatever is on their right border, so the available content width is actually 1px less than the total table width. This is currently only accounted for if the scrollbar is visible and the proposed changes account for it regardless of scrollbar visibility.

I do think that this could be potentially confusing from a consumer perspective, though, since to avoid a horizontal scrollbar, the table width must always be 1px more than the content width. This change only affects the cases when the vertical scrollbar is not visible since it is already like that if the scrollbar is visible.

Current behavior:
- Table width: 100px, column width: 100px, no vertical scrollbar
Horizontal scrollbar is not visible even though the content is larger than the available width of 99px

- Table width: 115px, column width: 100px, vertical scrollbar showing
Horizontal scrollbar is visible since the extra 1px is accounted for

Proposed change:
- Table width: 100px, column width: 100px, no vertical scrollbar
Horizontal scrollbar is visible since the extra 1px is accounted for

- Table width: 115px, column width: 100px, vertical scrollbar showing
No change from current behavior, horizontal scrollbar is visible since the extra 1px is accounted for

Let me know if that makes sense. If this still seems reasonable I can open a PR.

**Comment by pradeepnschrodinger** [comment]
> Not exactly. The vertical scrollbar's presence doesn't affect the overall width of the table currently, so that doesn't seem to be an issue.:

From the sandbox, what I'm seeing is that the table container (which includes the scrollbars) does not respect table width since the vertical scrollbar takes an extra 15px. 
The table height is correct, however, and the horizontal scrollbar doesn't change the height.

I think the `width` and `height` props should define the table **container** dimensions, or atleast we should make the behavior consistent for both axes. @wcjordan, what's your opinion?

> I do think that this could be potentially confusing from a consumer perspective, though, since to avoid a horizontal scrollbar, the table width must always be 1px more than the content width. This change only affects the cases when the vertical scrollbar is not visible since it is already like that if the scrollbar is visible.

Yea, this needs to be fixed too. Please open up the PR.
Thanks for the detailed response again 😄.

**Comment by wcjordan** [comment]
I agree that width & height should be the container dimensions.  It sounds like that's the case now.  We just don't account for styling / borders when determining if the content size fits.  The suggested fix seems reasonable to me.

I wonder if we'll see issues where users have custom CSS and different sized borders...  but that's probably a concern for the future.

**Comment by brandon-hass** [comment]
@pradeepnschrodinger 
> From the sandbox, what I'm seeing is that the table container (which includes the scrollbars) does not respect table width since the vertical scrollbar takes an extra 15px.

In the sandbox, I explicitly set the table width to be 415 for the lower table to account for the scrollbar. Sorry if that was causing any confusion.

@wcjordan I wondered about different size borders and I agree that's probably a future concern...

I'll get the PR set up for this change.

**Comment by pradeepnschrodinger** [comment]
> I agree that width & height should be the container dimensions. It sounds like that's the case now. 

I rendered  2 tables with height and width as 200px, 400px respectively.
This is how it looks
![image](https://user-images.githubusercontent.com/41563608/67407023-7f5a3180-f5d4-11e9-90b2-5b62a0863467.png)

The container with the scrollbar (second one) has more width due to the scrollbar. This is the first point I mentioned. The height is still 200px, as it should be.
![image](https://user-images.githubusercontent.com/41563608/67407084-9b5dd300-f5d4-11e9-837c-8c58475d6079.png)

> I wonder if we'll see issues where users have custom CSS and different sized borders... but that's probably a concern for the future.

Agreed, probably worth waiting for someone to file an issue, or we tackle it as part of v2.

**Comment by pradeepnschrodinger** [comment]
> In the sandbox, I explicitly set the table width to be 415 for the lower table to account for the scrollbar. Sorry if that was causing any confusion.

Ah my bad. I thought both were 415.

**Comment by wcjordan** [comment]
I'm going to close this due to inactivity. Please let me know if there's more details here which might make us reconsider. Thanks
