### ISSUE TITLE
Touch scrolling

### ISSUE THREAD

**Issue by gemedet** [schrodinger/fixed-data-table-2#5]
Thanks for starting this repo! Any plans to support touch scrolling natively? This was a common question in the original issue tracker.

For reference:
facebook/fixed-data-table#403
facebook/fixed-data-table#365
facebook/fixed-data-table#26

**Comment by wcjordan** [comment]
Kam and I are looking at adapting the code [here](https://github.com/facebook/fixed-data-table/issues/365) and [here](https://github.com/facebook/fixed-data-table/blob/master/site/examples/TouchableArea.js) to provide another scrolling handler similar to ReactWheelHandler.

The major challenge for us will be validating that the solution works on different devices and setups.  Particularly the cases mentioned of plugging a touchscreen laptop into an external monitor with a mouse may be challenging.

As such, we'll try to release a beta solution sometime this week which only enables the functionality if a flag is passed in as a prop.  We can then address any issues based on feedback.  Thanks for reporting!

**Comment by KamranAsif** [comment]
Have some basic functionality up behind a flag, as well as an example. 
Would appreciate it if you could checkout the PR and test it for your use case :)

**Comment by gemedet** [comment]
Awesome, that was fast!

It seems to work when I start dragging, but if I move my finger to the side it'll stop scrolling vertically. I have the table width fit inside the window, so `handleScrollX` always comes back false.

**Comment by mahmoudfelfel** [comment]
Thanks for working on this,
I have a similar issue, can't scroll on mobile devices, is there any updates ?

**Comment by wcjordan** [comment]
Hey @mahmoudfelfel, we have a PR up [here](https://github.com/schrodinger/fixed-data-table-2/pull/7) which enables touch scrolling when a touchScrollEnabled={true} prop is passed into the table.  Feel free to check it out and let us know if you find any issues with it.

Right now we're trying to resolve issues related to scroll stopping when your finger leaves the table and adding scroll deceleration so the scroll doesn't stop immediately when you remove your finger.  I hope to have a more detailed update to you later this week.

**Comment by mahmoudfelfel** [comment]
@wcjordan thanks for your reply, and certainly will check the PR, test it, and give my feedback and will add comments on the PR for any issues i find.

**Comment by wcjordan** [comment]
I've added some momentum scrolling when drag is released and some tuning to make scroll smooth here: https://github.com/wcjordan/fixed-data-table-2/commit/bffbf895157f425632d797fac809465a981cc815

I'll integrate it with Kam's open PR when I have a chance to sync with him.

**Comment by wcjordan** [comment]
We've merged this issue in and will release behind a flag as part of 0.6.6 shortly.  I'll close for now, but please try it out and open new issues for any instability or lack of smoothness you find.

**Comment by weixing2014** [comment]
@wcjordan Hi, do we have any plan to support touch scrolling natively on touchscreen PCs? It seems for the time being Fixed-data-table-2 can only be scrollable in Chrome on touchscreen PCs. Thanks!

**Comment by wcjordan** [comment]
I'd be open to PRs but don't want to get to into the thick of figuring out support for browsers which haven't implemented the [Touch Events API](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events).  You're welcome to experiment with the binding [here](https://github.com/schrodinger/fixed-data-table-2/blob/master/src/FixedDataTable.js#L626).  If you find something that works, feel free to extract the logic into a component and submit a PR.

**Comment by weixing2014** [comment]
Thanks, @wcjordan ! This is very helpful.
