### ISSUE TITLE
After updating the version to 1.0.1, an exception occurred. The error message is as follows: Invariant Violation: Index out of range NaN

### ISSUE THREAD

**Issue by jeffycai** [schrodinger/fixed-data-table-2#501]
After updating the version to 1.0.1, an exception occurred. The error message is as follows: Invariant Violation: Index out of range NaN

Stack:
Function defaultMemoize(func) {
   Var equalityCheck = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : defaultEqualityCheck;

   Var lastArgs = null;
   Var lastResult = null;
   // we reference arguments instead of spreading them for performance reasons
   Return function () {
     If (!areArgumentsShallowlyEqual(equalityCheck, lastArgs, arguments)) {
       // apply arguments instead of spreading for performance.
       lastResult = func.apply(null, arguments);
     }

     lastArgs = arguments;
     Return lastResult;
   };
}

The result of lastResult is as follows:
bufferRowCount: NaN
maxAvailableHeight: NaN
minAvailableHeight: NaN
reservedHeight: NaN

**Comment by pradeepnschrodinger** [comment]
> After updating the version to 1.0.1

Hey thanks for reporting. Which version did you update from?

Also could you post the code snippet that renders the table, along with the value of the props?
Alternatively It would be really helpful if you could put a codesandbox link reproducing this issue.

Having more information would help us narrow down the cause.

**Comment by jeffycai** [comment]
@pradeepnschrodinger My current version is 0.8.26，thanks

**Comment by pradeepnschrodinger** [comment]
@jeffycai , can you check if the table was passed an invalid height value?

You should make sure `height` is defined and is a valid number at every render.

**Comment by wcjordan** [comment]
Any update here @jeffycai ?

**Comment by jeffycai** [comment]
It's my problem, footerheight is null .That's what's causing this problem.
