### ISSUE TITLE
Is there a support for Angular 7 ?

### ISSUE THREAD

**Issue by vmagesh** [schrodinger/fixed-data-table-2#503]
I want to implement this datatable in my angular app is there any documentation available ?

**Comment by vmagesh** [comment]
I want to implement this in my angular app is there any documentation available

**Comment by pradeepnschrodinger** [comment]
We don't have an angular port.

But for now you could just use the react version instead. It should work as long as you render the table using `RenderDOM.render`.

Maybe this [repo](https://github.com/Gethyl/AngularJsWithReact/blob/master/src/angular/reactDirective.js) will give you an idea.
