### ISSUE TITLE
Document scrolls while the table is scrolled

### ISSUE THREAD

**Issue by jk171505** [schrodinger/fixed-data-table-2#504]
Is this possible to prevent document scroll while scrolling the table?
## Expected Behavior
Document doesn't scroll while the table is being scrolled

## Current Behavior
Document is scrolled while the table is being scrolled

## Steps to Reproduce (for bugs)
The page should be taller than the viewport, so it's possible to scroll it. It should contain a div that smaller than the viewport, so the height of the table is smaller than the height of the viewport.
video of the problem: https://d.pr/v/EAkRtM

**Comment by pradeepnschrodinger** [comment]
Can you try the table prop `stopScrollPropagation` set to `false`?
This should prevent the case where both the table and the container scrolls together.

**Comment by jk171505** [comment]
Tried this already, doesn't work. Problem reported in related PR:
https://github.com/schrodinger/fixed-data-table-2/pull/150

I also tried to set `overflow` to `hidden` on document.body in `onScrollStart`, but this takes a split of a second, so eventually the page is scrolled about 150px untill the scroll of the page is locked.

**Comment by pradeepnschrodinger** [comment]
@jk171505 , oops I made a mistake in the last update. 
You should set the table prop `stopScrollPropagation` to **`true`**.

If that doesn't solve it, could you also try setting `stopScrollDefaultHandling` set to `true`?

**Comment by jk171505** [comment]
Like I said, I already tried `stopScrollPropagation` - doesn't work. The same with `stopScrollDefaultHandling`.

**Comment by pradeepnschrodinger** [comment]
That's bad... It works fine on my machine (Windows 10, Chrome) that runs the latest FDT (`v1.0.2`).

Could you give the same info? (browser version, operating system version, and FDT version)

**Comment by jk171505** [comment]
Mac os x 10.15.14, chrome 78.0.3904.108, FDT 0.8.6
video from my environment: https://d.pr/v/Bl37dv

**Comment by pradeepnschrodinger** [comment]
Thanks for the info. The version you're using (`0.8.6`) is very old, and was released 2 years ago. 
The table in it doesn't support `stopScrollDefaultHandling`. Also the scroll handlers are registered through React which made similar issues like #154 and #419 hard to fix.

AFAIK, these issues should've been fixed in v1. So could you upgrade to the [latest version](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v1.0.2) and try the solutions again?

**Comment by jk171505** [comment]
Thanks, the update solved the issue.
