### ISSUE TITLE
Expanded rows example: Closing the last row creates a section of whitespace

### ISSUE THREAD

**Issue by ivanmontiel-lw** [schrodinger/fixed-data-table-2#510]
On Expanded rows example, closing the last row after expanding it causes a visual bug where the top row disappears. Scrolling will fix it.

## Expected Behavior
1. Click on the last item will open the content
2. Click on the last item will close the content
3. The rows are collapsed and visible.

## Current Behavior

* The top row of the table is blank.

## Possible Solution
* This looks like something is not triggering a re-calculation for which rows are visible after collapsing a row.

## Steps to Reproduce (for bugs)
1. Go to [example expanded rows](https://schrodinger.github.io/fixed-data-table-2/example-expanded-rows.html).
2. Go to last item and click expand.
3. Un-expand the last item

<img width="1433" alt="Screen Shot 2020-01-30 at 3 59 25 PM" src="https://user-images.githubusercontent.com/57112622/73500791-e8de9e80-4380-11ea-941f-a5dd8860189e.png">

## Context

We had this issue come up when using the fixed-data-table-2 with expanded rows and were able to reproduce it in the example code.

## Your Environment

* Version used: Example
* Browser Name and version: Google Chrome 79.0.3945.130 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Desktop
* Link to your project: [example](https://schrodinger.github.io/fixed-data-table-2/example-expanded-rows.html).

**Comment by wcjordan** [comment]
@ivanmontiel-lw thanks for reporting this and apologies for our delay responding.  

It looks like this is a short coming in how we account for the scroll position when row heights are changing dynamically.  In this case we anchor the scroll based on the current first row and then update all the row heights around it to ensure they are up to date (see [computeRenderedRows](https://github.com/schrodinger/fixed-data-table-2/blob/master/src/reducers/computeRenderedRows.js#L35)).  This makes a bad assumption that there will be enough scroll content to fill the available space.

I've opened PR #511 to address the issue.

**Comment by wcjordan** [comment]
Fixed via #511 
Will be released w/ v1.1

**Comment by wcjordan** [comment]
This is now released w/ v1.1.
