### ISSUE TITLE
Replace `hasteResolvers` with relative imports

### ISSUE THREAD

**Issue by boxfoot** [schrodinger/fixed-data-table-2#513]
This project uses a custom "hasteResolver" defined in `build_helpers\resolvers.js` to allow simplified imports like `import FixedDataTableStore from 'FixedDataTableStore';` instead of relative imports like `import FixedDataTableStore from './FixedDataTableStore';`

While this works, as a newcomer to the project I found it unintuitive and confusing.   Also, my IDE can't understand the webpack resolution behavior, and is constantly warning me that it can't find these modules.

I'm curious about the decision not to use relative imports, and am wondering whether you'd be open to a PR to remove the custom resolver in favor of relative imports.

**Comment by wcjordan** [comment]
I'd be open to a fix to use relative imports.  It was this way when forked from FBook, but I agree, it's not as good as following the JS standards of relative imports.  @pradeepnschrodinger  do you have any concerns?

**Comment by pradeepnschrodinger** [comment]
Nope, relative imports sounds good.
Also how good/bad are absolute imports (which we use in LD) in comparison to relative? 
I find absolute imports easier to copy and paste, and sometimes also to read. But besides that, I'm fine with both.

**Comment by wcjordan** [comment]
Could you send an email to Joe M w/ me CC'd about LD.  I think we should discuss there rather than here.

**Comment by pradeepnschrodinger** [comment]
Hi @boxfoot ,
We're open to your suggestion to not use the haste resolver, and instead make use of relative/absolute imports everywhere. 
Do you have a PR in mind?
