### ISSUE TITLE
IDs for testing

### ISSUE THREAD

**Issue by Andrii-A** [schrodinger/fixed-data-table-2#514]
## Expected Behavior
Each table row has it's own data-id for testing purpose.
Each cell in the row has it's own data-id for testing purpose.

## Current Behavior
The table produces pretty complicated layout and it's hard to test it without specific hooks.
Currently I need to do something like `cy.get('[data-attr-id="my-table"] > div > div > div:nth-child(3) > div')` to access table rows with Cypress. To access the cell in the table to check it's value, the path will be twice longer.

## Possible Solution
To add to each table row something like `data-id="fixed-data-table-row-${idx}"`.
To add to each row cell something like `data-id="fixed-data-row-cell-${idx}"`.

**Comment by wcjordan** [comment]
I'd be fine w/ a PR for this.  Any concerns from your end @pradeepnschrodinger ?

**Comment by pradeepnschrodinger** [comment]
No concerns, this sounds good.

FWIW, we set aria attributes for the rows at [`<FixedDataTableRowImpl/>`](https://github.com/schrodinger/fixed-data-table-2/blob/master/src/FixedDataTableRow.js#L296). I recommend showing actual row index at the same DOM level.
And for cells, it might be helpful to store both column id and row id, probably around [here](https://github.com/schrodinger/fixed-data-table-2/blob/master/src/FixedDataTableCell.js#L309).

**Comment by vcardins** [comment]
Hey guys, any progress on this issue?

**Comment by wcjordan** [comment]
@Andrii-A is this something you're working on or is it dormant?

**Comment by Andrii-A** [comment]
Well, it was more like a feature request... Sorry for not making it clear.
Unfortunately now I don't really have capacity to contribute myself.

**Comment by wcjordan** [comment]
Cool, no worries.  Sounds like this is dormant, @vcardins

**Comment by pradeepnschrodinger** [comment]
@vcardins, nice catch.

For more info, `rowAttributesGetter` was added along with `gridAttributesGetter` through #491, but only the latter prop was documented. 
We'll just need to add it in FixedDataTable's prop types to have it included in the docs.

**Comment by vcardins** [comment]
@pradeepnschrodinger Thanks for the prompt response.  How soon should we expect an update?

**Comment by pradeepnschrodinger** [comment]
@vcardins , I put a PR #580 for adding the docs, which is in turn blocked by #581.

I'll give it a couple more days to have it merged.

**Comment by pradeepnschrodinger** [comment]
Added docs for `rowAttributesGetter` through #580, and released it with [v1.1.3](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v1.1.3).

The new docs should appear as part of the [Table API](http://schrodinger.github.io/fixed-data-table-2/api-table.html).
