### ISSUE TITLE
can we add space between each row?

### ISSUE THREAD

**Issue by datavisorfrankhe** [schrodinger/fixed-data-table-2#515]
Hello,
We have a requirement to add space between each row, and also, remove the border completely. Making it look like the list, not the data table.
May I ask what will be the best approach to meet this requirement?
I tried to add margin to the row wrapper, but useless. I saw the row position is absolutely, just adding margin is useless here.

Thanls

**Comment by wcjordan** [comment]
Unfortunately, we don't have the best solutions for custom styling the table.  Some ideas & challenges are tracked under #60 & #61, please feel free to add your use case and any suggestions there.

A couple ideas to try for the space between rows would be:
1) Try making your row height larger than necessary (row height + empty space height) and then have the individual cell renderers only render content into the row height space, leaving the empty space blank.
2) Try using the subRowHeightGetter & rowExpanded props to add a sub row as the spacer between rows. (see the [Expanded Rows example](http://schrodinger.github.io/fixed-data-table-2/example-expanded-rows.html)).

I'm going to close this issue so we can consolidate the discussion under issues #60 & #61.  But feel free to continue to post here if you have any questions and I'll answer the best I can.  Also if you do get something working, a PR with an example would be great.  It would also ensure we don't break your workaround when we go to address #60 & #61.
