### ISSUE TITLE
Missing rows when filtering from the bottom of the table

### ISSUE THREAD

**Issue by johleander** [schrodinger/fixed-data-table-2#521]
## Expected Behavior
All rows within the viewport should be visible 

## Current Behavior
Some rows are not visible and the viewport show only a subset of items. 

## Steps to Reproduce (for bugs)
 1. Scroll to the bottom (in Client-side Filter example)
 2. Enter a filter query returning more data than could be shown within viewport (= scrollbar visible)
3. Rows that should be visible are not visible. Changing the scrollbar position re-renders the items correctly. 

## Your Environment
* Online example (Client-side Filter) and locally with React v16.12, FDT v1.0.2
* Browsers: Latest versions of: Firefox, Chrome & Edge. 

![missing-rows](https://user-images.githubusercontent.com/18050951/78131503-78550c00-741b-11ea-9d03-68fe6cd6fa85.jpg)

**Comment by johleander** [comment]
Thank you. 
I had some trouble reproducing it as well, but I assume the example uses randomized name. So the filter string in the screenshot might not give enough items for the problem to occur each time. 

It certainly looks related to #510. I´ll try it on the master. 
Is there any time estimation regarding the 1.1 version btw?

**Comment by wcjordan** [comment]
It should be sometime in the next couple weeks.  Right now we're just adding [react-lifecycles-compat](https://github.com/reactjs/react-lifecycles-compat).  To maintain support for older React versions while updating all our lifecycle methods.  Once that's working, we'll release.

**Comment by norayr93** [comment]
I am having the same issue, nay news on it?

**Comment by wcjordan** [comment]
We're still not able to reproduce this issue.  I don't know if anyone who can reproduce it has tried using the latest master yet.

**Comment by wcjordan** [comment]
v1.1 is now released

**Comment by wcjordan** [comment]
Has anyone been able to reproduce this w/ v1.1 @norayr93 @johleander ?

**Comment by norayr93** [comment]
@wcjordan Current version has solved my problem

**Comment by wcjordan** [comment]
Excellent, glad to hear!
