### ISSUE TITLE
Print issue on Firefox browser 67 version

### ISSUE THREAD

**Issue by nani1232** [schrodinger/fixed-data-table-2#529]
I am having an issue while printing the table in Firefox 67 version browser and it’s missing few rows while printing the page. Let’s say if I have 54 rows and it prints only 52 rows. 
FYI, it happens only on that version browser or below 67 version. 
Does anyone can suggest anything, regards to this?

**Comment by wcjordan** [comment]
I don't have much in the way of useful help, but we did recently fix a version where some rows wouldn't show after scrolling to the bottom of the table and changing the rows (#510, #511).  We may be able to help further if you can create an example reproduction, but I don't have access to a version of Firefox that old.  Is there a reason to rely on an older version of Firefox?

**Comment by nani1232** [comment]
Yes there are certain users which are using that older versions and as of I know that we are still supporting the version until 57 of Firefox and below that we are no longer providing support. So,this problem is affecting only the lower versions under 67 of Firefox browser and the issues which you pointed out didn’t help much. Any other ways that I can use? To resolve this

**Comment by wcjordan** [comment]
Unfortunately I don't have much more to suggest beyond upgrading FDT to the latest version and trying to create an example demonstrating the issue.

I'm going to close this issue for now, but happy to help with any follow ups you have.
