### ISSUE TITLE
OnScrollStart/OnScrollEnd/OnHorizontalScroll not called on scrollLeft prop changes

### ISSUE THREAD

**Issue by veej** [schrodinger/fixed-data-table-2#53]
## Expected Behavior
When changing `scrollTop` prop, onScrollStart/onScrollEnd functions are called as expected.
The same should happen when passing `scrollLeft` prop.

## Current Behavior
Passing a different `scrollLeft` prop value, `onScroll*` callbacks are not called.

## Steps to Reproduce (for bugs)
- [JSFiddle](https://jsfiddle.net/q3zwssoe/5/)
- In the example above, `scrollTop` value is incremented every second. When the value exceeds the max available value, `onScrollEnd` will adjust the state variable with the max scroll position.
- changing line 60 (replace `scrollTop` with `scrollLeft`) and line 41 (replace `y` with `x`), the value will continue to grow and grow, exceeding the max available value for horizontal scrolling (`onScrollEnd` is never called and state variable is never adjusted)

## Context
I'm trying to control the scroll using keyboard arrows, saving the scroll state and passing the stored `scrollTop` and `scrollLeft` to the table at each render.
When trying to pass a `scrollTop` value greater then the max allowed value, the table will scroll to the max and `onScrollEnd` will return the right scroll value, allowing me to revise my saved state with the correct max value, with no need to pre-calculate the max allowed value myself. 

The same thing doesn't happen with `scrollLeft`, so my state variable will continue to grow over the max allowed value with no chance to revise it when it exceeds the max value. 

## Your Environment
* Version used: 0.7.2
* Browser Name and version: Chrome 53
* Operating System and version (desktop or mobile): Mac OS X El Capitan

**Comment by KamranAsif** [comment]
I don't think this is a bug. 

onScrollEnd/onScrollStart returns fn(x, y, rowIndex);
Your example is using the Y position instead of the X position.

Here is a working fiddle: https://jsfiddle.net/mn2rvc7c/

**Comment by veej** [comment]
@KamranAsif, the example I linked is working fine as it shows the desired behavior. The issue is related to the horizontal scrolling. Try to replace `scrollTop` prop with `scrollLeft`, and every `y` in `onScrollEnd` with `x` in your fiddle, and you'll see that with horizontal scrolling, the value will grow endlessly.

Look at this fiddle instead: [](https://jsfiddle.net/543rkdpx/)

**Comment by KamranAsif** [comment]
@veej Spoke too soon! I misread your bug description sorry. 

Put up a PR https://github.com/schrodinger/fixed-data-table-2/pull/54
Fixed fiddle: https://jsfiddle.net/nprp19me/

**Comment by veej** [comment]
well done!
looks 👍

**Comment by KamranAsif** [comment]
Published 0.7.4 https://github.com/schrodinger/fixed-data-table-2/releases/tag/v0.7.4
