### ISSUE TITLE
Scroll nested in Scroll，the inside effect the outside

### ISSUE THREAD

**Issue by iRebel** [schrodinger/fixed-data-table-2#532]
The fixedDataTable container has a vertical scroll，and the fixedDataTable has a vertical scroll too.
when i scoll the fixedDataTable in vertical, the fixedDataTable container scroll too.

## Expected Behavior

when i scoll the fixedDataTable in vertical, the fixedDataTable container is not effected.

## Current Behavior

the fixedDataTable container will scroll too.

## Steps to Reproduce (for bugs)

* Version used:  "fixed-data-table-2": "^0.8.6"
* Browser Name and version: chrome  81.0.4044.138
* Operating System and version (desktop or mobile):   mac os desktop
* Link to your project:

**Comment by pradeepnschrodinger** [comment]
Seems like you're using an old version of FDT; could you try updating to the latest and see if the issue still exists?

You could also make use of the [following props](https://github.com/schrodinger/fixed-data-table-2/blob/master/src/FixedDataTable.js#L340):

> 
> `stopReactWheelPropagation`: If enabled scroll events will not be propagated outside of the table.
> 
> `stopScrollDefaultHandling`: If enabled scroll events will never be bubbled to the browser default handler. If disabled (default when unspecified), scroll events will be bubbled up if the scroll doesn't lead to a change in scroll offsets, which is preferable if you like the page/container to scroll up when the table is already scrolled up max.

**Comment by iRebel** [comment]
yeah，it's version. I updated it and done
