### ISSUE TITLE
Column pure rendering with resize issue

### ISSUE THREAD

**Issue by stepanvanzuriak** [schrodinger/fixed-data-table-2#533]
If you use pure rendering and column resize some columns may become unacceptable for scrolling 

## Current Behavior
Wrong resize when column use pure rendering 

## Steps to Reproduce (for bugs)
Codesandbox: https://codesandbox.io/s/zealous-hofstadter-bb9bf?file=/src/App.js

![RECORD](https://user-images.githubusercontent.com/33158700/82327272-d0a19680-99e6-11ea-8cb9-0ae29e7bebc6.gif)

**Comment by wcjordan** [comment]
Thanks for filing, the codesandbox is very helpful!  It looks like our pureRendering logic causes cells to not re-render when only the width is changed.  I'll take a look and see if it can be fixed.

**Comment by wcjordan** [comment]
Put a fix up for PR w/ #535

**Comment by wcjordan** [comment]
This fix is now released w/ v.1.1.1
