### ISSUE TITLE
How to set empty content when the table is empty?

### ISSUE THREAD

**Issue by WangYang-Rex** [schrodinger/fixed-data-table-2#537]
How to set empty content when the table is empty?

**Comment by wcjordan** [comment]
You're best bet is to create a HOC which wraps the table and renders a separate component when the row count is 0.  We don't have an example but I'm happy to work with you to add one if you want to put up a PR.  Thanks.

I'm going to close this, but feel free to ask any follow up questions here and I'll answer as best I can.
