### ISSUE TITLE
Is there a way to merge row or cell?

### ISSUE THREAD

**Issue by shuozhang2016** [schrodinger/fixed-data-table-2#539]
## Expected Behavior
![image](https://user-images.githubusercontent.com/17228552/83095293-92d2fb00-a0d5-11ea-8839-7b4e3d757046.png)

**Comment by wcjordan** [comment]
Not natively within FDT.  There are some discussions to implement these things w/ #183 & #300.  I'm going to close this, but please feel to add details or discuss ideas on those issues.
