### ISSUE TITLE
Any idea about loading more content when scrolling to the bottom of table

### ISSUE THREAD

**Issue by shuozhang2016** [schrodinger/fixed-data-table-2#541]
## Expected Behavior
![image](https://user-images.githubusercontent.com/17228552/83095721-89965e00-a0d6-11ea-9177-bba9d38f4a46.png)

**Comment by wcjordan** [comment]
I recommend looking at the [infinite scroll example](http://schrodinger.github.io/fixed-data-table-2/example-infinite-scroll.html) for a starting point.  I'm going to close this ticket, but feel free to respond here if ya have additional questions or there's more I can help with.
