### ISSUE TITLE
Moving the typescript types to the core lib?

### ISSUE THREAD

**Issue by apieceofbart** [schrodinger/fixed-data-table-2#546]
I saw some of the types to be off and it's not surprising given that they were last updated almost 2 years ago. 
Are you open to moving them to the fixed-data-table-2 packaged instead of keeping them in @types?
Even better: did you consider rewriting the lib to typescript?

**Comment by wcjordan** [comment]
We don't maintain or work on the types.  Currently there are no plans to do anything with them or to maintain them from our end.
