### ISSUE TITLE
Only track vertical scrolling on onScrollEnd

### ISSUE THREAD

**Issue by vcardins** [schrodinger/fixed-data-table-2#548]
I want to be able to fetch more data if the scroll reaches the end of the table only if I'm scrolling vertically. How could I check if it's scrolling only horizontally?

**Comment by wcjordan** [comment]
I'm not sure I fully understand the question, but the table takes an onScrollEnd prop which will be called with the parameters: scrollX, scrollY, firstRowIndex, and endRowIndex.  You can handle that callback to see how the table has scrolled and take the appropriate actions.

**Comment by vcardins** [comment]
The question is exactly how to know whether the table has scrolled only horizontally. If so, I won't check if there are more records to load, otherwise, if the `endRowIndex` is equaled to the total of items, I call the API again.
