### ISSUE TITLE
Is there any way to show scrollbar only when mouse over to table. 

### ISSUE THREAD

**Issue by SivakumarSkr** [schrodinger/fixed-data-table-2#563]
How can show scrollbar only when mouseover? 
Why scroll bar is in rectangle shape? how can i change curve at edge?

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by wcjordan** [comment]
We don't have any examples of this, but you can provide your own scrollbars w/ FDT.  More info can be found in #507 and #518, and you can refer to the [default scrollbar implementation here](https://github.com/schrodinger/fixed-data-table-2/blob/master/src/plugins/Scrollbar.js#L171).

I'm going to close as there's nothing more for us to do, but feel free to follow up here w/ any questions you have.
