### ISSUE TITLE
React 17 question

### ISSUE THREAD

**Issue by rallard71** [schrodinger/fixed-data-table-2#572]
I still have the warning even though I have the version "fixed-data-table-2": "^1.1.2": 

_Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
...
Please update the following components: FixedDataTableContainer_

I don't want to upgrade to React 17 because of it.

Is there a way to fix the warning?
thx.

**Comment by chhsiao1981** [comment]
#523

**Comment by rallard71** [comment]
Ok thank you @jimmyhmiller for your answer
