### ISSUE TITLE
How to group the rows , under a row

### ISSUE THREAD

**Issue by AdityaKallur** [schrodinger/fixed-data-table-2#593]

**Comment by AdityaKallur** [comment]
![image](https://user-images.githubusercontent.com/83698184/123596446-d4b9fd80-d80f-11eb-8d39-b3656971050c.png)

**Comment by pradeepnschrodinger** [comment]
Following the suggestions from https://github.com/schrodinger/fixed-data-table-2/issues/299#issuecomment-367901973:
1. If you just need to render some content underneath a row, you can use the `rowExpanded` prop to pass in a custom react component (refer the [expanded rows example](http://schrodinger.github.io/fixed-data-table-2/example-expanded-rows.html)).
You could also render sub tables as the expanded content.

2. Render the rows as you want and use the first columns' cell renderers to give a UX feel of column grouping.

I'm closing the issue, but feel free to continue the discussion here.
