### ISSUE TITLE
Checkbox on top row remains checked no matter what

### ISSUE THREAD

**Issue by Gothbag** [schrodinger/fixed-data-table-2#65]
## Expected Behavior

I'm rendering a checkbox on each row that is used to mark the elements that have to be removed from the table when clicking a button. When removing the top row I would expect the checkbox on the row below (now the one on top) not to be checked.
## Current Behavior

But as it stands right now, when removing the top row (whose checkbox was checked), the checkbox on the the row below (now on top) remains checked.
## Possible Solution

I imagine that the reason for the bug is that React somehow thinks that the "new" top row is the same as the previous one.
## Steps to Reproduce (for bugs)

Will provide a link to a fiddle as son as possible.
## Context

The context and what I'm trying to accomplish is pretty clear.
## Your Environment

- Version used: 0.7.2
- Browser Name and version: Internet Explorer 11
- Operating System and version (desktop or mobile): Windows 7 Enterprise

**Comment by KamranAsif** [comment]
This is similar to https://github.com/schrodinger/fixed-data-table-2/issues/18
Can you try using this solution proposed here to see if your issue goes away? https://github.com/schrodinger/fixed-data-table-2/issues/18#issuecomment-227744217

**Comment by wcjordan** [comment]
I'm going to close this since a solution was given and the ticket has been inactive since then
