### ISSUE TITLE
Z-index 1 set on column header causes header to overlap other elements

### ISSUE THREAD

**Issue by grosiles3** [schrodinger/fixed-data-table-2#652]
Hello team,

We are running into an issue where because there is a z index 1 set on the column header, if an element overlaps the header as shown below, the header is shown above the element, leading to unwanted results. Can the team please implement a fix where no z-index is set on the header? 

![image](https://user-images.githubusercontent.com/100440855/177613588-46a3498d-51db-463b-ae56-3898f5d951e0.png)

Thanks,
Guillermo Rosiles

**Comment by Tanner-MS** [comment]
I would alter this ask slightly and ask for a solution that doesn't use any z-indexes (scrollbars as well)

**Comment by pradeepnschrodinger** [comment]
@grosiles3 , could you mention the environment used here? --
Such as the version of FDT being used, OS name and version, browser name and version, and whether this is on PC or on mobile?

It would also be great if you could provide a way for us to reproduce this, maybe on [codesandbox](https://codesandbox.io/s/fixed-data-table-basic-example-cwds0?file=/src/index.js).

**Comment by grosiles3** [comment]
Hi Niranjan,

Sure, we are using the latest version of FDT (1.2.11) although this issue has existed for a very long time from what I can see. I mainly use Chrome (current version 103.0.5060.114) but it also repro's in other browsers, such as Edge. I've only ever tested this on PC not sure what it looks like on mobile.

I created a sandbox that repro's it here - https://codesandbox.io/s/fixed-right-column-forked-jufkcr

If you mouse over  "mouse over me", notice how the dropdown gets hidden behind the column header (because that row has a z-index of 1)
***@***.***

and this is what the dropdown should look like
***@***.***

Let us know if you have any other questions.

Thanks,
Guillermo Rosiles

**Comment by pradeepnschrodinger** [comment]
Thanks for the example and env details! I had to slightly tweak the codesandbox to render the table but I can reproduce the issue.

I think the simplest thing to do here is adjust z-Indices of the components.
You could either increase the z-Index of the dropdowns/popouts/etc to something higher than the the header row (2 or above in our case).
Or a simpler solution would be to just set the z-Index of the table container to zero.

https://codesandbox.io/s/fixed-right-column-forked-zo0t1j?file=/Index.css
```less
.fixedDataTableLayout_main {
  z-index: 0;
}
```
![image](https://user-images.githubusercontent.com/41563608/178906319-dd3c1b03-189a-4c86-b7f3-0d2d9c24b5e1.png)

Let me know if this works out for you.
