### ISSUE TITLE
Horizontal scrolling doesn't work in Chrome

### ISSUE THREAD

**Issue by sheerun** [schrodinger/fixed-data-table-2#66]
1. Go to your [primary example](http://schrodinger.github.io/fixed-data-table-2/example-object-data.html)
2. Scroll with macbook touchpad to the right side of the table
3. Scroll back to the left

## Expected Behavior

Table is scrolling to the left

## Current Behavior

Chrome goes back in history

## Possible Solution

Probably fixed-data-table "unfolds" too slow when scrolling to the left, so chrome triggers "history back" gestory. I found no way to prevent this geature programmatically without destroying table's behavior. There are some plugins for this, but none of them actually works.

* Version used: 0.7.5
* Browser Name and version: Google Chrome 53
* Operating System and version (desktop or mobile): OSX 10.11.6

![](https://media.giphy.com/media/3oz8xM6D3Kc1maOSzu/giphy.gif)

**Comment by wcjordan** [comment]
Peculiar, this works pretty smoothly for me on Chrome 54 and El Capitan (10.11.6).  @KamranAsif are you able to reproduce this?

**Comment by sheerun** [comment]
Spent 15 minutes filing an issue, upgraded chrome from 53 to 54, issue is fixed... oh well

**Comment by wcjordan** [comment]
Glad you were able to resolve it.  Let us know if you see similar issues in the future. Thanks!

**Comment by josh08h** [comment]
I am seeing this behaviour in Chrome 58.0.3029.96 (64-bit) El Capitan 10.11.6)
