### ISSUE TITLE
Limitation of row count due to the max height of any HTML Dom element

### ISSUE THREAD

**Issue by lujinappfolio** [schrodinger/fixed-data-table-2#67]
When loading a large number of rows to the fixed-data-table-2 component, rows at the bottom of the table may not be rendered currently. Sometimes it can even crash the browser. This is caused by the height limit of a HTML Dom element in the browser. Different browsers may have different limit. In the implementation of the fixed-data-table-2, it uses a sliding canvas container to expose rows that are visible depending on the window size and the scrolling position. The height of the canvas is the combined height of all rows, visible and hidden. If the combined height exceeds the allowed height of any element in the Dom structure, rows at the bottom with a top offset larger than the limited value, won't be displayed correctly.
## Expected Behavior

Any number of rows can be rendered correctly with no feature broken.
## Current Behavior

When loading a large number rows, the rows at the bottom can't be rendered correctly. It may crash the browser if using FF.
## Possible Solution

Instead of using a sliding canvas and setting the height of the canvas to be literally the combined height of all rows, we can simply slide the visible rows up or down to by a calculated offset to bring them to the right position that they can be seen. The offset will always be less than combined the height of visible rows, which will never exceed the limit of any browsers.
## Steps to Reproduce (for bugs)
- Navigate to the example page: 'http://schrodinger.github.io/fixed-data-table-2/example-object-data.html'. 
- Scroll down to the bottom. There is a big blank (in Chrome).
- Then scroll up to the last visible row. It's a little overlapped with the one above it.
## Context

By using a buffered design, we could load a large number of data to the component. But this issue prevents us from doing so. Because it won't allow rows at the bottom of the table to be rendered correctly.
## Your Environment
- Version used: Most up-to-date
- Browser Name and version: Chrome Version 53.0.2785.143 (64-bit)
- Operating System and version (desktop or mobile): Mac Sierra v10.12

**Comment by KamranAsif** [comment]
Resolved with #67
