### ISSUE TITLE
Can't style vertical lines between column groups

### ISSUE THREAD

**Issue by AdamPD** [schrodinger/fixed-data-table-2#70]
Currently, we can't find any way to style vertical lines between column groups.  We know that we can do it when you're using fixed column groups, but we simply want a vertical line through the entire table for each column groups (when none are fixed).
## Expected Behavior

We'd like to be able to have a public style where we can add a nice border/vertical line through the edge of each column group to give a user clear grouping of columns.  We don't want a vertical line for every single column - just the grouped ones.
## Current Behavior

Currently, the only way is to use fixed column groups, which means you can only have "effectively" two column groups with the vertical line through them.  We've looked at the CSS and there are no "overarching" cell group elements, nor are there any special CSS classes on the start/end columns in a group.
## Possible Solution

The easiest solution would be to add a public CSS class to the start of every column group (e.g. public_fixedDataTableCell_cellFirstInGroup or something).
## Context

Ideally, the user should see nice column groups in the table spanning the entire height.  This helps our users analyse different parts of the table clearly.

**Comment by wcjordan** [comment]
Hey Adam, sorry I've left this hanging without responding.  I'm looking into the issue, but our rendering of cell groups doesn't provide a great component for styling.  I'm going to dig in a bit deeper and hopefully can find somewhere to add something.  Once again sorry for the delay.

Also I'm going to link this to https://github.com/schrodinger/fixed-data-table-2/issues/60 to ensure we make this easier with longer term styling changes.

**Comment by wcjordan** [comment]
Hey, I've put a PR for this up at #83.  Could you check that branch out and see if it meets your needs?

**Comment by wcjordan** [comment]
I'm going to close this due to inactivity.
