### ISSUE TITLE
Resize line not shown when "maxHeight" is set.

### ISSUE THREAD

**Issue by daniela-mateescu** [schrodinger/fixed-data-table-2#704]
The resize line is shown only when the table is configures by setting the ```height``` property. It is not shown when the table is configured using only ```maxHeight```

## Expected Behavior
For a table configured using ```maxHeight```, when resizing a column, the resize line should appear. Just like in the case of a the table configured using the ```height``` property:
https://youtu.be/GzkgbgOk5CU

## Current Behavior
The resize line is not appearing
https://youtu.be/dVY1S15phRY

## Possible Solution
I have created a pull request for this : https://github.com/schrodinger/fixed-data-table-2/pull/703

## Steps to Reproduce (for bugs)
The problem can be seen in the following example by resizing the first column.
(https://codesandbox.io/s/resize-line-not-showing-7t4m2p?file=/src/index.js)

**Comment by karry08** [comment]
Thanks @daniela-mateescu for reporting this issue and also for providing the codesandbox links and the clips which were really helpful. 
We will also review the PR soon.

**Comment by karry08** [comment]
This is fixed with [v2.0.2](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v2.0.2) release
