### ISSUE TITLE
version for React 15

### ISSUE THREAD

**Issue by flyingpath** [schrodinger/fixed-data-table-2#71]
Hello! Is there a version for  react 15.3.2 ? 

I used version 0.6.1 fixed-data-table before, but there is a warning about div and columnKey.

I know that fixed-data-table-2 seems solved this question.

After installed the fixed-data-table-2, there is a conflict caused by version.

How do I solve the question?

Thanks very much!!

**Comment by KamranAsif** [comment]
Hey, were you able to resolve this?

**Comment by flyingpath** [comment]
Thanks for response! 
Ya.. I updated fixed-data-table to 0.6.2 and solved it.
But it still fixed-data-table.
Could fixed-data-table2 support react15.3.2?

**Comment by KamranAsif** [comment]
Thats strange..I would have expected _us_ to support it. I'm going to reopen this

**Comment by flyingpath** [comment]
It will install react 0.14.8 when I used npm install.
Or there is a specific version for react 15?

**Comment by KamranAsif** [comment]
You should specify which version of react you want to use. It probably just insteads 0.14.8 because thats the minimum support version.

**Comment by flyingpath** [comment]
How to specify it?
there is a warning
"requires a peer of react@>=0.13.0 || ^0.14.0-beta3 but none was installed" ( I install react15.3.2)

Sorry, I am new. Thanks a lot!

**Comment by KamranAsif** [comment]
Can you try running
'npm install --save react@15.3.2' and then try installing fixed-data-table-2 again?

**Comment by flyingpath** [comment]
Amazing! It works!!
Thanks a lot!!

Besides, it still failed when installed it by 'jspm install npm:fixed-data-table-2' (will install react0.14.8)
even if I had used 'jspm install npm:react@15.3.2' first. 
But in npm, it solved! I could work with npm only.

Thanks!!

**Comment by geoffreyfloyd** [comment]
The package.json file is still clearly wrong in latest source, and this should be reopened, despite whatever hack gets around it, the peerDependency section should be expanded to include 15 and up, instead of just 13 & 14.

**Comment by wcjordan** [comment]
Our understanding is 15.x.x is >= 0.13.0 and as such is considered an acceptable peer dependency.  Could you provide instructions to reproduce what you're seeing?

On a side note, we can probably remove support for 0.14.0-beta3 at this time.
