### ISSUE TITLE
Do you plan realize grouping like in this example http://adazzle.github.io/react-data-grid/examples.html#/grouping ?

### ISSUE THREAD

**Issue by ophite** [schrodinger/fixed-data-table-2#79]

**Comment by wcjordan** [comment]
No we don't have any plans for grouping rows based on values.  In the long term we may add support for cells which span multiple columns but we would leave it to outside extensions to use that primitive to build functionality like this.

**Comment by KamranAsif** [comment]
+1, this can easily be done via react outside of the table. I think as a rule of thumb, we want to avoid adding features that can be done via normal react. This is why the library doesn't support primitive functionality like sorting/filtering. We don't restrict the data format, allowing greater flexibility.

**Comment by ophite** [comment]
Maybe you can say more about how it could be done with standard react inside your grid system ?

**Comment by KamranAsif** [comment]
Hey. 

Sorry I forgot to reply to this. You can do it similar to how I did this one:
https://jsfiddle.net/pns30rfx/
