### ISSUE TITLE
Browser support information

### ISSUE THREAD

**Issue by KamranAsif** [schrodinger/fixed-data-table-2#8]
Original issue here: https://github.com/facebook/fixed-data-table/issues/56

Do we plan on only supporting IE11 going forward? I think its important to hear what the community has to say about this

**Comment by 3cooper** [comment]
For us, IE 11 support would be important.  Our customers aren't there yet, but they will be soon.  Do you know of any current issues with IE 11?

**Comment by KamranAsif** [comment]
Even though we've been testing this pretty aggressively, we haven't currently seen any major issues with it. There are reports of touch scrolling break on windows machines though.

**Comment by ryanhca** [comment]
What's the deal with not testing/supporting Safari? I have seen a UI issue here and there and have no real way to iron out the bugs I'm seeing.

**Comment by wcjordan** [comment]
We currently don't have the resources or test infrastructure to support browsers outside of our common usage.  We're happy to accept PRs for fixes though or add support if new maintainers join the project who want to take on that responsibility.

**Comment by KamranAsif** [comment]
@ryanhca If you see safari issues, please still file issues so others can try and tackle it.
