### ISSUE TITLE
Alternative Name RFC

### ISSUE THREAD

**Issue by KamranAsif** [schrodinger/fixed-data-table-2#81]
FDT2 has grown modestly over the last couple months. I think it's time to rename the repository to differentiate from the original repo.

The driving forces behind this are as follows:
- We want to start introducing breaking changes into the API. We don't want someone migration from FDT to just append '-2' to their package.json and expect full compatibility
- We want to increase community awareness and feedback. I think living in the shadow of a much larger repository will hinder that.
- We aren't as 'Fixed' in FixedDataTable anymore, so the name itself has lost some meaning
- We have plans for v1.0 release, and it would be an excellent springboard

We have some big plans in the future to make the code much easier to work with and more contributor friendly. 

Please feel free to suggest names and thumbs up the ones you like!

**Comment by mirko77** [comment]
ReactDataGrid

**Comment by gforge** [comment]
While I sympathise with the name change I think you may want to wait until the fork has more traction. The reason I found FDT2 was through identifying it as a fork off FDT and it felt safe to bet on something that was originally released by Facebook.

**Comment by KamranAsif** [comment]
I'm going to close this, since I think @gforge  makes a strong argument.

**Comment by wcjordan** [comment]
:(  One day... one day...
