### ISSUE TITLE
The scroll bar disappears and the user can't see all the data from the table.

### ISSUE THREAD

**Issue by AlexandruB** [schrodinger/fixed-data-table-2#87]
The scroll bar disappears and the user can't see all the data from the table.

1. Go to [Client-side Filter](http://schrodinger.github.io/fixed-data-table-2/example-filter.html) example.
2. Add a filter text that shows only a couple of items and the vertical scroll bar is not visible.
3. Make the page smaller until the vertical scroll bar appears. 
4. Scroll down to see the last row.
5. Make the page larger so the scroll bar disappears. 

## Expected Behavior
All rows should be visible. 

## Current Behavior
Only a part of the rows are visible.

## Steps to Reproduce (for bugs)
It can be reproduced on [Example Filter](http://schrodinger.github.io/fixed-data-table-2/example-filter.html) 

## Context
I think this is a general issue for all use cases that have table resize.

## Your Environment
* Version used: 0.7.7
* Browser Name and version: Chrome  54.0.2840.99 m (64-bit)
* Operating System and version (desktop or mobile): Desktop Win 10.

**Comment by KamranAsif** [comment]
Thanks for filing this bug! I'll take a look at fixing it in 0.7.x but it'll def be fixed in 0.8.0 when we move to redux

**Comment by larrydahooster** [comment]
Nice. Thanks for reporting the issue. I was facing the same issue in my project. I have a dashboard where you can resize the dimensions of tiles on it.

Once you resize the table to a height where the scrollbars are no longer required, they simply disappear and with them the ability to scrolling also goes away.

I created two gifs, Example 1 shows scrolling to the bottom of the table and resizing it to a heigth where the scrollbar still is visible (calculated by height of table and rows in it)
![scrollbars stay](https://cloud.githubusercontent.com/assets/4989851/20716391/571330a6-b652-11e6-9ea8-3376f3ec03b8.gif)

Example 2 shows a scenario where you scroll to bottom and resize the table to a dimension where the calculated scrollbars are no longer required and you can no longer scroll

![scrollbars disappear](https://cloud.githubusercontent.com/assets/4989851/20716469/9e2071e8-b652-11e6-93a3-b9d9449c7e34.gif)

**Comment by AlexandruB** [comment]
As a side note, this issue is also reproducible in fixed-data-table (facebook).

**Comment by KamranAsif** [comment]
This will be fixed as part of v0.8
