### ISSUE TITLE
Create migration docs from fb/FDT

### ISSUE THREAD

**Issue by KamranAsif** [schrodinger/fixed-data-table-2#90]
We currently have [v0.6 API Migratio](http://schrodinger.github.io/fixed-data-table-2/v6-migration.html)n docs which is largely unused. We should instead refactor this to be a migration guide coming from facebooks fixed-data-table v0.6.3.

Currently we don't have any breaking features but we should list new APIs, new features and maybe resolved bugs from the origin repo.

**Comment by wcjordan** [comment]
Closing this as it's old an it would be better effort to focus on documenting current state.
