### ISSUE TITLE
Some message when table data is empty

### ISSUE THREAD

**Issue by neospyk** [schrodinger/fixed-data-table-2#92]
If table has not any record, show message "No records" in the table body

## Expected Behavior
Message in table when table is empty

## Current Behavior
Showing only header cells

## Possible Solution
Put some span with text to body, something like:
```javascript
<span>{this.props.emptyDataMessage}</span>
```

to file https://github.com/schrodinger/fixed-data-table-2/blob/master/src/FixedDataTable.js:

```javascript
render() /*object*/ {
   ...
    return (
      <div
        className={joinClasses(
          this.state.className,
          cx('fixedDataTableLayout/main'),
          cx('public/fixedDataTable/main'),
        )}
        onWheel={this._wheelHandler.onWheel}
        onTouchStart={this._touchHandler.onTouchStart}
        onTouchEnd={this._touchHandler.onTouchEnd}
        onTouchMove={this._touchHandler.onTouchMove}
        onTouchCancel={this._touchHandler.onTouchCancel}
        style={{height: state.height, width: state.width}}>
        <div
          className={cx('fixedDataTableLayout/rowsContainer')}
          style={{height: rowsContainerHeight, width: state.width}}>
          {dragKnob}
          {groupHeader}
          {header}
          {rows}
          {footer}
          {topShadow}
          {bottomShadow}
        </div>
        {rows.length ? "" :  <span>{this.props.emptyDataMessage}</span> }
        {verticalScrollbar}
        {horizontalScrollbar}
      </div>
    );
},
```

## Context
It will more usefull when table will empty. For now we have implementation like div under the table, and have more problem with resizing page, or etc. 
Functional like this, there is in a lot of table components.
![Image of example](https://i.imgsafe.org/5837014534.png)

## Your Environment

* Version used: 0.7.7
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Mint 18
* Link to your project:

**Comment by KamranAsif** [comment]
Hmm I think the multi-row feature will make this easy to implement.
Its on the roadmap for v1.0+ http://schrodinger.github.io/fixed-data-table-2/roadmap.html

**Comment by wcjordan** [comment]
I think you could also implement this with a HOC without much difficulty by just wrapping the FDT in a component that renders and additional div below the table if the table is empty.

Rather than support this in FDT, I encourage you to build that HOC.  If you want to create a PR with an example demonstrating how it can be done for future interested parties, we'd appreciate that.

**Comment by KamranAsif** [comment]
Closing since there isn't any follow up here.
