### ISSUE TITLE
Make CSS inline instead of global?

### ISSUE THREAD

**Issue by sontek** [schrodinger/fixed-data-table-2#94]
We use cssmodules so we have no global CSS and so we'd like to be able to use fixed-data-table-2 but we have no place to load global CSS.

Could you use CSS modules or inline styles for this component so they are isolated?

**Comment by sontek** [comment]
I think this might be related to this:

https://github.com/schrodinger/fixed-data-table-2/issues/61

But I guess another reason to do so.  #61 is more of a technical issue where as I need it more for isolation so components I get from `node_modules/` don't affect my application outside of themselves.

**Comment by KamranAsif** [comment]
This isn't super high on our priority right now (you can checkout our roadmap on the site)

Please feel free to put up a PR for this. If you can do an isolated example we should be able to jump in and migrate the rest of it.

**Comment by KamranAsif** [comment]
Closing this in favor of #61
